import { defineItem } from '@motif/schema'

const option = (value: string, zh: string, en: string) => ({ value, label: { 'zh-CN': zh, en } })

export default defineItem({
  schemaVersion: 1,
  slug: 'image-transitions',
  status: 'published',
  title: { 'zh-CN': '图像转场', en: 'Image Transitions' },
  summary: {
    'zh-CN': '十种精选的 WebGL 转场：扭曲、缩放、立方体、涟漪、波点……在几幅画面之间自动循环切换。适合做作品集切换、幻灯片和首屏轮播。',
    en: 'Ten hand-picked WebGL transitions (warps, zooms, cube, ripple, polka dots and more) that loop between a few slides on their own. Made for portfolio reels, slideshows and hero carousels.',
  },
  category: 'transition',
  tags: ['transition', 'slideshow', 'carousel', 'webgl', 'shader', 'gl-transitions'],
  runtime: ['react', 'webgl', 'canvas2d'],
  entry: { file: 'image-transitions.tsx', export: 'ImageTransitions' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'image-transitions.tsx', role: 'component' },
    { path: 'shaders.ts', role: 'shader' },
    { path: 'artwork.ts', role: 'lib' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    {
      key: 'transition',
      type: 'select',
      label: { 'zh-CN': '转场', en: 'Transition' },
      default: 'crosswarp',
      options: [
        option('crosswarp', '交错扭曲', 'Crosswarp'),
        option('crosszoom', '十字缩放', 'Cross zoom'),
        option('directional-warp', '方向扭曲', 'Directional warp'),
        option('ripple', '涟漪', 'Ripple'),
        option('swirl', '漩涡', 'Swirl'),
        option('cube', '立方体', 'Cube'),
        option('glitch-memories', '故障记忆', 'Glitch memories'),
        option('polka-dots', '波点幕布', 'Polka dots'),
        option('circle-open', '圆形展开', 'Circle open'),
        option('dreamy-zoom', '梦幻缩放', 'Dreamy zoom'),
      ],
    },
    {
      key: 'duration',
      type: 'number',
      label: { 'zh-CN': '转场时长', en: 'Duration' },
      default: 1.6,
      min: 0.4,
      max: 3.5,
      step: 0.05,
      unit: 's',
      safe: [0.8, 2.4],
      group: 'motion',
    },
    {
      key: 'pause',
      type: 'number',
      label: { 'zh-CN': '停留时长', en: 'Pause' },
      hint: { 'zh-CN': '每幅画面停住多久再转场', en: 'How long each slide holds before the next transition' },
      default: 1.2,
      min: 0.2,
      max: 5,
      step: 0.05,
      unit: 's',
      group: 'motion',
    },
    { key: 'easing', type: 'easing', label: { 'zh-CN': '缓动', en: 'Easing' }, default: [0.65, 0, 0.35, 1], group: 'motion' },
    {
      key: 'scheme',
      type: 'select',
      label: { 'zh-CN': '配色', en: 'Palette' },
      default: 'dusk',
      options: [option('dusk', '暮色', 'Dusk'), option('mono', '黑白红', 'Mono'), option('lagoon', '泻湖', 'Lagoon'), option('candy', '糖果', 'Candy')],
      group: 'look',
    },
    {
      key: 'slides',
      type: 'select',
      label: { 'zh-CN': '画面数量', en: 'Slides' },
      hint: { 'zh-CN': '两幅来回切换，三幅依次轮播', en: 'Two slides ping-pong, three run in sequence' },
      default: '2',
      options: [option('2', '两幅（A→B→A）', 'Two (A→B→A)'), option('3', '三幅（A→B→C）', 'Three (A→B→C)')],
      group: 'look',
    },
  ],
  presets: [
    {
      id: 'nocturne',
      name: { 'zh-CN': '夜曲', en: 'Nocturne' },
      values: { transition: 'crosswarp', scheme: 'dusk', duration: 1.6, pause: 1.2 },
    },
    {
      id: 'monochrome-cube',
      name: { 'zh-CN': '黑白立方', en: 'Monochrome cube' },
      values: { transition: 'cube', scheme: 'mono', duration: 1.8, pause: 1, slides: '3', easing: [0.7, 0, 0.3, 1] },
    },
    {
      id: 'tide',
      name: { 'zh-CN': '潮汐', en: 'Tide' },
      values: { transition: 'ripple', scheme: 'lagoon', duration: 2.2, pause: 1.2, easing: [0.4, 0, 0.2, 1] },
    },
    {
      id: 'confetti',
      name: { 'zh-CN': '彩纸', en: 'Confetti' },
      values: { transition: 'polka-dots', scheme: 'candy', duration: 1.4, pause: 1, slides: '3' },
    },
    {
      id: 'static-burst',
      name: { 'zh-CN': '信号噪点', en: 'Static burst' },
      values: { transition: 'glitch-memories', scheme: 'mono', duration: 1.2, pause: 1.4, easing: [0.3, 0, 0.7, 1] },
    },
  ],
  dependencies: ['@motif/runtime'],
  perf: { webgl: true, maxDpr: 1.5 },
  a11y: { reducedMotion: 'static' },
  capture: { posterTime: 2, loop: 5.6 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'gl-transitions',
      repo: 'gl-transitions/gl-transitions',
      sha: '902218a1b63773ac0d0d9f491951da3392365bfe',
      paths: [
        'transitions/crosswarp.glsl',
        'transitions/CrossZoom.glsl',
        'transitions/directionalwarp.glsl',
        'transitions/ripple.glsl',
        'transitions/swirl.glsl',
        'transitions/cube.glsl',
        'transitions/GlitchMemories.glsl',
        'transitions/PolkaDotsCurtain.glsl',
        'transitions/circleopen.glsl',
        'transitions/DreamyZoom.glsl',
      ],
      spdx: 'MIT',
      copyright: ['Copyright (c) 2017-present gl-transitions contributors'],
      origin: 'Each transition keeps its own Author and License header (all MIT): crosswarp by Eke Péter, CrossZoom by rectalogic, directionalwarp by pschroen, ripple, cube and circleopen by gre, swirl by Sergey Kosarevsky, GlitchMemories by Gunnar Roth, PolkaDotsCurtain by bobylito, DreamyZoom by Zeh Fernando.',
    },
    modifications: [
      'Embedded ten transitions verbatim as strings in shaders.ts, together with the default uniform values from their comments; the GLSL is unchanged (non-ASCII characters in comments are stripped when the shader is compiled).',
      'Wrote a small renderer following the gl-transitions convention (progress, ratio, getFromColor, getToColor) on motif-runtime: pauses offscreen and in hidden tabs, shows the first slide under reduced motion, handles context loss and releases the context on unmount.',
      'Textures cover-fit the canvas so any aspect ratio works; the timeline (pause, duration, cubic-bezier easing) and the slides are Motif’s.',
      'The slides are drawn at runtime with Canvas 2D from code, so the item ships no image files.',
    ],
    assets: [],
  },
})
