import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'energy-orb',
  status: 'published',
  title: { 'zh-CN': '能量球', en: 'Energy Orb' },
  summary: {
    'zh-CN': '暗夜里悬着一颗由分形烟雾织成的能量球，边缘泛着柔和的辉光，背后有缓缓漂移的星点。适合做 AI、算力、网络类产品的首屏背景。',
    en: 'A sphere of fractal smoke floating in the dark, its rim wrapped in a soft glow and a slow field of stars drifting behind. A hero background for AI, compute and network products.',
  },
  category: 'shader',
  tags: ['orb', 'sphere', 'globe', 'fbm', 'smoke', 'glow', 'stars', 'webgl', 'canvas2d', 'background'],
  runtime: ['react', 'webgl', 'canvas2d'],
  entry: { file: 'energy-orb.tsx', export: 'EnergyOrb' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'energy-orb.tsx', role: 'component' },
    { path: 'shaders.ts', role: 'shader' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    { key: 'speed', type: 'number', label: { 'zh-CN': '速度', en: 'Speed' }, default: 1, min: 0, max: 2.5, step: 0.01, unit: 'x', safe: [0.3, 1.6], group: 'motion' },
    { key: 'scale', type: 'number', label: { 'zh-CN': '球体大小', en: 'Orb scale' }, default: 1.12, min: 0.8, max: 1.9, step: 0.01, safe: [1, 1.7], group: 'look' },
    {
      key: 'smokeScale',
      type: 'number',
      label: { 'zh-CN': '烟雾尺度', en: 'Smoke scale' },
      hint: { 'zh-CN': '越大烟雾纹理越细碎', en: 'Higher values make finer smoke' },
      default: 1,
      min: 0.5,
      max: 2.2,
      step: 0.01,
      safe: [0.6, 1.8],
      group: 'look',
    },
    { key: 'smokeStrength', type: 'number', label: { 'zh-CN': '烟雾强度', en: 'Smoke strength' }, default: 1, min: 0.3, max: 1.6, step: 0.01, group: 'look' },
    { key: 'glow', type: 'number', label: { 'zh-CN': '辉光', en: 'Glow' }, default: 1.25, min: 0.4, max: 1.6, step: 0.01, group: 'look' },
    { key: 'hue', type: 'number', label: { 'zh-CN': '色相', en: 'Hue' }, default: 0, min: -180, max: 180, step: 1, unit: 'deg', group: 'color' },
    { key: 'saturation', type: 'number', label: { 'zh-CN': '饱和度', en: 'Saturation' }, default: 1, min: 0.2, max: 1.6, step: 0.01, group: 'color' },
    { key: 'brightness', type: 'number', label: { 'zh-CN': '亮度', en: 'Brightness' }, default: 1, min: 0.7, max: 1.5, step: 0.01, group: 'color' },
    { key: 'starDensity', type: 'number', label: { 'zh-CN': '星点密度', en: 'Star density' }, default: 1, min: 0, max: 2, step: 0.01, group: 'stars' },
  ],
  presets: [
    { id: 'dusk', name: { 'zh-CN': '暮紫', en: 'Dusk' }, values: {} },
    { id: 'ember', name: { 'zh-CN': '余烬', en: 'Ember' }, values: { hue: 140, saturation: 1.15, glow: 1.2, smokeStrength: 1.2, starDensity: 0.6 } },
    { id: 'aurora', name: { 'zh-CN': '极光', en: 'Aurora' }, values: { hue: -95, saturation: 1.3, speed: 0.7, smokeScale: 0.8, starDensity: 1.4 } },
    { id: 'ghost', name: { 'zh-CN': '幽灵', en: 'Ghost' }, values: { saturation: 0.25, brightness: 1.15, glow: 0.8, smokeScale: 1.5, starDensity: 0.4 } },
    { id: 'nebula', name: { 'zh-CN': '星云', en: 'Nebula' }, values: { scale: 1.75, smokeScale: 0.6, smokeStrength: 1.5, glow: 1.4, starDensity: 2, speed: 0.6 } },
  ],
  dependencies: ['@motif/runtime'],
  perf: { webgl: true, maxDpr: 2 },
  a11y: { reducedMotion: 'static' },
  capture: { posterTime: 3 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'threeui',
      repo: 'MengTo/threeui',
      sha: '68802d5428071ada5c20db8094b1649e6bb770ed',
      paths: ['src/shaders/energy-orb/EnergyOrb.tsx', 'src/shaders/energy-orb/energyOrbShaders.ts', 'src/shaders/globe/GlobeCollection.tsx'],
      spdx: 'MIT',
      copyright: ['Copyright (c) 2026 Meng To'],
      origin: 'HTML Pages + Neuform export',
    },
    modifications: [
      'The render loops now use motif-runtime: pause offscreen and in hidden tabs, render a static frame under reduced motion, and cap the star canvas DPR at 1.5.',
      'Handles WebGL context loss and restore, and releases the context on unmount.',
      'Only the configurable fragment shader is kept (the canonical unparameterised copy is dropped); smoke speed, star speed, star size and opacity are fixed at their defaults.',
      'Orb time is accumulated from frame deltas so changing speed never jumps the animation; the default orb scale is 1.12 so it fills a background.',
      'Defaults moved into the generated defaults region; children can be layered on top.',
    ],
    assets: [],
  },
})
