import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'tidepool-startup-landing',
  status: 'published',
  title: { 'zh-CN': '创业公司全站落地页', en: 'Startup Landing Site' },
  summary: {
    'zh-CN': '经典的创业公司官网：装饰圆环首屏、六宫格功能、产品视频区、左右交替图文、评价卡、定价开关、博客、联系与订阅，一页走完。',
    en: 'A classic startup site on one page: an orb-decorated hero, six features, a product video block, alternating explainers, review cards, a pricing switch, blog cards, contact and newsletter.',
  },
  kind: 'template',
  category: 'landing',
  tags: ['startup', 'landing', 'fintech', 'pricing', 'blog', 'contact', 'light'],
  runtime: ['react', 'motion', 'css', 'svg'],
  entry: { file: 'tidepool-startup-landing.tsx', export: 'TidepoolStartupLanding' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'light' },
  files: [
    { path: 'tidepool-startup-landing.tsx', role: 'component' },
    { path: 'sections.tsx', role: 'component' },
    { path: 'mockups.tsx', role: 'component' },
    { path: 'parts.tsx', role: 'lib' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    { key: 'brandName', type: 'text', label: { 'zh-CN': '品牌名', en: 'Brand name' }, default: 'Tidepool', maxLength: 18, group: 'brand' },
    { key: 'accent', type: 'color', label: { 'zh-CN': '主色', en: 'Accent color' }, default: '#4a6cf7', group: 'brand' },
    {
      key: 'fontPair',
      type: 'select',
      label: { 'zh-CN': '字体搭配', en: 'Font pairing' },
      default: 'bricolage',
      options: [
        { value: 'bricolage', label: { 'zh-CN': 'Bricolage Grotesque + Manrope（有个性）', en: 'Bricolage Grotesque + Manrope, characterful' } },
        { value: 'inter', label: { 'zh-CN': 'Inter Tight + IBM Plex Sans（稳重）', en: 'Inter Tight + IBM Plex Sans, steady' } },
        { value: 'outfit', label: { 'zh-CN': 'Outfit + Manrope（几何）', en: 'Outfit + Manrope, geometric' } },
        { value: 'serif', label: { 'zh-CN': 'DM Serif Display + IBM Plex Sans（信赖）', en: 'DM Serif Display + IBM Plex Sans, trustworthy' } },
      ],
      group: 'brand',
    },
    { key: 'radius', type: 'number', label: { 'zh-CN': '圆角', en: 'Corner radius' }, default: 10, min: 2, max: 20, step: 1, unit: 'px', safe: [4, 16], group: 'look' },
    { key: 'dark', type: 'boolean', label: { 'zh-CN': '深色模式', en: 'Dark mode' }, default: false, group: 'look' },
    {
      key: 'headline',
      type: 'text',
      label: { 'zh-CN': '首屏标题', en: 'Hero headline' },
      hint: { 'zh-CN': '最好 60 字符以内', en: 'Best under 60 characters' },
      default: 'Reconcile every payout without opening a spreadsheet',
      maxLength: 90,
      group: 'copy',
    },
    {
      key: 'subhead',
      type: 'text',
      label: { 'zh-CN': '首屏副标题', en: 'Hero sub-headline' },
      default: 'Match bank deposits to marketplace orders, split what each seller is owed and close the month in an afternoon.',
      maxLength: 200,
      group: 'copy',
    },
  ],
  presets: [
    { id: 'harbor-blue', name: { 'zh-CN': '港蓝', en: 'Harbor blue' }, values: { accent: '#4a6cf7', fontPair: 'bricolage', radius: 10, dark: false } },
    {
      id: 'evergreen',
      name: { 'zh-CN': '常青', en: 'Evergreen' },
      values: { accent: '#15803d', fontPair: 'serif', radius: 6, dark: false, brandName: 'Evergreen' },
    },
    { id: 'signal', name: { 'zh-CN': '信号', en: 'Signal' }, values: { accent: '#e11d48', fontPair: 'outfit', radius: 16, dark: false, brandName: 'Signal' } },
    { id: 'after-hours', name: { 'zh-CN': '打烊后', en: 'After hours' }, values: { accent: '#818cf8', fontPair: 'inter', radius: 8, dark: true, brandName: 'Afterglow' } },
  ],
  dependencies: ['motion/react', '@motif/runtime'],
  fonts: ['Bricolage Grotesque Variable', 'Manrope Variable', 'Inter Tight Variable', 'IBM Plex Sans Variable', 'Outfit Variable', 'DM Serif Display', 'IBM Plex Mono'],
  guidance: {
    use: [
      'A conventional multi-section startup site for a B2B product: nav, hero, logos, features, video block, two explainers, testimonials, pricing, blog, contact and newsletter, footer.',
      'Good for early-stage companies who need every standard section on one page. Replace the dashboard, matching and ledger mockups with UI from your own product.',
    ],
    rules: [
      'Keep the classic order and rhythm: white sections alternate with a faint tint of the accent color (var(--tint)). Do not add more background colors.',
      'The accent is the only saturated color. Use it for primary buttons, the icon squares, active nav and the popular pricing ring; keep the rest neutral.',
      'Feature icons live in soft accent squares that fill on hover. Keep them to one icon per feature and one sentence of copy.',
      'Pricing is flat and honest: three plans, a monthly/yearly switch, greyed-out lines for what a plan lacks. No "contact us" tier hidden behind fake prices.',
      'Copy is concrete: real-sounding customer roles, numbers with units and a clear job for the product. No lorem ipsum, no "unlock" or "supercharge".',
      'No photos, avatars or logos of real people or companies: gradient initials, invented SVG wordmarks and JSX mockups only.',
    ],
  },
  perf: { webgl: false, maxDpr: 2 },
  a11y: { reducedMotion: 'static' },
  capture: { scroll: true, posterTime: 0.5, loop: 8 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'startup-nextjs',
      repo: 'NextJSTemplates/startup-nextjs',
      sha: 'e730b6a99c77b96c835f11347231faa4f4e9f767',
      paths: [
        'src/app/page.tsx',
        'src/components/Header/index.tsx',
        'src/components/Hero/index.tsx',
        'src/components/Brands/index.tsx',
        'src/components/Features/index.tsx',
        'src/components/Video/index.tsx',
        'src/components/About/AboutSectionOne.tsx',
        'src/components/Testimonials/index.tsx',
        'src/components/Pricing/index.tsx',
        'src/components/Blog/index.tsx',
        'src/components/Contact/index.tsx',
        'src/components/Footer/index.tsx',
      ],
      spdx: 'MIT',
      copyright: ['Copyright (c) 2023 Next.js Templates'],
    },
    modifications: [
      'Rewrote the page for React 19 and Tailwind v4 without Next.js: no next/image, next/link or next-themes; icons are inline SVG and motion comes from motion/react.',
      'All images (hero, video poster, about illustrations, blog covers, avatars, brand logos) were replaced with JSX and SVG mockups, gradient covers, gradient initials and invented wordmarks.',
      'Copy, pricing and blog posts are new; the section order, decorative orbs, six-up features, video block, alternating explainers, pricing switch and blog cards follow the upstream layout.',
      'Theming (brand, accent, fonts, radius, dark mode) is driven by props through CSS variables; layout uses container queries instead of viewport breakpoints.',
    ],
    assets: [],
  },
})
