import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'fluted-glass',
  status: 'published',
  title: { 'zh-CN': '凹槽玻璃', en: 'Fluted Glass' },
  summary: {
    'zh-CN': '隔着一块凹槽玻璃看画面：后面的景色被切成一条条折射，带着细细的高光和阴影，画面在玻璃后面缓慢地左右移动。景色可以是日落、色团或一行大字，都在 Canvas 上现画；凹槽可以换成波浪、锯齿或不规则条纹。',
    en: 'A scene seen through reeded glass: it is sliced into strips of refraction with fine highlights and shadows, and drifts slowly from side to side behind the glass. The scene is a sunset, colour blooms or a big word, all drawn on a canvas at runtime; the reeds can be waves, zigzags or irregular lines.',
  },
  kind: 'effect',
  category: 'shader',
  tags: ['glass', 'fluted', 'reeded', 'refraction', 'background', 'webgl', 'shader', 'paper'],
  runtime: ['react', 'webgl2', 'canvas2d'],
  entry: { file: 'fluted-glass.tsx', export: 'FlutedGlassPanel' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'fluted-glass.tsx', role: 'component' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    {
      key: 'scene',
      type: 'select',
      group: 'content',
      label: { 'zh-CN': '景色', en: 'Scene' },
      default: 'sunset',
      options: [
        { value: 'sunset', label: { 'zh-CN': '日落', en: 'Sunset' } },
        { value: 'bloom', label: { 'zh-CN': '色团', en: 'Bloom' } },
        { value: 'type', label: { 'zh-CN': '大字', en: 'Type' } },
      ],
    },
    { key: 'text', type: 'text', group: 'content', label: { 'zh-CN': '文字', en: 'Text' }, hint: { 'zh-CN': '景色选「大字」时使用', en: 'Used when the scene is Type' }, default: 'Reeded', maxLength: 10 },
    {
      key: 'shape',
      type: 'select',
      group: 'shape',
      label: { 'zh-CN': '凹槽', en: 'Reeds' },
      default: 'lines',
      options: [
        { value: 'lines', label: { 'zh-CN': '直条', en: 'Lines' } },
        { value: 'linesIrregular', label: { 'zh-CN': '不规则条', en: 'Irregular lines' } },
        { value: 'wave', label: { 'zh-CN': '波浪', en: 'Wave' } },
        { value: 'zigzag', label: { 'zh-CN': '锯齿', en: 'Zigzag' } },
        { value: 'pattern', label: { 'zh-CN': '格纹', en: 'Pattern' } },
      ],
    },
    {
      key: 'distortionShape',
      type: 'select',
      group: 'shape',
      label: { 'zh-CN': '截面', en: 'Profile' },
      hint: { 'zh-CN': '每条凹槽的横截面形状，决定折射的样子', en: 'The cross-section of each reed, which sets how it refracts' },
      default: 'prism',
      options: [
        { value: 'prism', label: { 'zh-CN': '棱柱', en: 'Prism' } },
        { value: 'lens', label: { 'zh-CN': '透镜', en: 'Lens' } },
        { value: 'contour', label: { 'zh-CN': '轮廓', en: 'Contour' } },
        { value: 'cascade', label: { 'zh-CN': '阶梯', en: 'Cascade' } },
        { value: 'flat', label: { 'zh-CN': '平面', en: 'Flat' } },
      ],
    },
    { key: 'size', type: 'number', group: 'shape', label: { 'zh-CN': '凹槽宽度', en: 'Reed width' }, default: 0.5, min: 0.1, max: 1, step: 0.01, safe: [0.25, 0.9] },
    { key: 'distortion', type: 'number', group: 'shape', label: { 'zh-CN': '折射', en: 'Refraction' }, default: 0.5, min: 0, max: 1, step: 0.01, safe: [0.2, 0.9] },
    { key: 'angle', type: 'number', group: 'shape', label: { 'zh-CN': '角度', en: 'Angle' }, default: 0, min: 0, max: 180, step: 1, unit: 'deg' },
    { key: 'blur', type: 'number', group: 'shape', label: { 'zh-CN': '磨砂', en: 'Frost' }, default: 0, min: 0, max: 1, step: 0.01, safe: [0, 0.5] },
    { key: 'edges', type: 'number', group: 'shape', label: { 'zh-CN': '边缘', en: 'Edges' }, default: 0.25, min: 0, max: 1, step: 0.01 },
    { key: 'shadows', type: 'number', group: 'shape', label: { 'zh-CN': '阴影', en: 'Shadows' }, default: 0.25, min: 0, max: 1, step: 0.01, safe: [0, 0.6] },
    { key: 'highlights', type: 'number', group: 'shape', label: { 'zh-CN': '高光', en: 'Highlights' }, default: 0.1, min: 0, max: 1, step: 0.01, safe: [0, 0.5] },
    { key: 'drift', type: 'number', group: 'motion', label: { 'zh-CN': '移动幅度', en: 'Drift' }, hint: { 'zh-CN': '画面在玻璃后左右移动的幅度，0 为静止', en: 'How far the scene drifts behind the glass; 0 keeps it still' }, default: 0.08, min: 0, max: 0.2, step: 0.01, safe: [0.03, 0.14] },
  ],
  presets: [
    { id: 'reeded', name: { 'zh-CN': '棱纹', en: 'Reeded' }, values: {} },
    { id: 'waves', name: { 'zh-CN': '波纹', en: 'Waves' }, values: { scene: 'bloom', shape: 'wave', distortionShape: 'contour', size: 0.9, blur: 0.1, edges: 0.5, shadows: 0 } },
    { id: 'folds', name: { 'zh-CN': '褶皱', en: 'Folds' }, values: { scene: 'type', shape: 'lines', distortionShape: 'cascade', size: 0.4, distortion: 0.75, blur: 0.25, edges: 0.5, shadows: 0.4, highlights: 0 } },
    { id: 'frosted', name: { 'zh-CN': '磨砂', en: 'Frosted' }, values: { scene: 'bloom', shape: 'linesIrregular', distortionShape: 'lens', size: 0.7, angle: 30, blur: 0.45, highlights: 0.2 } },
  ],
  dependencies: ['@motif/runtime', '@paper-design/shaders-react'],
  fonts: ['Instrument Serif'],
  perf: { webgl: true, maxDpr: 2 },
  a11y: { reducedMotion: 'static' },
  guidance: {
    use: ['A hero or section background with an architectural, editorial feel; also a frosted panel behind a short headline.'],
    rules: [
      'Use a scene with large, simple shapes and strong colour; fine detail turns to noise behind the reeds.',
      'Put readable text above the glass, never inside the scene image: the refraction slices it.',
      'Keep the drift small (under about 0.14) so the motion reads as parallax rather than a slideshow.',
    ],
  },
  capture: { posterTime: 6, loop: 12 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'paper-shaders',
      repo: 'paper-design/shaders',
      sha: '43cd68db79fa0b1759f72ffc941b3238e2a3954c',
      paths: ['packages/shaders-react/src/shaders/fluted-glass.tsx', 'docs/src/shader-defs/fluted-glass-def.ts'],
      spdx: 'Apache-2.0',
      copyright: ['Paper Shaders (https://shaders.paper.design)'],
    },
    modifications: [
      'The scene behind the glass (sunset, colour bloom or a big word) is drawn on a canvas at runtime, so the item needs no image assets.',
      'The scene drifts slowly behind the glass (the upstream shader is static); the image is passed as an element so the per-frame offset does not decode it again.',
      'Parameter ranges adapted from the Paper docs; Reeded follows the upstream default, Waves and Folds the upstream presets, Frosted is Motif’s.',
      'Stays still when the user prefers reduced motion.',
    ],
    assets: [],
  },
})
