import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'dot-orbit',
  status: 'published',
  title: { "zh-CN": '点阵轨道', en: 'Dot Orbit' },
  summary: {
    "zh-CN": '规整的点阵里，每个点都绕着自己的小轨道公转，颜色逐层渐变。适合做有节奏感的科技背景。',
    en: 'In a tidy grid, every dot orbits its own tiny path while colors step through the palette. A rhythmic backdrop with a technical feel.',
  },
  category: 'background',
  tags: ['dots', 'grid', 'orbit', 'pattern', 'shader', 'webgl'],
  runtime: ['react', 'webgl2'],
  entry: { file: 'dot-orbit.tsx', export: 'DotOrbitBackground' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'dot-orbit.tsx', role: 'component' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    {
      key: 'colors',
      type: 'palette',
      label: { "zh-CN": '颜色', en: 'Colors' },
      default: ['#ffc96b', '#ff6200', '#ff2f00', '#421100', '#1a0000'],
      minItems: 1,
      maxItems: 10,
    },
    { key: 'colorBack', type: 'color', label: { "zh-CN": '底色', en: 'Background' }, default: '#000000' },
    {
      key: 'size',
      type: 'number',
      label: { "zh-CN": '点的大小', en: 'Dot size' },
      default: 1,
      min: 0.1,
      max: 1,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'sizeRange',
      type: 'number',
      label: { "zh-CN": '大小差异', en: 'Size variation' },
      default: 0,
      min: 0,
      max: 1,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'spreading',
      type: 'number',
      label: { "zh-CN": '轨道半径', en: 'Orbit spread' },
      default: 1,
      min: 0.1,
      max: 1,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'stepsPerColor',
      type: 'number',
      label: { "zh-CN": '颜色层数', en: 'Steps per color' },
      default: 4,
      min: 1,
      max: 4,
      step: 1,
      group: 'look',
    },
    {
      key: 'speed',
      type: 'number',
      label: { "zh-CN": '速度', en: 'Speed' },
      default: 1.5,
      min: 0,
      max: 6,
      step: 0.01,
      safe: [0.1, 3],
      unit: 'x',
      group: 'motion',
    },
    {
      key: 'scale',
      type: 'number',
      label: { "zh-CN": '缩放', en: 'Scale' },
      default: 1,
      min: 0.3,
      max: 3,
      step: 0.01,
      safe: [0.3, 2],
      unit: 'x',
      group: 'layout',
    },
  ],
  presets: [
    {
      id: 'ember',
      name: { "zh-CN": '余烬', en: 'Ember' },
      values: {
        colors: ['#ffc96b', '#ff6200', '#ff2f00', '#421100', '#1a0000'],
        colorBack: '#000000',
        size: 1,
        sizeRange: 0,
        spreading: 1,
        stepsPerColor: 4,
        speed: 1.5,
        scale: 1,
      },
    },
    {
      id: 'shine',
      name: { "zh-CN": '闪耀', en: 'Shine' },
      values: {
        colors: ['#ffffff', '#006aff', '#fff675'],
        colorBack: '#000000',
        size: 0.3,
        sizeRange: 0.2,
        spreading: 1,
        stepsPerColor: 4,
        speed: 0.4,
        scale: 0.4,
      },
    },
    {
      id: 'bubbles',
      name: { "zh-CN": '气泡', en: 'Bubbles' },
      values: {
        colors: ['#d0d2d5'],
        colorBack: '#989ca4',
        size: 0.9,
        sizeRange: 0.7,
        spreading: 1,
        stepsPerColor: 2,
        speed: 0.4,
        scale: 1.64,
      },
    },
    {
      id: 'trip',
      name: { "zh-CN": '迷幻', en: 'Trip' },
      values: {
        colors: ['#000000'],
        colorBack: '#ffe500',
        size: 0.65,
        sizeRange: 0,
        spreading: 0.3,
        stepsPerColor: 2,
        speed: 4,
        scale: 0.5,
      },
    },
  ],
  dependencies: ['@paper-design/shaders-react', '@motif/runtime'],
  perf: { webgl: true, maxDpr: 1.5 },
  a11y: { reducedMotion: 'static' },
  capture: { posterTime: 2 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'paper-shaders',
      repo: 'paper-design/shaders',
      sha: '43cd68db79fa0b1759f72ffc941b3238e2a3954c',
      paths: ['packages/shaders-react/src/shaders/dot-orbit.tsx', 'docs/src/shader-defs/dot-orbit-def.ts'],
      spdx: 'Apache-2.0',
      copyright: ['Paper Shaders (https://shaders.paper.design)'],
    },
    modifications: ['Wrapped the Paper DotOrbit component as a full-bleed background that can hold children.', 'Parameter ranges adapted from the Paper docs; Ember (default), Shine, Bubbles and Trip (upstream Hallucinatory, speed lowered) follow the upstream presets.', 'Renders a static frame when the user prefers reduced motion.'],
    assets: [],
  },
})
