import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'morphing-dialog',
  status: 'published',
  title: { 'zh-CN': '形变对话框', en: 'Morphing Dialog' },
  summary: {
    'zh-CN': '点击卡片，它顺着弹簧曲线展开成对话框，标题和封面一路跟随，背景同步虚化；再点一下原路收回。适合案例列表、商品详情和预览。',
    en: 'Tap a card and it springs open into a dialog, title and cover riding along while the backdrop blurs; close it and it folds back in place. For case-study lists, product details and previews.',
  },
  kind: 'component',
  category: 'dialog',
  tags: ['dialog', 'modal', 'shared layout', 'morph', 'spring', 'expand', 'card'],
  runtime: ['react', 'motion'],
  entry: { file: 'morphing-dialog.tsx', export: 'MorphingDialog' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'morphing-dialog.tsx', role: 'component' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    {
      key: 'spring',
      type: 'spring',
      label: { 'zh-CN': '展开弹簧', en: 'Expand spring' },
      hint: { 'zh-CN': '时长越短越利落，弹性越大越有回弹', en: 'Shorter is crisper, more bounce overshoots' },
      default: { visualDuration: 0.5, bounce: 0.15 },
      group: 'motion',
    },
    {
      key: 'radius',
      type: 'number',
      label: { 'zh-CN': '对话框圆角', en: 'Dialog radius' },
      default: 24,
      min: 4,
      max: 40,
      step: 1,
      unit: 'px',
      safe: [12, 32],
      group: 'look',
    },
    {
      key: 'triggerRadius',
      type: 'number',
      label: { 'zh-CN': '触发器圆角', en: 'Trigger radius' },
      default: 18,
      min: 4,
      max: 40,
      step: 1,
      unit: 'px',
      safe: [8, 28],
      group: 'look',
    },
    {
      key: 'backdropOpacity',
      type: 'number',
      label: { 'zh-CN': '遮罩深度', en: 'Backdrop dimming' },
      default: 0.5,
      min: 0.1,
      max: 0.85,
      step: 0.01,
      safe: [0.3, 0.7],
      group: 'look',
    },
    {
      key: 'backdropBlur',
      type: 'number',
      label: { 'zh-CN': '背景虚化', en: 'Backdrop blur' },
      default: 6,
      min: 0,
      max: 20,
      step: 1,
      unit: 'px',
      safe: [2, 12],
      group: 'look',
    },
    {
      key: 'closeOnOutsideClick',
      type: 'boolean',
      label: { 'zh-CN': '点击遮罩关闭', en: 'Close on backdrop click' },
      default: true,
      group: 'interaction',
    },
  ],
  presets: [
    { id: 'settle', name: { 'zh-CN': '落定', en: 'Settle' }, values: { spring: { visualDuration: 0.5, bounce: 0.15 }, radius: 24, triggerRadius: 18, backdropOpacity: 0.5, backdropBlur: 6 } },
    { id: 'snappy', name: { 'zh-CN': '利落', en: 'Snappy' }, values: { spring: { visualDuration: 0.32, bounce: 0 }, radius: 16, triggerRadius: 12, backdropOpacity: 0.6, backdropBlur: 2 } },
    { id: 'jelly', name: { 'zh-CN': '果冻', en: 'Jelly' }, values: { spring: { visualDuration: 0.65, bounce: 0.4 }, radius: 32, triggerRadius: 26, backdropOpacity: 0.4, backdropBlur: 10 } },
    { id: 'frosted', name: { 'zh-CN': '磨砂', en: 'Frosted' }, values: { spring: { visualDuration: 0.6, bounce: 0.05 }, radius: 28, triggerRadius: 20, backdropOpacity: 0.25, backdropBlur: 16 } },
  ],
  dependencies: ['motion/react', '@motif/runtime'],
  perf: { webgl: false, maxDpr: 2 },
  a11y: { reducedMotion: 'static' },
  capture: { zoom: 1.2, posterTime: 3.2, loop: 8 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'motion-primitives',
      repo: 'ibelick/motion-primitives',
      sha: '120f64f6ca60348e251f929e9c81f11ccbe45eda',
      paths: ['components/core/morphing-dialog.tsx'],
      spdx: 'MIT',
      copyright: ['Copyright (c) 2024 ibelick'],
    },
    modifications: [
      'framer-motion imports moved to motion/react, cn comes from motif-runtime, and lucide-react was replaced by an inline SVG close icon.',
      'The @/hooks/useClickOutside hook was replaced by a click handler on the backdrop wrapper, and body scroll locking now restores the previous overflow value.',
      'Added controlled open / onOpenChange props; focus moves into the dialog and back to the trigger only when the user opened or closed it, and the trigger no longer steals focus on mount.',
      'The spring, radii and backdrop dimming / blur became props; the transition prop was replaced by the spring param.',
      'MorphingDialogImage also accepts children (for gradient or custom covers); the title and description get the ids the dialog labels itself with.',
      'Added reduced-motion handling (upstream has none): MotionConfig reducedMotion="user" turns the layout morph into an instant swap with a short fade.',
      'Defaults moved into the generated defaults region.',
    ],
    assets: [],
  },
})
