import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'stats-metric-tiles',
  status: 'published',
  title: { 'zh-CN': '数据指标磁贴', en: 'Metric Tiles' },
  summary: {
    'zh-CN': '四个大数字从零滚动到目标值，每个下面一条自己描出来的折线。可以是带边框的磁贴，也可以是只有分隔线的一行。数字会定时重播。',
    en: 'Four big numbers counting up from zero, each with a sparkline that draws itself underneath. Bordered tiles or a single row split by hairlines, replaying on a timer.',
  },
  kind: 'section',
  category: 'stats',
  tags: ['stats', 'metrics', 'numbers', 'counter', 'sparkline', 'social proof'],
  runtime: ['react', 'svg'],
  entry: { file: 'stats-metric-tiles.tsx', export: 'StatsMetricTiles' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'stats-metric-tiles.tsx', role: 'component' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    { key: 'eyebrow', type: 'text', label: { 'zh-CN': '小标题', en: 'Eyebrow' }, default: 'By the numbers', maxLength: 28, group: 'content' },
    { key: 'heading', type: 'text', label: { 'zh-CN': '标题', en: 'Heading' }, default: 'Boring infrastructure, measured in public', maxLength: 64, group: 'content' },
    {
      key: 'subline',
      type: 'text',
      label: { 'zh-CN': '副标题', en: 'Subline' },
      default: 'The four numbers we watch every morning, and the ones we would like you to hold us to.',
      maxLength: 130,
      group: 'content',
    },
    { key: 'accent', type: 'color', label: { 'zh-CN': '主色', en: 'Accent color' }, default: '#2dd4bf', group: 'look' },
    {
      key: 'tone',
      type: 'select',
      label: { 'zh-CN': '明暗', en: 'Tone' },
      default: 'dark',
      options: [
        { value: 'dark', label: { 'zh-CN': '深色', en: 'Dark' } },
        { value: 'light', label: { 'zh-CN': '浅色', en: 'Light' } },
      ],
      group: 'look',
    },
    {
      key: 'font',
      type: 'select',
      label: { 'zh-CN': '数字字体', en: 'Number font' },
      default: 'geist',
      options: [
        { value: 'geist', label: { 'zh-CN': 'Geist 无衬线', en: 'Geist sans' } },
        { value: 'grotesk', label: { 'zh-CN': 'Space Grotesk', en: 'Space Grotesk' } },
        { value: 'serif', label: { 'zh-CN': 'Instrument 衬线', en: 'Instrument serif' } },
      ],
      group: 'look',
    },
    { key: 'radius', type: 'number', label: { 'zh-CN': '磁贴圆角', en: 'Tile radius' }, default: 20, min: 0, max: 32, step: 1, unit: 'px', safe: [6, 28], group: 'look' },
    {
      key: 'layout',
      type: 'select',
      label: { 'zh-CN': '排布', en: 'Layout' },
      default: 'tiles',
      options: [
        { value: 'tiles', label: { 'zh-CN': '边框磁贴', en: 'Bordered tiles' } },
        { value: 'lines', label: { 'zh-CN': '分隔线一行', en: 'Hairline row' } },
      ],
      group: 'layout',
    },
    { key: 'duration', type: 'number', label: { 'zh-CN': '滚动用时', en: 'Count-up time' }, default: 2, min: 0.8, max: 4, step: 0.1, unit: 's', safe: [1.2, 3], group: 'motion' },
    {
      key: 'replay',
      type: 'number',
      label: { 'zh-CN': '重播间隔', en: 'Replay every' },
      hint: { 'zh-CN': '0 表示只播一次', en: '0 plays once' },
      default: 8,
      min: 0,
      max: 20,
      step: 1,
      unit: 's',
      group: 'motion',
    },
  ],
  presets: [
    { id: 'teal-signal', name: { 'zh-CN': '青绿信号', en: 'Teal Signal' }, values: {} },
    { id: 'amber-line', name: { 'zh-CN': '琥珀线', en: 'Amber Line' }, values: { accent: '#fbbf24', layout: 'lines', font: 'grotesk' } },
    { id: 'annual-report', name: { 'zh-CN': '年报', en: 'Annual Report' }, values: { tone: 'light', accent: '#c2410c', font: 'serif', radius: 8, replay: 0 } },
  ],
  dependencies: ['@motif/runtime'],
  fonts: ['Geist Variable', 'Space Grotesk Variable', 'Instrument Serif'],
  guidance: {
    rules: [
      'Show four numbers, each with a label and one sentence of context. Numbers must be real or clearly illustrative; never inflate them.',
      'Only the unit suffix and the sparkline take the accent color; digits stay in the foreground color and use tabular figures so they do not jitter.',
      'Count-up runs once per visit; replaying on a timer is for previews only, set replay to 0 in production.',
    ],
  },
  perf: { webgl: false, maxDpr: 2 },
  a11y: { reducedMotion: 'static' },
  capture: { posterTime: 2.8, loop: 8 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'magicui',
      repo: 'magicuidesign/magicui',
      sha: 'd7207e5692d14c00dceafa8488d6d01f197fa0e4',
      paths: ['apps/www/registry/magicui/number-ticker.tsx'],
      spdx: 'MIT',
      copyright: ['Copyright (c) Magic UI'],
    },
    modifications: [
      'Kept the count-up-to-value idea of NumberTicker; values are computed from the Motif frame loop time with an ease-out curve and written straight to the DOM instead of using a motion spring and useInView.',
      'Composed four tiles with a self-drawing sparkline each, a bordered and a hairline layout, and a timed replay; all figures and copy are invented.',
      'Under reduced motion the numbers show their final values.',
    ],
    assets: [],
  },
})
