import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'spiral',
  status: 'published',
  title: { "zh-CN": '螺线', en: 'Spiral' },
  summary: {
    "zh-CN": '一条不断旋转的螺线铺满画面，线宽可以渐细，边缘可以带噪点。适合做催眠感或极简风的背景。',
    en: 'A single turning spiral fills the frame, with strokes that taper and edges that can turn grainy. For hypnotic or minimal backdrops.',
  },
  category: 'shader',
  tags: ['spiral', 'lines', 'minimal', 'shader', 'webgl', 'pattern'],
  runtime: ['react', 'webgl2'],
  entry: { file: 'spiral.tsx', export: 'SpiralBackground' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'spiral.tsx', role: 'component' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    { key: 'colorBack', type: 'color', label: { "zh-CN": '底色', en: 'Background' }, default: '#001429' },
    { key: 'colorFront', type: 'color', label: { "zh-CN": '线条色', en: 'Stroke color' }, default: '#79d1ff' },
    {
      key: 'density',
      type: 'number',
      label: { "zh-CN": '密度', en: 'Density' },
      default: 1,
      min: 0.1,
      max: 1,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'strokeWidth',
      type: 'number',
      label: { "zh-CN": '线宽', en: 'Stroke width' },
      default: 0.5,
      min: 0.1,
      max: 0.9,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'strokeTaper',
      type: 'number',
      label: { "zh-CN": '渐细', en: 'Taper' },
      default: 0,
      min: 0,
      max: 1,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'softness',
      type: 'number',
      label: { "zh-CN": '柔和度', en: 'Softness' },
      default: 0,
      min: 0,
      max: 1,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'noise',
      type: 'number',
      label: { "zh-CN": '噪点', en: 'Noise' },
      default: 0,
      min: 0,
      max: 1,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'noiseFrequency',
      type: 'number',
      label: { "zh-CN": '噪点频率', en: 'Noise frequency' },
      default: 0.3,
      min: 0,
      max: 1,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'speed',
      type: 'number',
      label: { "zh-CN": '速度', en: 'Speed' },
      default: 1,
      min: 0,
      max: 4,
      step: 0.01,
      safe: [0.1, 2.5],
      unit: 'x',
      group: 'motion',
    },
    {
      key: 'scale',
      type: 'number',
      label: { "zh-CN": '缩放', en: 'Scale' },
      default: 1,
      min: 0.3,
      max: 3,
      step: 0.01,
      safe: [0.4, 2],
      unit: 'x',
      group: 'layout',
    },
  ],
  presets: [
    {
      id: 'blueprint',
      name: { "zh-CN": '蓝图', en: 'Blueprint' },
      values: {
        colorBack: '#001429',
        colorFront: '#79d1ff',
        density: 1,
        strokeWidth: 0.5,
        strokeTaper: 0,
        softness: 0,
        noise: 0,
        noiseFrequency: 0.3,
        speed: 1,
        scale: 1,
      },
    },
    {
      id: 'droplet',
      name: { "zh-CN": '水滴', en: 'Droplet' },
      values: {
        colorBack: '#effafe',
        colorFront: '#bf40a0',
        density: 0.9,
        strokeWidth: 0.75,
        strokeTaper: 0.18,
        softness: 0.02,
        noise: 0.74,
        noiseFrequency: 0.33,
        speed: 1,
        scale: 1,
      },
    },
    {
      id: 'jungle',
      name: { "zh-CN": '丛林', en: 'Jungle' },
      values: {
        colorBack: '#a0ef2a',
        colorFront: '#288b18',
        density: 0.5,
        strokeWidth: 0.5,
        strokeTaper: 0,
        softness: 0,
        noise: 1,
        noiseFrequency: 0.25,
        speed: 0.75,
        scale: 1.3,
      },
    },
    {
      id: 'tide',
      name: { "zh-CN": '潮汐', en: 'Tide' },
      values: {
        colorBack: '#b3e6d9',
        colorFront: '#1a2b4d',
        density: 0.2,
        strokeWidth: 0.5,
        strokeTaper: 0,
        softness: 0.5,
        noise: 0,
        noiseFrequency: 0.3,
        speed: 1,
        scale: 0.45,
      },
    },
  ],
  dependencies: ['@paper-design/shaders-react', '@motif/runtime'],
  perf: { webgl: true, maxDpr: 1.5 },
  a11y: { reducedMotion: 'static' },
  capture: { posterTime: 2 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'paper-shaders',
      repo: 'paper-design/shaders',
      sha: '43cd68db79fa0b1759f72ffc941b3238e2a3954c',
      paths: ['packages/shaders-react/src/shaders/spiral.tsx', 'docs/src/shader-defs/spiral-def.ts'],
      spdx: 'Apache-2.0',
      copyright: ['Paper Shaders (https://shaders.paper.design)'],
    },
    modifications: ['Wrapped the Paper Spiral component as a full-bleed background that can hold children (distortion and stroke cap are fixed at 0).', 'Parameter ranges adapted from the Paper docs; Blueprint (default), Droplet (round stroke cap dropped), Jungle and Tide (upstream Swirl) follow the upstream presets.', 'Renders a static frame when the user prefers reduced motion.'],
    assets: [],
  },
})
