import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'smoke-ring',
  status: 'published',
  title: { "zh-CN": '烟环', en: 'Smoke Ring' },
  summary: {
    "zh-CN": '一圈缓缓翻滚的烟雾光环，可以调成日冕、云环或一条细亮线。适合做发布页的主视觉。',
    en: 'A slowly churning ring of smoke that can be tuned into a solar corona, a cloud halo or a thin glowing line. A centerpiece for launch pages.',
  },
  kind: 'effect',
  category: 'shader',
  tags: ['ring', 'smoke', 'glow', 'shader', 'webgl', 'hero'],
  runtime: ['react', 'webgl2'],
  entry: { file: 'smoke-ring.tsx', export: 'SmokeRingBackground' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'smoke-ring.tsx', role: 'component' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    {
      key: 'colors',
      type: 'palette',
      label: { "zh-CN": '颜色', en: 'Colors' },
      hint: { "zh-CN": '烟雾由内向外依次经过这些颜色', en: 'Smoke moves through these colors' },
      default: ['#ffffff'],
      minItems: 1,
      maxItems: 10,
    },
    { key: 'colorBack', type: 'color', label: { "zh-CN": '底色', en: 'Background' }, default: '#000000' },
    {
      key: 'radius',
      type: 'number',
      label: { "zh-CN": '半径', en: 'Radius' },
      default: 0.25,
      min: 0.1,
      max: 0.6,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'thickness',
      type: 'number',
      label: { "zh-CN": '厚度', en: 'Thickness' },
      default: 0.65,
      min: 0.01,
      max: 1,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'innerShape',
      type: 'number',
      label: { "zh-CN": '内圈形状', en: 'Inner shape' },
      hint: { "zh-CN": '内缘的衰减，越大内圈越亮', en: 'Falloff on the inner edge' },
      default: 0.7,
      min: 0,
      max: 4,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'noiseScale',
      type: 'number',
      label: { "zh-CN": '烟雾尺度', en: 'Smoke scale' },
      default: 3,
      min: 0.5,
      max: 5,
      step: 0.01,
      safe: [1, 4],
      group: 'look',
    },
    {
      key: 'noiseIterations',
      type: 'number',
      label: { "zh-CN": '烟雾细节', en: 'Smoke detail' },
      default: 8,
      min: 1,
      max: 8,
      step: 1,
      group: 'look',
    },
    {
      key: 'speed',
      type: 'number',
      label: { "zh-CN": '速度', en: 'Speed' },
      default: 0.5,
      min: 0,
      max: 4,
      step: 0.01,
      safe: [0.1, 2],
      unit: 'x',
      group: 'motion',
    },
    {
      key: 'scale',
      type: 'number',
      label: { "zh-CN": '缩放', en: 'Scale' },
      default: 0.8,
      min: 0.4,
      max: 3,
      step: 0.01,
      safe: [0.5, 2.5],
      unit: 'x',
      group: 'layout',
    },
    {
      key: 'offsetY',
      type: 'number',
      label: { "zh-CN": '垂直偏移', en: 'Vertical offset' },
      default: 0,
      min: -1,
      max: 1,
      step: 0.01,
      group: 'layout',
    },
  ],
  presets: [
    {
      id: 'halo',
      name: { "zh-CN": '光晕', en: 'Halo' },
      values: {
        colors: ['#ffffff'],
        colorBack: '#000000',
        radius: 0.25,
        thickness: 0.65,
        innerShape: 0.7,
        noiseScale: 3,
        noiseIterations: 8,
        speed: 0.5,
        scale: 0.8,
        offsetY: 0,
      },
    },
    {
      id: 'solar',
      name: { "zh-CN": '日冕', en: 'Solar' },
      values: {
        colors: ['#ffffff', '#ffca0a', '#fc6203', '#fc620366'],
        colorBack: '#000000',
        radius: 0.4,
        thickness: 0.8,
        innerShape: 4,
        noiseScale: 2,
        noiseIterations: 3,
        speed: 1,
        scale: 2,
        offsetY: 1,
      },
    },
    {
      id: 'line',
      name: { "zh-CN": '细线', en: 'Thread' },
      values: {
        colors: ['#4540a4', '#1fe8ff'],
        colorBack: '#000000',
        radius: 0.38,
        thickness: 0.01,
        innerShape: 0.88,
        noiseScale: 1.1,
        noiseIterations: 2,
        speed: 2,
        scale: 0.8,
        offsetY: 0,
      },
    },
    {
      id: 'cloud',
      name: { "zh-CN": '云环', en: 'Cloud' },
      values: {
        colors: ['#ffffff'],
        colorBack: '#81adec',
        radius: 0.5,
        thickness: 0.65,
        innerShape: 0.85,
        noiseScale: 3,
        noiseIterations: 8,
        speed: 0.5,
        scale: 2.5,
        offsetY: 0,
      },
    },
    {
      id: 'nebula',
      name: { "zh-CN": '星云', en: 'Nebula' },
      values: {
        colors: ['#ffffff', '#b58cff', '#ff5fa2', '#ff5fa233'],
        colorBack: '#05030f',
        radius: 0.3,
        thickness: 0.7,
        innerShape: 1.6,
        noiseScale: 2.4,
        noiseIterations: 6,
        speed: 0.6,
        scale: 1.1,
        offsetY: 0,
      },
    },
  ],
  dependencies: ['@paper-design/shaders-react', '@motif/runtime'],
  perf: { webgl: true, maxDpr: 1.5 },
  a11y: { reducedMotion: 'static' },
  capture: { posterTime: 2 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'paper-shaders',
      repo: 'paper-design/shaders',
      sha: '43cd68db79fa0b1759f72ffc941b3238e2a3954c',
      paths: ['packages/shaders-react/src/shaders/smoke-ring.tsx', 'docs/src/shader-defs/smoke-ring-def.ts'],
      spdx: 'Apache-2.0',
      copyright: ['Paper Shaders (https://shaders.paper.design)'],
    },
    modifications: ['Wrapped the Paper SmokeRing component as a full-bleed background that can hold children.', 'Parameter ranges adapted from the Paper docs; the Halo (default), Solar, Thread (upstream Line) and Cloud presets follow the upstream presets (Thread’s speed lowered, Cloud’s smoke detail capped at 8); Nebula is Motif’s.', 'Renders a static frame when the user prefers reduced motion.'],
    assets: [],
  },
})
