import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'spotlight',
  status: 'published',
  title: { 'zh-CN': '聚光', en: 'Spotlight' },
  summary: {
    'zh-CN': '一团柔和的光晕跟随指针在卡片上游走，移出时淡去。适合功能卡、定价卡和深色的内容面板。',
    en: 'A soft pool of light trails the pointer across a card and fades when it leaves. Made for feature cards, pricing tiles and dark content panels.',
  },
  kind: 'effect',
  category: 'cursor',
  tags: ['spotlight', 'glow', 'pointer', 'hover', 'card', 'interactive'],
  runtime: ['react', 'motion', 'css'],
  entry: { file: 'spotlight.tsx', export: 'Spotlight' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'spotlight.tsx', role: 'component' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    {
      key: 'size',
      type: 'number',
      label: { 'zh-CN': '光斑大小', en: 'Size' },
      default: 320,
      min: 80,
      max: 700,
      step: 1,
      unit: 'px',
      safe: [180, 480],
      group: 'look',
    },
    { key: 'color', type: 'color', label: { 'zh-CN': '光色', en: 'Color' }, default: '#a5b4fc', group: 'look' },
    {
      key: 'intensity',
      type: 'number',
      label: { 'zh-CN': '亮度', en: 'Intensity' },
      default: 0.42,
      min: 0.05,
      max: 0.8,
      step: 0.01,
      safe: [0.2, 0.6],
      group: 'look',
    },
    {
      key: 'blur',
      type: 'number',
      label: { 'zh-CN': '柔化', en: 'Softness' },
      hint: { 'zh-CN': '光斑边缘的模糊半径', en: 'Blur radius on the edge of the light' },
      default: 24,
      min: 0,
      max: 60,
      step: 1,
      unit: 'px',
      safe: [12, 40],
      group: 'look',
    },
    {
      key: 'spring',
      type: 'spring',
      label: { 'zh-CN': '跟随手感', en: 'Follow' },
      hint: { 'zh-CN': '时长越长，光斑越有拖尾感', en: 'Longer durations make the light trail behind' },
      default: { visualDuration: 0.3, bounce: 0 },
      group: 'motion',
    },
  ],
  presets: [
    { id: 'moonlight', name: { 'zh-CN': '月光', en: 'Moonlight' }, values: { color: '#c7d2fe', size: 360, intensity: 0.4, blur: 28 } },
    { id: 'ember', name: { 'zh-CN': '余烬', en: 'Ember' }, values: { color: '#fb923c', size: 280, intensity: 0.5, blur: 30, spring: { visualDuration: 0.45, bounce: 0 } } },
    { id: 'lagoon', name: { 'zh-CN': '潟湖', en: 'Lagoon' }, values: { color: '#2dd4bf', size: 420, intensity: 0.36, blur: 36, spring: { visualDuration: 0.5, bounce: 0.1 } } },
    { id: 'pinlight', name: { 'zh-CN': '针灯', en: 'Pinlight' }, values: { color: '#ffffff', size: 160, intensity: 0.55, blur: 14, spring: { visualDuration: 0.18, bounce: 0 } } },
  ],
  dependencies: ['motion/react', '@motif/runtime'],
  perf: { webgl: false, maxDpr: 2 },
  a11y: { reducedMotion: 'not-animated' },
  capture: { zoom: 1.4, posterTime: 1.1, loop: 8 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'motion-primitives',
      repo: 'ibelick/motion-primitives',
      sha: '120f64f6ca60348e251f929e9c81f11ccbe45eda',
      paths: ['components/core/spotlight.tsx'],
      spdx: 'MIT',
      copyright: ['Copyright (c) 2024 ibelick'],
    },
    modifications: [
      'framer-motion imports moved to motion/react and cn now comes from motif-runtime; the spring is described with visualDuration and bounce.',
      'Color, intensity and blur are props (upstream hard-codes a zinc gradient and a Tailwind blur), and the glow is positioned with transform instead of left/top.',
      'Listens to pointer events on the parent, shows on pointerenter or the first pointermove, and no longer fades with a class-based transition.',
      'Added reduced-motion handling (upstream has none): the glow jumps to the pointer without easing and fades instantly.',
      'Defaults moved into the generated defaults region.',
    ],
    assets: [],
  },
})
