import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'mobile-app-landing',
  status: 'published',
  title: { 'zh-CN': '手机 App 落地页', en: 'Mobile App Landing' },
  summary: {
    'zh-CN': '深色的手机 App 官网：三台 JSX 画的手机叠在跑道线前，往下是便当格功能、四屏画廊、评分评价、定价与 FAQ。没有商店徽章，也不需要任何截图。',
    en: 'A dark mobile-app site: three phones drawn in JSX float in front of track lines, followed by a bento of features, a four-screen gallery, ratings and reviews, pricing and FAQ. No store badges, no screenshots.',
  },
  kind: 'template',
  category: 'app',
  tags: ['app', 'mobile', 'landing', 'dark', 'phone mockup', 'pricing', 'reviews'],
  runtime: ['react', 'motion', 'css', 'svg'],
  entry: { file: 'mobile-app-landing.tsx', export: 'MobileAppLanding' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'mobile-app-landing.tsx', role: 'component' },
    { path: 'sections.tsx', role: 'component' },
    { path: 'phones.tsx', role: 'component' },
    { path: 'parts.tsx', role: 'lib' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    { key: 'brandName', type: 'text', label: { 'zh-CN': '品牌名', en: 'Brand name' }, default: 'Cadence', maxLength: 16, group: 'brand' },
    { key: 'accent', type: 'color', label: { 'zh-CN': '主色', en: 'Accent color' }, default: '#ff6a3d', group: 'brand' },
    {
      key: 'fontPair',
      type: 'select',
      label: { 'zh-CN': '字体搭配', en: 'Font pairing' },
      default: 'archivo',
      options: [
        { value: 'archivo', label: { 'zh-CN': 'Archivo Black + Inter Tight（运动感）', en: 'Archivo Black + Inter Tight, athletic' } },
        { value: 'grotesk', label: { 'zh-CN': 'Space Grotesk + IBM Plex Sans（数据感）', en: 'Space Grotesk + IBM Plex Sans, data-minded' } },
        { value: 'bricolage', label: { 'zh-CN': 'Bricolage Grotesque + Manrope（友好）', en: 'Bricolage Grotesque + Manrope, friendly' } },
        { value: 'syne', label: { 'zh-CN': 'Syne + Geist（前卫）', en: 'Syne + Geist, avant-garde' } },
      ],
      group: 'brand',
    },
    { key: 'radius', type: 'number', label: { 'zh-CN': '圆角', en: 'Corner radius' }, default: 12, min: 4, max: 20, step: 1, unit: 'px', safe: [8, 16], group: 'look' },
    { key: 'dark', type: 'boolean', label: { 'zh-CN': '深色模式', en: 'Dark mode' }, default: true, group: 'look' },
    {
      key: 'headline',
      type: 'text',
      label: { 'zh-CN': '首屏标题', en: 'Hero headline' },
      hint: { 'zh-CN': '最好 50 字符以内', en: 'Best under 50 characters' },
      default: 'A running plan that changes when you do',
      maxLength: 80,
      group: 'copy',
    },
    {
      key: 'subhead',
      type: 'text',
      label: { 'zh-CN': '首屏副标题', en: 'Hero sub-headline' },
      default: 'Cadence adjusts every session to your sleep, your legs and your calendar, so you can train for a race without a spreadsheet.',
      maxLength: 200,
      group: 'copy',
    },
  ],
  presets: [
    { id: 'ember', name: { 'zh-CN': '余烬', en: 'Ember' }, values: { accent: '#ff6a3d', fontPair: 'archivo', radius: 12, dark: true } },
    {
      id: 'meadow',
      name: { 'zh-CN': '草甸', en: 'Meadow' },
      values: { accent: '#3f9b54', fontPair: 'bricolage', radius: 16, dark: false, brandName: 'Meadow' },
    },
    { id: 'volt', name: { 'zh-CN': '电光', en: 'Volt' }, values: { accent: '#c6f432', fontPair: 'grotesk', radius: 6, dark: true, brandName: 'Voltage' } },
    { id: 'orchid', name: { 'zh-CN': '兰紫', en: 'Orchid' }, values: { accent: '#a855f7', fontPair: 'syne', radius: 14, dark: true, brandName: 'Orchid' } },
  ],
  dependencies: ['motion/react', '@motif/runtime'],
  fonts: ['Archivo Black', 'Inter Tight Variable', 'Space Grotesk Variable', 'IBM Plex Sans Variable', 'Bricolage Grotesque Variable', 'Manrope Variable', 'Syne Variable', 'Geist Variable', 'Geist Mono Variable', 'JetBrains Mono Variable'],
  guidance: {
    use: [
      'A marketing page for a consumer mobile app (fitness, habits, finance, notes). Phone mockups carry the whole story, so the app needs two or three screens worth showing.',
      'Replace the running screens in phones.tsx with your own screens drawn in JSX. Keep each one to a single idea: a headline number, a list or a chart.',
    ],
    rules: [
      'Never add store badges, store logos or fetched store data. Download buttons are ordinary buttons with a generic phone icon and plain text.',
      'Phone screens always use a dark UI regardless of the page mode, so they read as real device screenshots in both light and dark pages. Only the accent color changes.',
      'Keep the section order: header, hero with phones and app info, stats, bento features, screen gallery, ratings and reviews, pricing, FAQ, CTA, footer.',
      'The accent drives primary buttons, progress rings, route lines and the full-bleed CTA block. Everything else is warm neutral.',
      'Reviews are written like real store reviews: a specific title, first-person detail, one or two four-star reviews with honest complaints. Do not use invented celebrity names or real handles.',
      'Copy is short and physical (kilometres, minutes, weeks). Avoid "revolutionary", "unlock" and exclamation marks.',
    ],
  },
  perf: { webgl: false, maxDpr: 2 },
  a11y: { reducedMotion: 'static' },
  capture: { scroll: true, posterTime: 0.5, loop: 8 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'app-landing',
      repo: 'bohd4nx/app-landing',
      sha: '8bd07982803fffc3f247381493de492546287a1f',
      paths: [
        'src/app/page.tsx',
        'src/components/AppHero/index.tsx',
        'src/components/Features/index.tsx',
        'src/components/Screenshots/index.tsx',
        'src/components/Reviews/index.tsx',
        'src/components/Pricing/index.tsx',
        'src/components/FAQ/index.tsx',
        'src/components/Footer/index.tsx',
      ],
      spdx: 'MIT',
      copyright: ['Copyright (c) 2024-2026 Bohdan (https://bohd4n.dev/)'],
    },
    modifications: [
      'Rewrote the page for React 19 and Tailwind v4 without Next.js: no store metadata fetching, next/image or react-icons; icons are inline SVG and motion comes from motion/react.',
      'Removed the store buttons and badges (plain download buttons instead) and replaced the screenshot images with four phone screens built in JSX and SVG.',
      'Added a stats strip and a bento feature grid with small UI illustrations; hero, screenshot gallery, ratings and reviews, pricing tiers, FAQ and footer follow the upstream structure.',
      'Copy, reviews, pricing and FAQ are new; theming (brand, accent, fonts, radius, dark mode) is driven by props through CSS variables and layout uses container queries.',
    ],
    assets: [],
  },
})
