import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'tilt',
  status: 'published',
  title: { 'zh-CN': '3D 倾斜', en: 'Tilt' },
  summary: {
    'zh-CN': '卡片随指针位置在三维空间里微微倾斜，表面带一层跟随的高光，内部元素可以浮出层次。适合专辑、票券、商品和功能卡片。',
    en: 'A card leans toward the pointer in 3D with a soft glare that follows it, and inner elements can float above the surface. Suits album covers, tickets, product and feature cards.',
  },
  kind: 'effect',
  category: 'card',
  tags: ['tilt', '3d', 'perspective', 'card', 'glare', 'hover', 'interactive'],
  runtime: ['react', 'motion', 'css'],
  entry: { file: 'tilt.tsx', export: 'Tilt' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'tilt.tsx', role: 'component' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    {
      key: 'rotationFactor',
      type: 'number',
      label: { 'zh-CN': '倾斜角度', en: 'Max angle' },
      hint: { 'zh-CN': '指针在边缘时的最大倾斜', en: 'Tilt when the pointer reaches the edge' },
      default: 14,
      min: 2,
      max: 30,
      step: 0.5,
      unit: 'deg',
      safe: [6, 20],
      group: 'interaction',
    },
    {
      key: 'perspective',
      type: 'number',
      label: { 'zh-CN': '透视距离', en: 'Perspective' },
      hint: { 'zh-CN': '越小，立体感越夸张', en: 'Smaller values exaggerate the depth' },
      default: 1000,
      min: 400,
      max: 2400,
      step: 10,
      unit: 'px',
      safe: [700, 1600],
      group: 'interaction',
    },
    {
      key: 'reverse',
      type: 'boolean',
      label: { 'zh-CN': '反向倾斜', en: 'Lean away' },
      hint: { 'zh-CN': '开启后卡片会向远离指针的方向倾斜', en: 'Tilt away from the pointer instead of toward it' },
      default: false,
      group: 'interaction',
    },
    {
      key: 'glare',
      type: 'number',
      label: { 'zh-CN': '高光强度', en: 'Glare' },
      default: 0.22,
      min: 0,
      max: 0.6,
      step: 0.01,
      safe: [0.1, 0.35],
      group: 'look',
    },
    {
      key: 'spring',
      type: 'spring',
      label: { 'zh-CN': '回弹', en: 'Spring' },
      hint: { 'zh-CN': '时长越短越跟手', en: 'Shorter feels more responsive' },
      default: { visualDuration: 0.5, bounce: 0.2 },
      group: 'motion',
    },
  ],
  presets: [
    { id: 'showroom', name: { 'zh-CN': '展台', en: 'Showroom' }, values: { rotationFactor: 12, perspective: 1200, glare: 0.25, spring: { visualDuration: 0.6, bounce: 0.15 } } },
    { id: 'holo', name: { 'zh-CN': '镭射', en: 'Holo' }, values: { rotationFactor: 22, perspective: 800, glare: 0.4, spring: { visualDuration: 0.45, bounce: 0.25 } } },
    { id: 'whisper', name: { 'zh-CN': '耳语', en: 'Whisper' }, values: { rotationFactor: 6, perspective: 1600, glare: 0.12, spring: { visualDuration: 0.7, bounce: 0 } } },
    { id: 'mirror', name: { 'zh-CN': '镜面', en: 'Mirror' }, values: { rotationFactor: 16, reverse: true, glare: 0.3, spring: { visualDuration: 0.5, bounce: 0.3 } } },
  ],
  dependencies: ['motion/react', '@motif/runtime'],
  perf: { webgl: false, maxDpr: 2 },
  a11y: { reducedMotion: 'not-animated' },
  capture: { zoom: 1.5, posterTime: 2.6, loop: 8 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'motion-primitives',
      repo: 'ibelick/motion-primitives',
      sha: '120f64f6ca60348e251f929e9c81f11ccbe45eda',
      paths: ['components/core/tilt.tsx'],
      spdx: 'MIT',
      copyright: ['Copyright (c) 2024 ibelick'],
    },
    modifications: [
      'framer-motion imports moved to motion/react; the spring is now described with visualDuration and bounce, and the perspective distance is a prop.',
      'The misspelled isRevese prop is now reverse.',
      'Uses pointer events instead of mouse events, and adds an optional glare layer that follows the pointer.',
      'Added reduced-motion handling (upstream has none): the card stays flat.',
      'Defaults moved into the generated defaults region.',
    ],
    assets: [],
  },
})
