import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'studio-agency-site',
  status: 'published',
  title: { 'zh-CN': '工作室官网', en: 'Studio Agency' },
  summary: {
    'zh-CN': '深色的设计与工程工作室官网：光带描边的产品界面首屏、客户字标、服务便当格、斜切流程带、案例、报价、期刊和常见问题。一页讲完「我们是谁、做过什么、怎么合作」。',
    en: 'A dark design-and-engineering studio site: a hero with a beam-lit product mock, client wordmarks, a services bento, a diagonal process band, case studies, engagement pricing, a journal and an FAQ. Says who you are, what you shipped and how to hire you in one page.',
  },
  kind: 'template',
  category: 'agency',
  tags: ['agency', 'studio', 'dark', 'bento', 'pricing', 'case-studies', 'faq', 'landing'],
  runtime: ['react', 'motion'],
  entry: { file: 'studio-agency-site.tsx', export: 'StudioAgencySite' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'studio-agency-site.tsx', role: 'component' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    { key: 'name', type: 'text', label: { 'zh-CN': '工作室名', en: 'Studio name' }, hint: { 'zh-CN': '导航、页脚、字标和文案里的名字', en: 'Used in nav, footer, mark and copy' }, default: 'Halftone', maxLength: 20, group: 'content' },
    { key: 'headline', type: 'text', label: { 'zh-CN': '首屏标题文案', en: 'Headline' }, default: 'A small studio for products that need to feel finished.', maxLength: 80, group: 'content' },
    { key: 'accent', type: 'color', label: { 'zh-CN': '主色', en: 'Accent' }, hint: { 'zh-CN': '光带、按钮、图标底色、封面渐变都从它推出来', en: 'Beam, buttons, icon chips and cover gradients derive from it' }, default: '#6d5efc', group: 'look' },
    {
      key: 'fontPair',
      type: 'select',
      label: { 'zh-CN': '字体搭配', en: 'Font pairing' },
      default: 'bricolage',
      options: [
        { value: 'bricolage', label: { 'zh-CN': 'Bricolage Grotesque + Inter Tight', en: 'Bricolage Grotesque + Inter Tight' } },
        { value: 'grotesk', label: { 'zh-CN': 'Space Grotesk + Geist', en: 'Space Grotesk + Geist' } },
        { value: 'outfit', label: { 'zh-CN': 'Outfit + Manrope', en: 'Outfit + Manrope' } },
        { value: 'syne', label: { 'zh-CN': 'Syne + Plus Jakarta', en: 'Syne + Plus Jakarta' } },
      ],
      group: 'look',
    },
    { key: 'radius', type: 'number', label: { 'zh-CN': '圆角', en: 'Corner radius' }, default: 20, min: 4, max: 32, step: 1, unit: 'px', safe: [10, 28], group: 'look' },
    { key: 'dark', type: 'boolean', label: { 'zh-CN': '深色模式', en: 'Dark mode' }, default: true, group: 'look' },
    { key: 'animate', type: 'boolean', label: { 'zh-CN': '入场与光带动画', en: 'Entrance and beam animation' }, default: true, group: 'motion' },
  ],
  presets: [
    { id: 'midnight-violet', name: { 'zh-CN': '午夜紫', en: 'Midnight Violet' }, values: { accent: '#6d5efc', fontPair: 'bricolage', radius: 20, dark: true } },
    { id: 'signal-lime', name: { 'zh-CN': '信号绿', en: 'Signal Lime' }, values: { accent: '#b6f03c', fontPair: 'grotesk', radius: 10, dark: true } },
    { id: 'daylight', name: { 'zh-CN': '日光', en: 'Daylight' }, values: { accent: '#e5484d', fontPair: 'outfit', radius: 24, dark: false } },
    { id: 'ocean-syne', name: { 'zh-CN': '深海', en: 'Ocean Syne' }, values: { accent: '#22a7f0', fontPair: 'syne', radius: 16, dark: true } },
  ],
  dependencies: ['motion/react', '@motif/runtime'],
  fonts: ['Bricolage Grotesque Variable', 'Inter Tight Variable', 'Space Grotesk Variable', 'Geist Variable', 'Outfit Variable', 'Manrope Variable', 'Syne Variable', 'Plus Jakarta Sans Variable', 'Geist Mono Variable'],
  guidance: {
    use: [
      'A marketing site for a design studio, dev shop, consultancy or any small service business that sells engagements: hero with product visual, logos, services, work, process, pricing, testimonials, journal, FAQ, contact.',
      'Adapt it by editing the arrays at the top of the component (BRANDS, WORK, SERVICES, STEPS, STATS, QUOTES, PLANS, POSTS, FAQS) and the name/headline params. Keep the section order: it is a proven conversion sequence.',
    ],
    rules: [
      'One accent color drives everything (beam, primary button, icon chips, cover gradients). Surfaces step through --bg, --bg-2, --card, --card-2 with 1px --line borders; never use pure black or white fills.',
      'Headings use the head font at weight 600 with -0.03em tracking and balanced wrapping; labels use the mono font at 11px, uppercase, 0.2em tracking.',
      'Primary CTA is a filled accent pill, secondary is an outlined pill; only one filled accent button per viewport.',
      'The hero visual is built from divs and SVG (MockApp). Replace its content with your own product UI; never add screenshots. Client names are invented SVG wordmarks; do not use real logos.',
      'Every section fades up once when scrolled into view (22px, 0.65s). Do not add parallax or looping motion other than the hero beam.',
      'Copy is concrete: numbers, durations, prices and named deliverables. No superlatives.',
    ],
  },
  perf: { webgl: false, maxDpr: 2 },
  a11y: { reducedMotion: 'static' },
  capture: { scroll: true, posterTime: 0.5, loop: 8 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'tailcast',
      repo: 'matt765/Tailcast',
      sha: '85843e5feaa46bdee05e180cf0c76f12408d7557',
      paths: [
        'src/pages/index.astro',
        'src/components/Navbar.astro',
        'src/components/Hero.astro',
        'src/components/BentoFeatures.astro',
        'src/components/FeaturesDiagonal.astro',
        'src/components/HowItWorks.astro',
        'src/components/Brands.astro',
        'src/components/Gallery.astro',
        'src/components/Testimonials.astro',
        'src/components/Pricing.astro',
        'src/components/Blog.astro',
        'src/components/FAQ.astro',
        'src/components/CtaBottom.astro',
        'src/components/Footer.astro',
      ],
      spdx: 'MIT',
      copyright: ['Copyright (c) 2022-2026 Mateusz Wyrębek'],
    },
    modifications: [
      'Astro components rewritten as one React 19 + Tailwind v4 component; the section sequence, floating navbar, glowing hero product frame, bento grid, diagonal band, pricing cards and FAQ are kept.',
      'Repositioned from an analytics SaaS to a design and engineering studio; all copy, names, prices and numbers are invented.',
      'The dashboard image is replaced by a div/SVG product mock with an animated conic-gradient beam border; brand logos are invented SVG wordmarks; blog and gallery images are generated gradient/SVG covers.',
      'Theming is driven by accent, font pairing, radius and a dark flag via CSS variables instead of the upstream Theme.css tokens.',
      'Scroll reveals use motion (whileInView) and respect prefers-reduced-motion.',
    ],
    assets: [],
  },
})
