import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'globe',
  status: 'published',
  title: { 'zh-CN': '发光地球', en: 'Globe' },
  summary: {
    'zh-CN': '一颗缓缓自转的点阵地球，城市地标发光，飞线在大陆之间划过。可以用手拖动。适合放在产品首屏，讲「全球」和「网络」。',
    en: 'A slowly turning dot-matrix globe with glowing city markers and arcs flying between continents. Drag to spin it. Made for hero sections about reach and networks.',
  },
  category: '3d',
  tags: ['globe', 'earth', 'webgl', 'map', 'hero', 'interactive'],
  runtime: ['react', 'webgl'],
  entry: { file: 'globe.tsx', export: 'Globe' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'globe.tsx', role: 'component' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    { key: 'baseColor', type: 'color', label: { 'zh-CN': '球体颜色', en: 'Base color' }, default: '#3a4a8f', group: 'look' },
    { key: 'glowColor', type: 'color', label: { 'zh-CN': '光晕颜色', en: 'Glow color' }, default: '#5b6cff', group: 'look' },
    { key: 'markerColor', type: 'color', label: { 'zh-CN': '地标与飞线颜色', en: 'Marker and arc color' }, default: '#ffb86b', group: 'look' },
    {
      key: 'dark',
      type: 'number',
      label: { 'zh-CN': '明暗', en: 'Darkness' },
      hint: { 'zh-CN': '0 是亮面球体，1 是暗色球体加发光陆地', en: '0 is a lit sphere, 1 is a dark sphere with glowing land' },
      default: 1,
      min: 0,
      max: 1,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'diffuse',
      type: 'number',
      label: { 'zh-CN': '漫反射', en: 'Diffuse' },
      hint: { 'zh-CN': '越大陆地越亮、层次越强', en: 'Higher values make the land brighter and more contrasty' },
      default: 1.4,
      min: 0.4,
      max: 3,
      step: 0.01,
      safe: [0.8, 2.2],
      group: 'look',
    },
    {
      key: 'mapBrightness',
      type: 'number',
      label: { 'zh-CN': '陆地亮度', en: 'Land brightness' },
      default: 7,
      min: 2,
      max: 14,
      step: 0.1,
      safe: [4, 10],
      group: 'look',
    },
    {
      key: 'rotationSpeed',
      type: 'number',
      label: { 'zh-CN': '自转速度', en: 'Rotation speed' },
      hint: { 'zh-CN': '弧度每秒；开启「减少动态效果」时不自转', en: 'Radians per second; no auto-rotation under reduced motion' },
      default: 0.12,
      min: 0,
      max: 0.6,
      step: 0.01,
      group: 'motion',
    },
    {
      key: 'tilt',
      type: 'number',
      label: { 'zh-CN': '俯仰角', en: 'Tilt' },
      default: 0.3,
      min: -0.6,
      max: 0.9,
      step: 0.01,
      group: 'motion',
    },
    {
      key: 'markerCount',
      type: 'number',
      label: { 'zh-CN': '地标数量', en: 'Markers' },
      default: 8,
      min: 0,
      max: 24,
      step: 1,
      safe: [3, 16],
      group: 'data',
    },
    {
      key: 'arcCount',
      type: 'number',
      label: { 'zh-CN': '飞线数量', en: 'Arcs' },
      default: 4,
      min: 0,
      max: 8,
      step: 1,
      group: 'data',
    },
  ],
  presets: [
    {
      id: 'nocturne',
      name: { 'zh-CN': '夜曲', en: 'Nocturne' },
      values: { baseColor: '#3a4a8f', glowColor: '#5b6cff', markerColor: '#ffb86b', dark: 1, diffuse: 1.4, mapBrightness: 7 },
    },
    {
      id: 'ember',
      name: { 'zh-CN': '余烬', en: 'Ember' },
      values: { baseColor: '#8a3b2a', glowColor: '#ff6a3d', markerColor: '#ffd9a0', dark: 1, diffuse: 1.6, mapBrightness: 8, tilt: 0.2, arcCount: 6 },
    },
    {
      id: 'glacier',
      name: { 'zh-CN': '冰川', en: 'Glacier' },
      values: { baseColor: '#cfe6ff', glowColor: '#8fc7ff', markerColor: '#0a6cff', dark: 0.15, diffuse: 1.2, mapBrightness: 5, markerCount: 6 },
    },
    {
      id: 'terminal',
      name: { 'zh-CN': '终端', en: 'Terminal' },
      values: { baseColor: '#1f6b46', glowColor: '#22ff99', markerColor: '#b8ffd9', dark: 1, diffuse: 1.8, mapBrightness: 9, rotationSpeed: 0.2, markerCount: 14, arcCount: 8 },
    },
  ],
  dependencies: ['cobe', '@motif/runtime'],
  perf: { webgl: true, maxDpr: 2 },
  a11y: { reducedMotion: 'static' },
  capture: { posterTime: 2, loop: 8 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'cobe',
      repo: 'shuding/cobe',
      sha: '7e94076fa8c38707f4c9cd114ff4f7c5c880971e',
      paths: ['README.md', 'src/index.d.ts'],
      spdx: 'MIT',
      copyright: ['Copyright (c) 2021 Shu Ding'],
    },
    modifications: [
      'Wrapped the cobe package (2.0.1) as a React component that owns the render loop through motif-runtime: pauses offscreen and in hidden tabs, and does not auto-rotate under reduced motion.',
      'The canvas is created imperatively because cobe re-parents it; handles context loss and restore and releases the context on unmount.',
      'Added a curated city and route list driving markers and arcs, hex color params, drag-to-rotate with inertia, and resize handling.',
    ],
    assets: [],
  },
})
