import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'style-editorial',
  status: 'published',
  title: { 'zh-CN': '杂志编辑', en: 'Editorial' },
  summary: {
    'zh-CN': '衬线体、斜体标题、细线与双线、页边注和首字下沉：像一本认真排版的杂志。颜色只有纸和墨，外加一支红铅笔。适合长文、博客、出版物和个人站。',
    en: 'Serif type, italic headings, hairline and double rules, margin notes and a drop cap: the page of a carefully typeset magazine. Paper, ink and one red pencil. For essays, blogs, publications and personal sites.',
  },
  kind: 'style',
  category: 'editorial',
  tags: ['editorial', 'serif', 'magazine', 'tufte', 'margin notes', 'typography', 'tokens', 'design system'],
  runtime: ['react', 'css'],
  entry: { file: 'style-editorial.tsx', export: 'Editorial' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'light' },
  files: [
    { path: 'style-editorial.tsx', role: 'component' },
    { path: 'style-editorial.css', role: 'style' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    {
      key: 'accent',
      type: 'color',
      group: 'look',
      label: { 'zh-CN': '红铅笔色', en: 'Red-pencil accent' },
      hint: { 'zh-CN': '只用于线条、链接、首字下沉和悬停', en: 'Only for rules, links, the drop cap and hover' },
      default: '#b3261e',
    },
    {
      key: 'ruleWeight',
      type: 'number',
      group: 'shape',
      label: { 'zh-CN': '线条粗细', en: 'Rule weight' },
      default: 1,
      min: 1,
      max: 3,
      step: 0.5,
      unit: 'px',
      safe: [1, 2],
    },
    {
      key: 'radius',
      type: 'number',
      group: 'shape',
      label: { 'zh-CN': '圆角', en: 'Corner radius' },
      default: 0,
      min: 0,
      max: 8,
      step: 1,
      unit: 'px',
      safe: [0, 4],
    },
    {
      key: 'fontPairing',
      type: 'select',
      group: 'type',
      label: { 'zh-CN': '字体搭配', en: 'Font pairing' },
      default: 'instrument',
      options: [
        {
          value: 'instrument',
          label: { 'zh-CN': 'Instrument Serif + Newsreader', en: 'Instrument Serif + Newsreader' },
        },
        { value: 'playfair', label: { 'zh-CN': 'Playfair + Newsreader', en: 'Playfair + Newsreader' } },
        { value: 'fraunces', label: { 'zh-CN': 'Fraunces + Newsreader', en: 'Fraunces + Newsreader' } },
        { value: 'dm-serif', label: { 'zh-CN': 'DM 衬线 + Newsreader', en: 'DM Serif + Newsreader' } },
      ],
    },
    {
      key: 'measure',
      type: 'number',
      group: 'layout',
      label: { 'zh-CN': '行宽', en: 'Reading measure' },
      hint: { 'zh-CN': '正文一行大约多少个字符', en: 'Approximate characters per line' },
      default: 64,
      min: 48,
      max: 76,
      step: 1,
      safe: [56, 70],
    },
    {
      key: 'density',
      type: 'number',
      group: 'layout',
      label: { 'zh-CN': '疏密', en: 'Density' },
      default: 1,
      min: 0.85,
      max: 1.2,
      step: 0.05,
      unit: 'x',
      safe: [0.9, 1.15],
    },
    {
      key: 'mode',
      type: 'select',
      group: 'look',
      label: { 'zh-CN': '纸张', en: 'Edition' },
      default: 'paper',
      options: [
        { value: 'paper', label: { 'zh-CN': '日报纸', en: 'Paper' } },
        { value: 'night', label: { 'zh-CN': '夜刊', en: 'Night' } },
      ],
    },
    {
      key: 'margin',
      type: 'boolean',
      group: 'layout',
      label: { 'zh-CN': '页边注', en: 'Margin notes' },
      default: true,
    },
    {
      key: 'dropcap',
      type: 'boolean',
      group: 'look',
      label: { 'zh-CN': '首字下沉', en: 'Drop cap' },
      default: true,
    },
  ],
  presets: [
    {
      id: 'red-pencil',
      name: { 'zh-CN': '红铅笔', en: 'Red pencil' },
      values: {
        accent: '#b3261e',
        ruleWeight: 1,
        radius: 0,
        measure: 64,
        density: 1,
        fontPairing: 'instrument',
        mode: 'paper',
        margin: true,
        dropcap: true,
      },
    },
    {
      id: 'ink-blue',
      name: { 'zh-CN': '蓝黑墨水', en: 'Blue-black ink' },
      values: {
        accent: '#1f4e8c',
        ruleWeight: 1,
        radius: 0,
        measure: 60,
        density: 1,
        fontPairing: 'playfair',
        mode: 'paper',
        margin: true,
        dropcap: true,
      },
    },
    {
      id: 'forest-review',
      name: { 'zh-CN': '林间评论', en: 'Forest review' },
      values: {
        accent: '#2f6b4f',
        ruleWeight: 1.5,
        radius: 2,
        measure: 66,
        density: 1.05,
        fontPairing: 'fraunces',
        mode: 'paper',
        margin: true,
        dropcap: false,
      },
    },
    {
      id: 'night-edition',
      name: { 'zh-CN': '夜刊', en: 'Night edition' },
      values: {
        accent: '#e6806a',
        ruleWeight: 1,
        radius: 0,
        measure: 62,
        density: 1,
        fontPairing: 'dm-serif',
        mode: 'night',
        margin: true,
        dropcap: true,
      },
    },
  ],
  dependencies: ['@motif/runtime'],
  fonts: [
    'Instrument Serif',
    'Newsreader Variable',
    'Playfair Display Variable',
    'Fraunces Variable',
    'DM Serif Display',
  ],
  guidance: {
    use: [
      'Use for essays, blogs, newsletters, publications, portfolios of writers and designers, and any product where reading is the main activity.',
      'Avoid for dense dashboards, games or anything that needs loud, saturated interface chrome.',
    ],
    rules: [
      'Palette ratio: about 85% paper ground (a warm off-white tinted 2% by the accent, or a warm near-black in night mode), 10% ink for text and rules, 4% the single accent used like a red pencil (kickers, links, drop cap, active rule, hover), 1% muted tag colors (ochre, rose, sage) used only in badges and tinted panels. Never pure white or pure black; never more than one accent.',
      'Typography: a display serif for headlines (Instrument Serif, Playfair Display, Fraunces or DM Serif Display) at weight 400 with -0.025em tracking on the display size, and Newsreader for text at 17px / 1.6. Headings are italic, never bold; emphasis is italic. Kickers, labels, buttons and badges are small uppercase text (0.66-0.78rem) with 0.14-0.16em tracking. Set numbers in lining tabular figures.',
      'Measure: keep running text to 56-70 characters per line. Put explanations in a right-hand margin as numbered side notes at 14px in muted ink, with a hairline above; on narrow screens they fall below the content.',
      'Rules replace boxes: a 3px ink rule above panels, hairlines between list items, a heavy-over-thin rule under mastheads, a double rule at the end of a page. Controls are rectangles (radius 0-4px) with 1px outlines or solid ink; no shadows, no gradients, no glass.',
      'Motion is quiet: 200ms ease color and border fades on hover, a 220ms slide on switches. Nothing bounces, scales or parallaxes. Reduced motion removes the transitions.',
      'Use a drop cap on the first paragraph of an article, one pull quote per screen (italic display serif, accent rule above), and sparklines or small figures with an italic caption for data. Use sidenote markers in accent color.',
      'Do not use bold headings, sans-serif interface text, pill buttons, drop shadows, gradients, emoji, stock photography placeholders or centered body text.',
    ],
  },
  perf: { webgl: false, maxDpr: 2 },
  a11y: { reducedMotion: 'static' },
  capture: { scroll: true, posterTime: 0.5, loop: 8 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'tufte-css',
      repo: 'edwardtufte/tufte-css',
      sha: 'b5d7b7bbe5ce9c4c50fcfad4f19ee3646cfd7ae1',
      paths: ['tufte.css'],
      spdx: 'MIT',
      copyright: ['Copyright (c) 2014 Dave Liepmann'],
    },
    modifications: [
      'Kept the Tufte layout ideas (an off-white paper ground, dark-gray ink, italic headings, small-caps style kickers, side notes with numbered markers in a right margin, narrow reading measure, sparse rules) and rebuilt them as scoped CSS variables and React primitives (button, ruled panel, underline field, badge, tabs, pull-out alert, switch).',
      'The ET Book typeface is not used. Headlines and body copy use OFL serifs from the Motif font list (Instrument Serif, Playfair Display, Fraunces, DM Serif Display and Newsreader).',
      'Added an accent color, dark (night) mode, configurable reading measure, rule weight and corner radius, an optional drop cap and margin notes toggle, a sparkline figure and a pull quote in the demo; all drawn with plain elements and inline SVG.',
    ],
    assets: [],
  },
})
