import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'pricing-usage-slider',
  status: 'published',
  title: { 'zh-CN': '用量滑块定价', en: 'Usage Slider Pricing' },
  summary: {
    'zh-CN': '极光背景上的一张毛玻璃定价卡：拖动对数刻度的用量滑块，右侧价格、明细和有效单价实时更新，阶梯计价越用越便宜。适合按量计费的 API 和基础设施产品。',
    en: 'One frosted pricing card on an aurora backdrop: drag a log-scale usage slider and the price, breakdown and effective rate update live, with volume tiers that get cheaper as you grow. Built for usage-billed APIs and infrastructure.',
  },
  kind: 'section',
  category: 'pricing',
  tags: ['pricing', 'usage based', 'slider', 'calculator', 'glass', 'aurora'],
  runtime: ['react', 'css'],
  entry: { file: 'pricing-usage-slider.tsx', export: 'PricingUsageSlider' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'pricing-usage-slider.tsx', role: 'component' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    { key: 'heading', type: 'text', label: { 'zh-CN': '标题', en: 'Heading' }, default: 'Pay for the traffic you actually send', maxLength: 64, group: 'content' },
    {
      key: 'subline',
      type: 'text',
      label: { 'zh-CN': '副标题', en: 'Subline' },
      default: 'One plan, no seat fees. Slide to your monthly volume and see the bill before you sign up.',
      maxLength: 130,
      group: 'content',
    },
    { key: 'cta', type: 'text', label: { 'zh-CN': '按钮文案', en: 'Button label' }, default: 'Start with the Scale plan', maxLength: 30, group: 'content' },
    {
      key: 'currency',
      type: 'select',
      label: { 'zh-CN': '货币符号', en: 'Currency' },
      default: '$',
      options: [
        { value: '$', label: { 'zh-CN': '$ 美元', en: '$ Dollar' } },
        { value: '€', label: { 'zh-CN': '€ 欧元', en: '€ Euro' } },
        { value: '£', label: { 'zh-CN': '£ 英镑', en: '£ Pound' } },
        { value: '¥', label: { 'zh-CN': '¥ 元', en: '¥ Yuan' } },
      ],
      group: 'pricing',
    },
    { key: 'basePrice', type: 'number', label: { 'zh-CN': '基础月费', en: 'Base price' }, default: 29, min: 9, max: 199, step: 1, safe: [19, 99], group: 'pricing' },
    { key: 'overage', type: 'number', label: { 'zh-CN': '超量单价（每百万次）', en: 'Overage per 1M' }, hint: { 'zh-CN': '2M 到 10M 区间的单价，后两档自动更低', en: 'Rate for the 2M to 10M band; the next two bands are cheaper' }, default: 1.2, min: 0.4, max: 3, step: 0.1, safe: [0.6, 2], group: 'pricing' },
    { key: 'accent', type: 'color', label: { 'zh-CN': '主色', en: 'Accent color' }, default: '#8b7bff', group: 'look' },
    {
      key: 'tone',
      type: 'select',
      label: { 'zh-CN': '明暗', en: 'Tone' },
      default: 'dark',
      options: [
        { value: 'dark', label: { 'zh-CN': '深色', en: 'Dark' } },
        { value: 'light', label: { 'zh-CN': '浅色', en: 'Light' } },
      ],
      group: 'look',
    },
    {
      key: 'surface',
      type: 'select',
      label: { 'zh-CN': '卡片质感', en: 'Card surface' },
      default: 'glass',
      options: [
        { value: 'glass', label: { 'zh-CN': '毛玻璃', en: 'Frosted glass' } },
        { value: 'solid', label: { 'zh-CN': '实色', en: 'Solid' } },
      ],
      group: 'look',
    },
    {
      key: 'font',
      type: 'select',
      label: { 'zh-CN': '标题字体', en: 'Heading font' },
      default: 'geist',
      options: [
        { value: 'geist', label: { 'zh-CN': 'Geist 无衬线', en: 'Geist sans' } },
        { value: 'grotesk', label: { 'zh-CN': 'Space Grotesk', en: 'Space Grotesk' } },
        { value: 'serif', label: { 'zh-CN': 'Instrument 衬线', en: 'Instrument serif' } },
      ],
      group: 'look',
    },
    { key: 'radius', type: 'number', label: { 'zh-CN': '卡片圆角', en: 'Card radius' }, default: 28, min: 0, max: 40, step: 1, unit: 'px', safe: [10, 36], group: 'look' },
  ],
  presets: [
    { id: 'aurora', name: { 'zh-CN': '极光', en: 'Aurora' }, values: {} },
    { id: 'coral-reef', name: { 'zh-CN': '珊瑚礁', en: 'Coral Reef' }, values: { accent: '#ff6b6b', font: 'grotesk', basePrice: 49, overage: 1.6 } },
    { id: 'linen-solid', name: { 'zh-CN': '亚麻实色', en: 'Linen Solid' }, values: { tone: 'light', accent: '#3b5bdb', surface: 'solid', font: 'serif', radius: 20, currency: '€' } },
  ],
  dependencies: ['@motif/runtime'],
  fonts: ['Geist Variable', 'Space Grotesk Variable', 'Instrument Serif'],
  guidance: {
    rules: [
      'One plan only: the slider is the whole pricing story, so do not add tier cards beside it.',
      'The price must be computed from the same numbers shown in the breakdown (base, included volume, banded rates); never hard-code the displayed total.',
      'Keep the native range input (transparent, on top of the custom track) so keyboard and screen readers work, and keep aria-valuetext.',
      'Use the accent for the thumb, fill and the single CTA only; the aurora backdrop derives its second color from the accent.',
    ],
  },
  perf: { webgl: false, maxDpr: 2 },
  a11y: { reducedMotion: 'static' },
  capture: { scroll: true, posterTime: 1.6, loop: 8 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'uitripled',
      repo: 'moumen-soliman/uitripled',
      sha: '05d18376db775072ed61d0cab8ea184f8f527429',
      paths: ['packages/components/react-shadcn/src/components/sections/glassmorphism-pricing-block.tsx'],
      spdx: 'MIT',
      copyright: ['Copyright (c) 2026 uitripled'],
    },
    modifications: [
      'Kept the frosted-glass pricing card idea; replaced the three static plans with a single usage-based card driven by a log-scale slider and banded pricing.',
      'The aurora backdrop is CSS radial gradients from the accent and a hue-shifted second color; framer-motion and lucide were dropped for plain elements and inline SVG.',
      'The slider is a transparent native range input over a custom track for accessibility; position can be controlled so a demo can drive it.',
    ],
    assets: [],
  },
})
