import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'style-neobrutalism',
  status: 'published',
  title: { 'zh-CN': '新粗野主义', en: 'Neobrutalism' },
  summary: {
    'zh-CN': '粗黑描边、无模糊的硬阴影、高饱和平涂色块：每个元素都像一张贴纸，按下去会真的「压」进页面。适合工具类产品、创作者主页和有态度的品牌。',
    en: 'Thick black outlines, blur-free hard shadows and flat saturated color: every element is a sticker that visibly presses into the page. For tools, creator sites and brands with an attitude.',
  },
  kind: 'style',
  category: 'bold',
  tags: ['neobrutalism', 'brutalist', 'hard shadow', 'bold', 'tokens', 'design system'],
  runtime: ['react', 'css'],
  entry: { file: 'style-neobrutalism.tsx', export: 'NeoBrutalism' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'light' },
  files: [
    { path: 'style-neobrutalism.tsx', role: 'component' },
    { path: 'style-neobrutalism.css', role: 'style' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    {
      key: 'accent',
      type: 'color',
      group: 'look',
      label: { 'zh-CN': '强调色', en: 'Accent color' },
      hint: { 'zh-CN': '页面底色、浅色块和按钮字色都会跟着它变', en: 'Page ground, tints and button text color follow it' },
      default: '#4d7cff',
    },
    {
      key: 'radius',
      type: 'number',
      group: 'shape',
      label: { 'zh-CN': '圆角', en: 'Corner radius' },
      default: 8,
      min: 0,
      max: 20,
      step: 1,
      unit: 'px',
      safe: [0, 16],
    },
    {
      key: 'borderWidth',
      type: 'number',
      group: 'shape',
      label: { 'zh-CN': '描边粗细', en: 'Border width' },
      default: 3,
      min: 2,
      max: 5,
      step: 0.5,
      unit: 'px',
      safe: [2, 4],
    },
    {
      key: 'shadowOffset',
      type: 'number',
      group: 'shape',
      label: { 'zh-CN': '阴影偏移', en: 'Shadow offset' },
      default: 5,
      min: 2,
      max: 10,
      step: 1,
      unit: 'px',
      safe: [3, 8],
    },
    {
      key: 'fontPairing',
      type: 'select',
      group: 'type',
      label: { 'zh-CN': '字体搭配', en: 'Font pairing' },
      default: 'bricolage',
      options: [
        { value: 'bricolage', label: { 'zh-CN': '布里科拉 + 曼罗普', en: 'Bricolage + Manrope' } },
        { value: 'archivo', label: { 'zh-CN': '阿基沃黑体 + Inter Tight', en: 'Archivo Black + Inter Tight' } },
        { value: 'grotesk', label: { 'zh-CN': '太空怪诞体', en: 'Space Grotesk' } },
        { value: 'plex', label: { 'zh-CN': '怪诞体 + 等宽正文', en: 'Grotesk + Plex Mono' } },
      ],
    },
    {
      key: 'density',
      type: 'number',
      group: 'layout',
      label: { 'zh-CN': '疏密', en: 'Density' },
      default: 1,
      min: 0.85,
      max: 1.2,
      step: 0.05,
      unit: 'x',
      safe: [0.9, 1.15],
    },
    {
      key: 'dots',
      type: 'boolean',
      group: 'look',
      label: { 'zh-CN': '点阵底纹', en: 'Dot grid ground' },
      default: true,
    },
  ],
  presets: [
    {
      id: 'ultramarine',
      name: { 'zh-CN': '群青', en: 'Ultramarine' },
      values: {
        accent: '#4d7cff',
        radius: 8,
        borderWidth: 3,
        shadowOffset: 5,
        density: 1,
        fontPairing: 'bricolage',
        dots: true,
      },
    },
    {
      id: 'bubblegum',
      name: { 'zh-CN': '泡泡糖', en: 'Bubblegum' },
      values: {
        accent: '#ff6fb1',
        radius: 14,
        borderWidth: 3,
        shadowOffset: 6,
        density: 1.05,
        fontPairing: 'archivo',
        dots: true,
      },
    },
    {
      id: 'lemon-soda',
      name: { 'zh-CN': '柠檬汽水', en: 'Lemon soda' },
      values: {
        accent: '#ffd23f',
        radius: 4,
        borderWidth: 4,
        shadowOffset: 8,
        density: 1,
        fontPairing: 'grotesk',
        dots: false,
      },
    },
    {
      id: 'vermilion',
      name: { 'zh-CN': '朱砂', en: 'Vermilion' },
      values: {
        accent: '#ff4d2e',
        radius: 0,
        borderWidth: 3,
        shadowOffset: 6,
        density: 0.95,
        fontPairing: 'plex',
        dots: true,
      },
    },
  ],
  dependencies: ['@motif/runtime'],
  fonts: [
    'Bricolage Grotesque Variable',
    'Manrope Variable',
    'Archivo Black',
    'Inter Tight Variable',
    'Space Grotesk Variable',
    'IBM Plex Mono',
  ],
  guidance: {
    use: [
      'Use for tools, creator and indie-product sites, dashboards for playful audiences, and anything that should feel loud, honest and handmade rather than polished-corporate.',
      'Avoid for finance, healthcare or other contexts where the audience expects calm, restrained visuals.',
    ],
    rules: [
      'Palette ratio: about 60% flat ground (a pale tint of the accent or warm cream), 25% white surfaces, 10% accent, 5% pop colors (yellow, pink, mint). Text and outlines are one near-black ink; never use gray borders.',
      'Every interactive or containing surface has an opaque outline (2-4px, same ink) and a hard offset shadow with zero blur in the same ink. Shadow offset is one token; hover shrinks the shadow to ~60% while translating the box by the removed amount, active shrinks it to zero.',
      'Fills are flat. No gradients, no glow, no blur, no translucency, no inner shadows. Depth comes only from the offset shadow and from overlap.',
      'Typography: a heavy display face (weight 800) with tight negative tracking for headings, a friendly humanist or mono face at weight 500 for body. Headings are sentence case; small labels are uppercase with wide tracking. Use one highlighter-style mark per screen, not more.',
      'Shape: one radius token for everything (0-16px); pills only for badges and switches. Cards may be rotated 1-3 degrees for a sticker feel, but never text blocks or form fields.',
      'Motion: fast and mechanical, 80-120ms, ease-out, only transform / box-shadow / background-color. No springs, no fades, no bounce. Reduced motion removes the transitions.',
      'Text on the accent color is chosen by contrast (ink or white), never a fixed color. Keep focus rings as a 3px solid ink outline with offset.',
      'Do not add gradients, drop shadows with blur, glassmorphism, thin 1px borders, or rounded-2xl soft cards; do not mix in a second shadow style.',
    ],
  },
  perf: { webgl: false, maxDpr: 2 },
  a11y: { reducedMotion: 'static' },
  capture: { scroll: true, posterTime: 0.5, loop: 8 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'neobrutalism-components',
      repo: 'ekmas/neobrutalism-components',
      sha: '3306a802724874a85f93079702b2795370a279d4',
      paths: [
        'src/styling/globals.css',
        'src/components/ui/button.tsx',
        'src/components/ui/card.tsx',
        'src/components/ui/input.tsx',
      ],
      spdx: 'MIT',
      copyright: ['Copyright (c) 2023 Samuel Breznjak'],
    },
    modifications: [
      'Rebuilt the upstream token set (border radius, box-shadow offsets, main / background / border colors, heading and base font weights) as CSS variables scoped to a .nb-root element and driven by component props instead of a global :root.',
      'Replaced the shadcn/Radix/Tailwind components with plain React primitives (button, card, field, badge, tabs, alert, switch) styled by one CSS file; the press interaction (shadow shrinks while the box translates by the same offset) follows the upstream reverse-box-shadow idea.',
      'The page background and tints are derived from the accent color with color-mix, the text color on the accent is picked by contrast, and the extra pop colors (sun, pink, mint) are new.',
      'Added the style sheet demo. No upstream images or avatars are used; fonts are self-hosted OFL families from the Motif font list.',
    ],
    assets: [],
  },
})
