import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'style-retro-bold',
  status: 'published',
  title: { 'zh-CN': '复古大胆', en: 'Retro Bold' },
  summary: {
    'zh-CN': '暖色纸张底、黑色描边、像琴键一样按下去的按钮，再加一点日落色带和半调网点：老唱片的味道，现代的分寸。适合音乐、咖啡、独立品牌和内容社区。',
    en: 'Warm paper ground, black outlines, keys that press down, sunset stripes and halftone dots: old-record charm with modern manners. For music, coffee, indie brands and communities.',
  },
  kind: 'style',
  category: 'retro',
  tags: ['retro', 'bold', 'vintage', 'halftone', 'sunset', 'tokens', 'design system'],
  runtime: ['react', 'css'],
  entry: { file: 'style-retro-bold.tsx', export: 'RetroBold' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'light' },
  files: [
    { path: 'style-retro-bold.tsx', role: 'component' },
    { path: 'style-retro-bold.css', role: 'style' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    {
      key: 'accent',
      type: 'color',
      group: 'look',
      label: { 'zh-CN': '强调色', en: 'Accent color' },
      hint: { 'zh-CN': '纸张底色和按钮字色会跟着它变', en: 'The paper ground and button text follow it' },
      default: '#ffdb33',
    },
    {
      key: 'radius',
      type: 'number',
      group: 'shape',
      label: { 'zh-CN': '圆角', en: 'Corner radius' },
      default: 4,
      min: 0,
      max: 14,
      step: 1,
      unit: 'px',
      safe: [0, 10],
    },
    {
      key: 'borderWidth',
      type: 'number',
      group: 'shape',
      label: { 'zh-CN': '描边粗细', en: 'Border width' },
      default: 2,
      min: 2,
      max: 4,
      step: 0.5,
      unit: 'px',
      safe: [2, 3],
    },
    {
      key: 'shadowOffset',
      type: 'number',
      group: 'shape',
      label: { 'zh-CN': '阴影深度', en: 'Shadow depth' },
      default: 4,
      min: 2,
      max: 8,
      step: 1,
      unit: 'px',
      safe: [3, 6],
    },
    {
      key: 'fontPairing',
      type: 'select',
      group: 'type',
      label: { 'zh-CN': '字体搭配', en: 'Font pairing' },
      default: 'archivo-plex',
      options: [
        { value: 'archivo-plex', label: { 'zh-CN': '阿基沃黑体 + Plex Sans', en: 'Archivo Black + Plex Sans' } },
        { value: 'dm-serif', label: { 'zh-CN': 'DM 衬线展示 + Inter Tight', en: 'DM Serif + Inter Tight' } },
        { value: 'fraunces', label: { 'zh-CN': '弗劳恩斯软衬线 + Jakarta', en: 'Fraunces + Jakarta Sans' } },
        { value: 'syne', label: { 'zh-CN': 'Syne + 曼罗普', en: 'Syne + Manrope' } },
      ],
    },
    {
      key: 'density',
      type: 'number',
      group: 'layout',
      label: { 'zh-CN': '疏密', en: 'Density' },
      default: 1,
      min: 0.85,
      max: 1.2,
      step: 0.05,
      unit: 'x',
      safe: [0.9, 1.15],
    },
    {
      key: 'halftone',
      type: 'boolean',
      group: 'look',
      label: { 'zh-CN': '半调网点底纹', en: 'Halftone ground' },
      default: true,
    },
  ],
  presets: [
    {
      id: 'sunday-yellow',
      name: { 'zh-CN': '周日蛋黄', en: 'Sunday yolk' },
      values: {
        accent: '#ffdb33',
        radius: 4,
        borderWidth: 2,
        shadowOffset: 4,
        density: 1,
        fontPairing: 'archivo-plex',
        halftone: true,
      },
    },
    {
      id: 'coral-diner',
      name: { 'zh-CN': '珊瑚餐厅', en: 'Coral diner' },
      values: {
        accent: '#ff7a6b',
        radius: 8,
        borderWidth: 2.5,
        shadowOffset: 5,
        density: 1.05,
        fontPairing: 'fraunces',
        halftone: true,
      },
    },
    {
      id: 'teal-tape',
      name: { 'zh-CN': '青绿磁带', en: 'Teal tape' },
      values: {
        accent: '#3cc9b6',
        radius: 2,
        borderWidth: 2,
        shadowOffset: 4,
        density: 0.95,
        fontPairing: 'syne',
        halftone: false,
      },
    },
    {
      id: 'grape-soda',
      name: { 'zh-CN': '葡萄汽水', en: 'Grape soda' },
      values: {
        accent: '#b18cff',
        radius: 6,
        borderWidth: 3,
        shadowOffset: 6,
        density: 1,
        fontPairing: 'dm-serif',
        halftone: true,
      },
    },
  ],
  dependencies: ['@motif/runtime'],
  fonts: [
    'Archivo Black',
    'IBM Plex Sans Variable',
    'DM Serif Display',
    'Inter Tight Variable',
    'Fraunces Variable',
    'Plus Jakarta Sans Variable',
    'Syne Variable',
    'Manrope Variable',
  ],
  guidance: {
    use: [
      'Use for music, coffee, food, indie and community brands, event pages and newsletters that want warmth, nostalgia and a hand-made confidence.',
      'Avoid for dense enterprise dashboards or anything that must read as neutral and clinical.',
    ],
    rules: [
      'Palette ratio: about 55% warm paper ground (a cream tinted by the accent), 20% lighter paper surfaces, 10% accent, 10% retro pops (orange, teal, plum, pink), 5% warm black ink. Never pure white or pure black; ink is #161210 and paper is #fffaf0.',
      'Outlines are 2-3px warm black on every surface. Buttons have a downward key edge (0 offset-y hard shadow); cards have a diagonal hard shadow; featured cards add a second colored shadow. No blur anywhere.',
      'Typography: a heavy display face (Archivo Black, DM Serif Display, Fraunces or Syne) for headings and buttons, a friendly grotesque for body at weight 450-500. Buttons, badges and labels are uppercase with 0.04-0.14em tracking; headings stay sentence case, optionally with a layered offset text-shadow (paper, then orange) on the hero only.',
      'Decoration comes from CSS: sunset arcs or stripes (orange, yellow, teal, plum), halftone dots at low opacity, hazard-stripe alert edges, folder tabs, ticket-shaped badges. One decorative device per section, never all at once.',
      'Motion: 120ms ease-out presses. Buttons translate down by half the shadow on hover and the full shadow on press; switches slide. No bounces, no fades, no looping animations.',
      'Text on the accent is chosen by contrast. Focus rings are a 3px plum outline with offset; inputs get a double accent + ink ring.',
      'Do not use gradients other than the hard-stop sunset arcs and stripes, blurred shadows, glass, gray borders or thin hairlines, or more than four hues on one screen.',
    ],
  },
  perf: { webgl: false, maxDpr: 2 },
  a11y: { reducedMotion: 'static' },
  capture: { scroll: true, posterTime: 0.5, loop: 8 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'retroui',
      repo: 'Logging-Studio/RetroUI',
      sha: 'd5fbc0e823bb66575f5372c3df03ee43be45c91b',
      paths: ['app/global.css', 'components/retroui/Button.tsx', 'components/retroui/Card.tsx'],
      spdx: 'MIT',
      copyright: ['Copyright (c) 2024 Arif Hossain'],
    },
    modifications: [
      'Kept the upstream token idea (warm background, yellow primary, black borders, 4px-radius hard shadows, a separate heading font) but moved it into CSS variables scoped to a .rb-root element and driven by component props.',
      'Replaced the Next / base-ui / cva / Tailwind components with plain React primitives (button, card, field, badge, folder tabs, hazard-stripe alert, slider switch) in one CSS file.',
      'The button shadow is a downward key edge that shrinks on hover and press; cards get an optional second, colored shadow; the sunset arcs, halftone ground, ticket badges and record artwork are new and drawn with CSS gradients.',
      'The page ground is derived from the accent, the text on the accent is picked by contrast. Upstream decorative bitmaps (public/decor) are not used; fonts are self-hosted OFL families from the Motif font list.',
    ],
    assets: [],
  },
})
