import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'mesh-gradient',
  status: 'published',
  title: { 'zh-CN': '流动网格渐变', en: 'Mesh Gradient' },
  summary: {
    'zh-CN': '几团颜色沿各自的轨迹缓慢游动，被有机噪声和漩涡揉在一起。适合做首屏或整块区域的背景。',
    en: 'Color spots drift along their own paths, blended by organic noise and a gentle swirl. Made for hero and section backgrounds.',
  },
  kind: 'effect',
  category: 'background',
  tags: ['gradient', 'shader', 'webgl', 'hero', 'aurora'],
  runtime: ['react', 'webgl2'],
  entry: { file: 'mesh-gradient.tsx', export: 'MeshGradientBackground' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'mesh-gradient.tsx', role: 'component' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    {
      key: 'colors',
      type: 'palette',
      label: { 'zh-CN': '颜色', en: 'Colors' },
      hint: { 'zh-CN': '每个颜色是一团色块，最多 10 个', en: 'Each color is one moving spot, up to 10' },
      default: ['#e0eaff', '#241d9a', '#f75092', '#9f50d3'],
      minItems: 2,
      maxItems: 10,
    },
    {
      key: 'distortion',
      type: 'number',
      label: { 'zh-CN': '扭曲', en: 'Distortion' },
      hint: { 'zh-CN': '有机噪声扭曲的强度', en: 'Strength of the organic noise distortion' },
      default: 0.8,
      min: 0,
      max: 1,
      step: 0.01,
    },
    {
      key: 'swirl',
      type: 'number',
      label: { 'zh-CN': '漩涡', en: 'Swirl' },
      hint: { 'zh-CN': '漩涡扭曲的强度', en: 'Strength of the vortex distortion' },
      default: 0.1,
      min: 0,
      max: 1,
      step: 0.01,
    },
    {
      key: 'grainMixer',
      type: 'number',
      label: { 'zh-CN': '边缘颗粒', en: 'Edge grain' },
      hint: { 'zh-CN': '色块边缘的颗粒感', en: 'Grain distortion on the edges of the shapes' },
      default: 0,
      min: 0,
      max: 1,
      step: 0.01,
      group: 'grain',
    },
    {
      key: 'grainOverlay',
      type: 'number',
      label: { 'zh-CN': '颗粒叠加', en: 'Grain overlay' },
      hint: { 'zh-CN': '整体叠一层黑白胶片颗粒', en: 'Black-and-white film grain on top' },
      default: 0,
      min: 0,
      max: 1,
      step: 0.01,
      safe: [0, 0.5],
      group: 'grain',
    },
    {
      key: 'speed',
      type: 'number',
      label: { 'zh-CN': '速度', en: 'Speed' },
      default: 0.6,
      min: 0,
      max: 2,
      step: 0.01,
      safe: [0.1, 1.2],
      unit: 'x',
      group: 'motion',
    },
    {
      key: 'scale',
      type: 'number',
      label: { 'zh-CN': '缩放', en: 'Scale' },
      default: 1,
      min: 0.3,
      max: 3,
      step: 0.01,
      unit: 'x',
      group: 'layout',
    },
    {
      key: 'rotation',
      type: 'number',
      label: { 'zh-CN': '旋转', en: 'Rotation' },
      default: 0,
      min: 0,
      max: 360,
      step: 1,
      unit: 'deg',
      group: 'layout',
    },
  ],
  presets: [
    {
      id: 'ink',
      name: { 'zh-CN': '水墨', en: 'Ink' },
      values: { colors: ['#ffffff', '#000000'], distortion: 1, swirl: 0.2, rotation: 90, speed: 0.8 },
    },
    {
      id: 'violet',
      name: { 'zh-CN': '紫雾', en: 'Violet haze' },
      values: { colors: ['#aaa7d7', '#3c2b8e'], distortion: 1, swirl: 1, speed: 0.5 },
    },
    {
      id: 'lagoon',
      name: { 'zh-CN': '泻湖', en: 'Lagoon' },
      values: { colors: ['#bcecf6', '#00aaff', '#00f7ff', '#ffd447'], distortion: 0.8, swirl: 0.35, speed: 0.15 },
    },
    {
      id: 'nocturne',
      name: { 'zh-CN': '夜曲', en: 'Nocturne' },
      values: { colors: ['#07071a', '#2d1bff', '#ff3d8b', '#0b0b24', '#19d3c5'], distortion: 0.9, swirl: 0.45, grainOverlay: 0.12, speed: 0.4 },
    },
    {
      id: 'peach',
      name: { 'zh-CN': '蜜桃', en: 'Peach' },
      values: { colors: ['#fff1e6', '#ff9a76', '#ffd6e0', '#ffb347'], distortion: 0.7, swirl: 0.25, grainMixer: 0.2, speed: 0.35 },
    },
  ],
  dependencies: ['@paper-design/shaders-react', '@motif/runtime'],
  perf: { webgl: true, maxDpr: 2 },
  a11y: { reducedMotion: 'static' },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'paper-shaders',
      repo: 'paper-design/shaders',
      sha: '43cd68db79fa0b1759f72ffc941b3238e2a3954c',
      paths: ['packages/shaders-react/src/shaders/mesh-gradient.tsx', 'docs/src/shader-defs/mesh-gradient-def.ts'],
      spdx: 'Apache-2.0',
      copyright: ['Paper Shaders (https://shaders.paper.design)'],
    },
    modifications: [
      'Wrapped the Paper MeshGradient component as a full-bleed background that can hold children.',
      'Parameter ranges and the first three presets adapted from the Paper docs; defaults and the Nocturne and Peach presets are Motif’s.',
      'Renders a static frame when the user prefers reduced motion.',
    ],
    assets: [],
  },
})
