import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'sliding-number',
  status: 'published',
  title: { 'zh-CN': '滚动数字', en: 'Sliding Number' },
  summary: {
    'zh-CN': '数值变化时，每一位数字像里程表一样单独滚动到新值，方向跟随涨跌。适合营收、用户数、倒计时这类会实时更新的指标。',
    en: 'When the value changes, each digit rolls to its new value like an odometer, in the direction the number moved. For revenue, user counts and timers that update live.',
  },
  kind: 'component',
  category: 'data',
  tags: ['number', 'counter', 'odometer', 'digits', 'metric', 'spring'],
  runtime: ['react', 'motion'],
  entry: { file: 'sliding-number.tsx', export: 'SlidingNumber' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'sliding-number.tsx', role: 'component' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    {
      key: 'value',
      type: 'number',
      label: { 'zh-CN': '数值', en: 'Value' },
      hint: { 'zh-CN': '改一改，看数字滚动', en: 'Change it to watch the digits roll' },
      default: 12480,
      min: 0,
      max: 999999,
      step: 1,
    },
    { key: 'prefix', type: 'text', label: { 'zh-CN': '前缀', en: 'Prefix' }, default: '$', maxLength: 4 },
    { key: 'suffix', type: 'text', label: { 'zh-CN': '后缀', en: 'Suffix' }, default: '', maxLength: 4 },
    {
      key: 'minDigits',
      type: 'number',
      label: { 'zh-CN': '最少位数', en: 'Minimum digits' },
      hint: { 'zh-CN': '不足时在前面补 0，做倒计时很有用', en: 'Pads with leading zeros, handy for timers' },
      default: 1,
      min: 1,
      max: 8,
      step: 1,
    },
    { key: 'grouping', type: 'boolean', label: { 'zh-CN': '千位分隔', en: 'Thousands separator' }, default: true },
    {
      key: 'spring',
      type: 'spring',
      label: { 'zh-CN': '滚动弹簧', en: 'Roll spring' },
      hint: { 'zh-CN': '弹性越大，数字停下时越有回弹', en: 'More bounce makes digits settle with a wobble' },
      default: { visualDuration: 0.7, bounce: 0.2 },
      group: 'motion',
    },
  ],
  presets: [
    { id: 'ledger', name: { 'zh-CN': '账本', en: 'Ledger' }, values: { value: 12480, prefix: '$', suffix: '', grouping: true, spring: { visualDuration: 0.7, bounce: 0.2 } } },
    { id: 'clock', name: { 'zh-CN': '钟表', en: 'Clock' }, values: { value: 45, prefix: '', suffix: '', minDigits: 2, grouping: false, spring: { visualDuration: 0.5, bounce: 0 } } },
    { id: 'arcade', name: { 'zh-CN': '街机', en: 'Arcade' }, values: { value: 98650, prefix: '', suffix: ' pts', minDigits: 6, grouping: false, spring: { visualDuration: 0.9, bounce: 0.45 } } },
    { id: 'growth', name: { 'zh-CN': '增长', en: 'Growth' }, values: { value: 128, prefix: '', suffix: '%', grouping: false, spring: { visualDuration: 0.6, bounce: 0.1 } } },
  ],
  dependencies: ['motion/react', '@motif/runtime'],
  perf: { webgl: false, maxDpr: 2 },
  a11y: { reducedMotion: 'static' },
  capture: { zoom: 1.7, posterTime: 5.95, loop: 8 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'motion-primitives',
      repo: 'ibelick/motion-primitives',
      sha: '120f64f6ca60348e251f929e9c81f11ccbe45eda',
      paths: ['components/core/sliding-number.tsx'],
      spdx: 'MIT',
      copyright: ['Copyright (c) 2024 ibelick'],
    },
    modifications: [
      'framer-motion imports moved to motion/react; react-use-measure was dropped, digits are positioned with percentage translations of their own line height instead of measured pixels.',
      'Each digit now rolls the short way in the direction the value moved (upstream spins through every digit in between), and the spring is described with visualDuration and bounce.',
      'Added prefix, suffix, minimum digits and thousands separators; padStart became minDigits.',
      'Added reduced-motion handling (upstream has none): digits jump straight to the new value.',
      'Defaults moved into the generated defaults region.',
    ],
    assets: [],
  },
})
