import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'devfolio-site',
  status: 'published',
  title: { 'zh-CN': '开发者作品集', en: 'Devfolio' },
  summary: {
    'zh-CN': '一页式开发者作品集：主色晕染的首屏配代码卡片，接着是简介、经历时间线、编号项目卡和联系区。浅色干净，深色也成立，主色一换整站跟着变。',
    en: 'A one-page developer portfolio: an accent-washed hero with a floating code card, then about, an experience timeline, numbered project cards and a contact block. Clean in light, sharp in dark, and one accent color re-themes it all.',
  },
  kind: 'template',
  category: 'portfolio',
  tags: ['portfolio', 'developer', 'one-page', 'timeline', 'resume', 'responsive'],
  runtime: ['react', 'motion'],
  entry: { file: 'devfolio-site.tsx', export: 'DevfolioSite' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'light' },
  files: [
    { path: 'devfolio-site.tsx', role: 'component' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    { key: 'name', type: 'text', label: { 'zh-CN': '姓名 / 品牌', en: 'Name / brand' }, hint: { 'zh-CN': '首屏大标题，也用于页眉缩写和页脚', en: 'Hero title, header monogram and footer' }, default: 'Iris Calder', maxLength: 28, group: 'content' },
    { key: 'headline', type: 'text', label: { 'zh-CN': '首屏标题文案', en: 'Headline' }, default: 'Systems engineer building fast, quiet developer tools.', maxLength: 90, group: 'content' },
    { key: 'accent', type: 'color', label: { 'zh-CN': '主色', en: 'Accent' }, hint: { 'zh-CN': '按钮、时间线、高亮和背景晕染都从它推出来', en: 'Buttons, timeline, highlights and the hero wash all derive from it' }, default: '#0f9d6e', group: 'look' },
    {
      key: 'fontPair',
      type: 'select',
      label: { 'zh-CN': '字体搭配', en: 'Font pairing' },
      default: 'grotesk',
      options: [
        { value: 'grotesk', label: { 'zh-CN': 'Space Grotesk + Inter Tight', en: 'Space Grotesk + Inter Tight' } },
        { value: 'geist', label: { 'zh-CN': 'Geist + Geist Mono', en: 'Geist + Geist Mono' } },
        { value: 'plex', label: { 'zh-CN': 'IBM Plex', en: 'IBM Plex' } },
        { value: 'bricolage', label: { 'zh-CN': 'Bricolage + Manrope', en: 'Bricolage + Manrope' } },
      ],
      group: 'look',
    },
    { key: 'radius', type: 'number', label: { 'zh-CN': '圆角', en: 'Corner radius' }, default: 14, min: 0, max: 28, step: 1, unit: 'px', safe: [6, 22], group: 'look' },
    { key: 'dark', type: 'boolean', label: { 'zh-CN': '深色模式', en: 'Dark mode' }, default: false, group: 'look' },
    { key: 'animate', type: 'boolean', label: { 'zh-CN': '入场动画', en: 'Entrance animation' }, hint: { 'zh-CN': '首屏依次淡入，其余区块滚动到时淡入', en: 'Hero staggers in, the rest fade in on scroll' }, default: true, group: 'motion' },
  ],
  presets: [
    { id: 'terminal-green', name: { 'zh-CN': '终端绿', en: 'Terminal Green' }, values: { accent: '#0f9d6e', fontPair: 'grotesk', radius: 14, dark: false } },
    { id: 'midnight-build', name: { 'zh-CN': '夜间构建', en: 'Midnight Build' }, values: { accent: '#7c8cff', fontPair: 'geist', radius: 10, dark: true } },
    { id: 'ember-shell', name: { 'zh-CN': '余烬', en: 'Ember Shell' }, values: { accent: '#e8590c', fontPair: 'bricolage', radius: 20, dark: false } },
    { id: 'plex-mono', name: { 'zh-CN': '等宽夜色', en: 'Plex Night' }, values: { accent: '#3fc1a5', fontPair: 'plex', radius: 4, dark: true } },
  ],
  dependencies: ['motion/react', '@motif/runtime'],
  fonts: ['Space Grotesk Variable', 'Inter Tight Variable', 'JetBrains Mono Variable', 'Geist Variable', 'Geist Mono Variable', 'IBM Plex Sans Variable', 'IBM Plex Mono', 'Bricolage Grotesque Variable', 'Manrope Variable'],
  guidance: {
    use: [
      'A single-page personal site for a software engineer or maintainer: hero, about, experience, projects, education, contact.',
      'Adapt it by replacing the arrays at the top of the component (NAV, STATS, JOBS, PROJECTS, SCHOOLS) and the name/headline params; keep section order and rhythm.',
    ],
    rules: [
      'All colors derive from the accent and the dark flag in themeVars(); never hard-code a second brand color. Use the CSS variables (--accent, --fg, --mut, --line, --card, --bg-alt).',
      'Keep one accent color. Surfaces alternate between --bg and --bg-alt; cards are --card with a 1px --line border and no heavy shadows except on hover.',
      'Headings use the head font, body copy the body font, and only labels, dates, chips and code use the mono font.',
      'Project covers are generated from gradients and SVG; do not add photographs or screenshots. Company and school names must stay fictional.',
      'Copy stays concrete: real-sounding numbers, verbs, no slogans. Keep bullets to one sentence.',
      'Section titles use the sticky left column on lg screens; on phones everything stacks in one column at 20px gutters.',
    ],
  },
  perf: { webgl: false, maxDpr: 2 },
  a11y: { reducedMotion: 'static' },
  capture: { scroll: true, posterTime: 0.5, loop: 8 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'devportfolio',
      repo: 'RyanFitzgerald/devportfolio',
      sha: '852d650fb0a8cf0c98f874af5a56a0a9b7d7d4b7',
      paths: [
        'src/pages/index.astro',
        'src/components/Header.astro',
        'src/components/Hero.astro',
        'src/components/About.astro',
        'src/components/Experience.astro',
        'src/components/Projects.astro',
        'src/components/Education.astro',
        'src/components/Footer.astro',
      ],
      spdx: 'MIT',
      copyright: ['Copyright (c) 2025 Ryan Fitzgerald'],
    },
    modifications: [
      'Astro components rewritten as a single React 19 + Tailwind v4 component; section order, the accent bar headings, the numbered project cards and the timeline are kept.',
      'All personal content replaced with an invented engineer, companies and projects; the emoji greeting was dropped.',
      'The hero gets a floating code card, and project cards get generated gradient covers (no images).',
      'Theming is driven by accent, font pairing, radius and a dark flag through CSS variables instead of the upstream config file.',
      'Entrance animations use motion (whileInView) and respect prefers-reduced-motion.',
    ],
    assets: [],
  },
})
