import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'gem-smoke',
  status: 'published',
  title: { 'zh-CN': '宝石烟雾', en: 'Gem Smoke' },
  summary: {
    'zh-CN': '一颗宝石形的轮廓里翻涌着彩色烟雾，边缘透出辉光，像一团被封在水晶里的火。形状可以是菱形、圆、雏菊或融球，颜色从火焰、荧光到红外都能调。',
    en: 'Coloured smoke churns inside a gem-shaped outline with light glowing through its edges, like fire sealed in crystal. The shape can be a diamond, circle, daisy or metaballs, and the colours range from flame to fluorescent to infrared.',
  },
  kind: 'effect',
  category: 'shader',
  tags: ['smoke', 'gem', 'glow', 'fire', 'webgl', 'shader', 'paper'],
  runtime: ['react', 'webgl2'],
  entry: { file: 'gem-smoke.tsx', export: 'GemSmokeShape' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'gem-smoke.tsx', role: 'component' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    {
      key: 'shape',
      type: 'select',
      group: 'shape',
      label: { 'zh-CN': '形状', en: 'Shape' },
      default: 'diamond',
      options: [
        { value: 'diamond', label: { 'zh-CN': '菱形', en: 'Diamond' } },
        { value: 'circle', label: { 'zh-CN': '圆', en: 'Circle' } },
        { value: 'daisy', label: { 'zh-CN': '雏菊', en: 'Daisy' } },
        { value: 'metaballs', label: { 'zh-CN': '融球', en: 'Metaballs' } },
      ],
    },
    { key: 'colors', type: 'palette', group: 'color', label: { 'zh-CN': '烟雾颜色', en: 'Smoke' }, default: ['#fe5b16', '#f7ff61', '#ffffff'], minItems: 2, maxItems: 6 },
    { key: 'colorBack', type: 'color', group: 'color', label: { 'zh-CN': '背景', en: 'Background' }, default: '#000000' },
    { key: 'colorInner', type: 'color', group: 'color', label: { 'zh-CN': '内部底色', en: 'Inner colour' }, default: '#000000' },
    { key: 'innerGlow', type: 'number', group: 'shape', label: { 'zh-CN': '内发光', en: 'Inner glow' }, default: 0.65, min: 0, max: 1, step: 0.01 },
    { key: 'outerGlow', type: 'number', group: 'shape', label: { 'zh-CN': '外发光', en: 'Outer glow' }, default: 1, min: 0, max: 1, step: 0.01 },
    { key: 'innerDistortion', type: 'number', group: 'shape', label: { 'zh-CN': '内部翻涌', en: 'Inner churn' }, default: 0.6, min: 0, max: 1, step: 0.01 },
    { key: 'outerDistortion', type: 'number', group: 'shape', label: { 'zh-CN': '边缘扰动', en: 'Edge churn' }, default: 0.8, min: 0, max: 1, step: 0.01 },
    { key: 'offset', type: 'number', group: 'shape', label: { 'zh-CN': '色带偏移', en: 'Colour offset' }, default: 0, min: -1, max: 1, step: 0.01, safe: [-0.5, 0.5] },
    { key: 'angle', type: 'number', group: 'shape', label: { 'zh-CN': '角度', en: 'Angle' }, default: 0, min: 0, max: 360, step: 1, unit: 'deg' },
    { key: 'size', type: 'number', group: 'shape', label: { 'zh-CN': '烟雾范围', en: 'Smoke size' }, default: 0.8, min: 0.2, max: 1, step: 0.01 },
    { key: 'scale', type: 'number', group: 'shape', label: { 'zh-CN': '大小', en: 'Scale' }, default: 0.6, min: 0.3, max: 1, step: 0.01, safe: [0.45, 0.85] },
    { key: 'speed', type: 'number', group: 'motion', label: { 'zh-CN': '速度', en: 'Speed' }, default: 1, min: 0, max: 3, step: 0.05, unit: 'x', safe: [0.3, 2] },
  ],
  presets: [
    { id: 'fire', name: { 'zh-CN': '火焰', en: 'Fire' }, values: {} },
    { id: 'fluorescent', name: { 'zh-CN': '荧光', en: 'Fluorescent' }, values: { colors: ['#2fb64c', '#cdff61', '#ffffff'], outerGlow: 0, innerGlow: 1, innerDistortion: 1 } },
    { id: 'pearl', name: { 'zh-CN': '珍珠', en: 'Pearl' }, values: { colorBack: '#f0efea', colorInner: '#fafaf5', colors: ['#333333', '#e7e6df'], outerGlow: 0.55, innerGlow: 1, innerDistortion: 0.8, outerDistortion: 0.6 } },
    { id: 'infrared', name: { 'zh-CN': '红外', en: 'Infrared' }, values: { colorBack: '#cd28dc', colorInner: '#00000000', colors: ['#ff9900', '#fff67a', '#dcff52', '#00ffbb', '#0077ff'], outerGlow: 1, innerGlow: 1, innerDistortion: 1, outerDistortion: 1, offset: 0.2, size: 1, speed: 0.5 } },
  ],
  dependencies: ['@motif/runtime', '@paper-design/shaders-react'],
  fonts: [],
  perf: { webgl: true, maxDpr: 2 },
  a11y: { reducedMotion: 'static' },
  guidance: {
    use: ['A centrepiece for a launch, an AI or energy product, or a loading moment that should feel precious. One per view.'],
    rules: [
      'Keep it as the only animated focal point; it competes with anything else that moves.',
      'Pair dark backgrounds with bright smoke (Fire, Fluorescent), light backgrounds with grey smoke (Pearl).',
    ],
  },
  capture: { posterTime: 2.2, loop: 8 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'paper-shaders',
      repo: 'paper-design/shaders',
      sha: '43cd68db79fa0b1759f72ffc941b3238e2a3954c',
      paths: ['packages/shaders-react/src/shaders/gem-smoke.tsx', 'docs/src/shader-defs/gem-smoke-def.ts'],
      spdx: 'Apache-2.0',
      copyright: ['Paper Shaders (https://shaders.paper.design)'],
    },
    modifications: [
      'Wrapped the Paper GemSmoke component as a full-bleed panel that can hold children; the image mask is not exposed, only the built-in shapes.',
      'Parameter ranges adapted from the Paper docs; Fire (default), Fluorescent, Pearl (upstream Default) and Infrared follow the upstream presets.',
      'Renders a static frame when the user prefers reduced motion.',
    ],
    assets: [],
  },
})
