import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'pricing-three-tier',
  status: 'published',
  title: { 'zh-CN': '三档定价', en: 'Three-Tier Pricing' },
  summary: {
    'zh-CN': '月付 / 年付切换、价格数字上滚更新的三档定价。推荐档抬高并带主色渐变描边，其余两档保持安静，一眼就知道该选哪个。',
    en: 'Three plans with a monthly/yearly switch and prices that roll to their new value. The recommended tier stands taller with an accent gradient border while the others stay quiet.',
  },
  kind: 'section',
  category: 'pricing',
  tags: ['pricing', 'plans', 'toggle', 'billing', 'saas', 'launch ui'],
  runtime: ['react', 'motion', 'css'],
  entry: { file: 'pricing-three-tier.tsx', export: 'PricingThreeTier' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'pricing-three-tier.tsx', role: 'component' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    { key: 'heading', type: 'text', label: { 'zh-CN': '标题', en: 'Heading' }, default: 'Pricing that scales with the work, not the seats', maxLength: 70, group: 'content' },
    {
      key: 'subline',
      type: 'text',
      label: { 'zh-CN': '副标题', en: 'Subline' },
      default: 'Start free, upgrade when a project goes live. No per-seat fees on any plan.',
      maxLength: 130,
      group: 'content',
    },
    {
      key: 'currency',
      type: 'select',
      label: { 'zh-CN': '货币符号', en: 'Currency' },
      default: '$',
      options: [
        { value: '$', label: { 'zh-CN': '$ 美元', en: '$ Dollar' } },
        { value: '€', label: { 'zh-CN': '€ 欧元', en: '€ Euro' } },
        { value: '£', label: { 'zh-CN': '£ 英镑', en: '£ Pound' } },
        { value: '¥', label: { 'zh-CN': '¥ 元', en: '¥ Yuan' } },
      ],
      group: 'content',
    },
    {
      key: 'billing',
      type: 'select',
      label: { 'zh-CN': '默认计费周期', en: 'Default billing' },
      default: 'monthly',
      options: [
        { value: 'monthly', label: { 'zh-CN': '月付', en: 'Monthly' } },
        { value: 'yearly', label: { 'zh-CN': '年付', en: 'Yearly' } },
      ],
      group: 'pricing',
    },
    { key: 'discount', type: 'number', label: { 'zh-CN': '年付折扣', en: 'Yearly discount' }, default: 20, min: 5, max: 40, step: 5, unit: '%', safe: [10, 30], group: 'pricing' },
    {
      key: 'highlight',
      type: 'select',
      label: { 'zh-CN': '推荐档', en: 'Highlighted tier' },
      hint: { 'zh-CN': '只能有一档被高亮', en: 'Only one tier can be highlighted' },
      default: 'pro',
      options: [
        { value: 'starter', label: { 'zh-CN': 'Starter', en: 'Starter' } },
        { value: 'pro', label: { 'zh-CN': 'Pro', en: 'Pro' } },
        { value: 'team', label: { 'zh-CN': 'Team', en: 'Team' } },
      ],
      group: 'pricing',
    },
    { key: 'accent', type: 'color', label: { 'zh-CN': '主色', en: 'Accent color' }, default: '#6d7dff', group: 'look' },
    {
      key: 'tone',
      type: 'select',
      label: { 'zh-CN': '明暗', en: 'Tone' },
      default: 'dark',
      options: [
        { value: 'dark', label: { 'zh-CN': '深色', en: 'Dark' } },
        { value: 'light', label: { 'zh-CN': '浅色', en: 'Light' } },
      ],
      group: 'look',
    },
    {
      key: 'font',
      type: 'select',
      label: { 'zh-CN': '标题字体', en: 'Heading font' },
      default: 'geist',
      options: [
        { value: 'geist', label: { 'zh-CN': 'Geist 无衬线', en: 'Geist sans' } },
        { value: 'grotesk', label: { 'zh-CN': 'Space Grotesk', en: 'Space Grotesk' } },
        { value: 'serif', label: { 'zh-CN': 'Instrument 衬线', en: 'Instrument serif' } },
      ],
      group: 'look',
    },
    { key: 'radius', type: 'number', label: { 'zh-CN': '卡片圆角', en: 'Card radius' }, default: 22, min: 0, max: 32, step: 1, unit: 'px', safe: [8, 28], group: 'look' },
  ],
  presets: [
    { id: 'indigo-night', name: { 'zh-CN': '靛夜', en: 'Indigo Night' }, values: {} },
    { id: 'emerald-ledger', name: { 'zh-CN': '翠账', en: 'Emerald Ledger' }, values: { accent: '#10b981', billing: 'yearly', highlight: 'team', font: 'grotesk' } },
    { id: 'cream', name: { 'zh-CN': '奶油', en: 'Cream' }, values: { tone: 'light', accent: '#e4572e', font: 'serif', radius: 16, currency: '€' } },
  ],
  dependencies: ['motion/react', '@motif/runtime'],
  fonts: ['Geist Variable', 'Space Grotesk Variable', 'Instrument Serif'],
  guidance: {
    use: ['Use on a dedicated pricing page or as the pricing block of a landing page for a product with three plans.'],
    rules: [
      'Exactly one tier is highlighted (accent gradient border, filled button, taller card). Never highlight two.',
      'Keep three tiers with a free or lowest entry tier first; feature lists of 4 to 5 short lines, the same rhythm across cards.',
      'Yearly prices are the monthly price minus the discount, rounded; show the yearly total under the price.',
      'Buttons are the only accent-filled element besides the highlighted card; do not color the other tiers.',
    ],
  },
  perf: { webgl: false, maxDpr: 2 },
  a11y: { reducedMotion: 'static' },
  capture: { scroll: true, posterTime: 1, loop: 8 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'launch-ui',
      repo: 'launch-ui/launch-ui',
      sha: 'b0d4d5bce91d13523450416ce1797109076b2787',
      paths: ['components/sections/pricing/default.tsx', 'components/ui/pricing-column.tsx'],
      spdx: 'MIT',
      copyright: ['Copyright (c) 2024 Mikolaj Dobrucki'],
    },
    modifications: [
      'Kept the idea of a plan-column layout with one highlighted column; the component, copy and plans were rewritten.',
      'Added a monthly/yearly switch with a sliding thumb and rolling price digits, an accent gradient border for the highlighted tier, tone and font params.',
      'Radix Slot, lucide icons and the site config were replaced by inline SVG and plain elements; the switch and price animation respect reduced motion.',
    ],
    assets: [],
  },
})
