import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'swirl',
  status: 'published',
  title: { "zh-CN": '螺旋色带', en: 'Swirl' },
  summary: {
    "zh-CN": '色带从中心向外旋转展开，像万花筒或旋转的糖纸。适合做活泼的背景或转场底图。',
    en: 'Bands of color unfurl outward from the center like a kaleidoscope or spinning candy wrapper. A lively backdrop or transition base.',
  },
  kind: 'effect',
  category: 'background',
  tags: ['swirl', 'spiral', 'bands', 'shader', 'webgl', 'background'],
  runtime: ['react', 'webgl2'],
  entry: { file: 'swirl.tsx', export: 'SwirlBackground' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'swirl.tsx', role: 'component' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    {
      key: 'colors',
      type: 'palette',
      label: { "zh-CN": '颜色', en: 'Colors' },
      hint: { "zh-CN": '色带的颜色，依次循环', en: 'Band colors, cycled in order' },
      default: ['#ffd1d1', '#ff8a8a', '#660000'],
      minItems: 1,
      maxItems: 10,
    },
    { key: 'colorBack', type: 'color', label: { "zh-CN": '底色', en: 'Background' }, default: '#330000' },
    {
      key: 'bandCount',
      type: 'number',
      label: { "zh-CN": '色带数量', en: 'Bands' },
      default: 4,
      min: 1,
      max: 12,
      step: 1,
      group: 'look',
    },
    {
      key: 'twist',
      type: 'number',
      label: { "zh-CN": '扭转', en: 'Twist' },
      default: 0.1,
      min: 0,
      max: 1,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'center',
      type: 'number',
      label: { "zh-CN": '中心', en: 'Center' },
      hint: { "zh-CN": '中心区域的宽度', en: 'Width of the center area' },
      default: 0.2,
      min: 0,
      max: 1,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'proportion',
      type: 'number',
      label: { "zh-CN": '比例', en: 'Proportion' },
      default: 0.5,
      min: 0,
      max: 1,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'softness',
      type: 'number',
      label: { "zh-CN": '柔和度', en: 'Softness' },
      default: 0,
      min: 0,
      max: 1,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'noise',
      type: 'number',
      label: { "zh-CN": '噪声', en: 'Noise' },
      default: 0.2,
      min: 0,
      max: 1,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'speed',
      type: 'number',
      label: { "zh-CN": '速度', en: 'Speed' },
      default: 0.32,
      min: 0,
      max: 2,
      step: 0.01,
      safe: [0.05, 1.2],
      unit: 'x',
      group: 'motion',
    },
  ],
  presets: [
    {
      id: 'rose',
      name: { "zh-CN": '玫瑰', en: 'Rose' },
      values: {
        colors: ['#ffd1d1', '#ff8a8a', '#660000'],
        colorBack: '#330000',
        bandCount: 4,
        twist: 0.1,
        center: 0.2,
        proportion: 0.5,
        softness: 0,
        noise: 0.2,
        speed: 0.32,
      },
    },
    {
      id: 'candy',
      name: { "zh-CN": '糖纸', en: 'Candy' },
      values: {
        colors: ['#6bbceb', '#d7b3ff', '#ff9fff'],
        colorBack: '#ffcd66',
        bandCount: 2,
        twist: 0.15,
        center: 0.2,
        proportion: 0.5,
        softness: 1,
        noise: 0,
        speed: 0.6,
      },
    },
    {
      id: '007',
      name: { "zh-CN": '007', en: '007' },
      values: {
        colors: ['#000000'],
        colorBack: '#e9e7da',
        bandCount: 5,
        twist: 0.3,
        center: 0,
        proportion: 0,
        softness: 0,
        noise: 0,
        speed: 0.6,
      },
    },
    {
      id: 'nocturne',
      name: { "zh-CN": '夜曲', en: 'Nocturne' },
      values: {
        colors: ['#7c5cff', '#22d3ee', '#f472b6'],
        colorBack: '#050816',
        bandCount: 3,
        twist: 0.25,
        center: 0.3,
        proportion: 0.55,
        softness: 0.6,
        noise: 0.15,
        speed: 0.3,
      },
    },
  ],
  dependencies: ['@paper-design/shaders-react', '@motif/runtime'],
  perf: { webgl: true, maxDpr: 1.5 },
  a11y: { reducedMotion: 'static' },
  capture: { posterTime: 2 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'paper-shaders',
      repo: 'paper-design/shaders',
      sha: '43cd68db79fa0b1759f72ffc941b3238e2a3954c',
      paths: ['packages/shaders-react/src/shaders/swirl.tsx', 'docs/src/shader-defs/swirl-def.ts'],
      spdx: 'Apache-2.0',
      copyright: ['Paper Shaders (https://shaders.paper.design)'],
    },
    modifications: ['Wrapped the Paper Swirl component as a full-bleed background that can hold children.', 'Parameter ranges adapted from the Paper docs; Rose (default), Candy and 007 follow the upstream presets (speed and noise frequency adjusted); Nocturne is Motif’s.', 'Renders a static frame when the user prefers reduced motion.'],
    assets: [],
  },
})
