import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'liquid-metal',
  status: 'published',
  title: { 'zh-CN': '液态金属', en: 'Liquid Metal' },
  summary: {
    'zh-CN': '把一个字母、一个词或一个形状变成会流动的镀铬：条纹沿着轮廓流过，边缘带一点色散。文字现场在 Canvas 上画出来再当遮罩，不需要任何图片素材；也可以换成圆、雏菊、菱形和融球。',
    en: 'Turns a letter, a word or a shape into flowing chrome: stripes run along the outline with a touch of colour dispersion at the edges. The text is drawn on a canvas and used as the mask, so no image assets are needed; circle, daisy, diamond and metaballs shapes are built in.',
  },
  kind: 'effect',
  category: 'shader',
  tags: ['liquid metal', 'chrome', 'logo', 'text', 'webgl', 'shader', 'paper'],
  runtime: ['react', 'webgl2', 'canvas2d'],
  entry: { file: 'liquid-metal.tsx', export: 'LiquidMetalMark' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'liquid-metal.tsx', role: 'component' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    {
      key: 'mark',
      type: 'select',
      group: 'content',
      label: { 'zh-CN': '图形', en: 'Mark' },
      default: 'text',
      options: [
        { value: 'text', label: { 'zh-CN': '文字', en: 'Text' } },
        { value: 'circle', label: { 'zh-CN': '圆', en: 'Circle' } },
        { value: 'daisy', label: { 'zh-CN': '雏菊', en: 'Daisy' } },
        { value: 'diamond', label: { 'zh-CN': '菱形', en: 'Diamond' } },
        { value: 'metaballs', label: { 'zh-CN': '融球', en: 'Metaballs' } },
      ],
    },
    { key: 'text', type: 'text', group: 'content', label: { 'zh-CN': '文字', en: 'Text' }, hint: { 'zh-CN': '一个字母或一个短词效果最好', en: 'A single letter or a short word works best' }, default: 'M', maxLength: 6 },
    {
      key: 'font',
      type: 'select',
      group: 'content',
      label: { 'zh-CN': '字体', en: 'Font' },
      default: 'archivo',
      options: [
        { value: 'archivo', label: { 'zh-CN': '粗黑', en: 'Heavy' } },
        { value: 'syne', label: { 'zh-CN': '宽体', en: 'Wide' } },
        { value: 'serif', label: { 'zh-CN': '衬线', en: 'Serif' } },
      ],
    },
    { key: 'colorBack', type: 'color', group: 'color', label: { 'zh-CN': '背景', en: 'Background' }, default: '#0c0c0e' },
    { key: 'colorTint', type: 'color', group: 'color', label: { 'zh-CN': '染色', en: 'Tint' }, hint: { 'zh-CN': '用颜色加深混合叠在金属上', en: 'Laid over the metal with colour burn' }, default: '#ffffff' },
    { key: 'repetition', type: 'number', group: 'shape', label: { 'zh-CN': '条纹密度', en: 'Stripes' }, default: 2, min: 1, max: 10, step: 0.1, safe: [1.5, 6] },
    { key: 'softness', type: 'number', group: 'shape', label: { 'zh-CN': '柔和', en: 'Softness' }, hint: { 'zh-CN': '0 是硬边，1 是平滑渐变', en: '0 is a hard edge, 1 a smooth gradient' }, default: 0.1, min: 0, max: 1, step: 0.01, safe: [0, 0.8] },
    { key: 'shiftRed', type: 'number', group: 'shape', label: { 'zh-CN': '红色偏移', en: 'Red shift' }, default: 0.3, min: -1, max: 1, step: 0.01 },
    { key: 'shiftBlue', type: 'number', group: 'shape', label: { 'zh-CN': '蓝色偏移', en: 'Blue shift' }, default: 0.3, min: -1, max: 1, step: 0.01 },
    { key: 'distortion', type: 'number', group: 'shape', label: { 'zh-CN': '扰动', en: 'Distortion' }, default: 0.07, min: 0, max: 1, step: 0.01, safe: [0, 0.5] },
    { key: 'contour', type: 'number', group: 'shape', label: { 'zh-CN': '轮廓', en: 'Contour' }, hint: { 'zh-CN': '条纹沿边缘弯曲的程度', en: 'How strongly the stripes bend along the edges' }, default: 0.4, min: 0, max: 1, step: 0.01 },
    { key: 'angle', type: 'number', group: 'motion', label: { 'zh-CN': '流向', en: 'Flow angle' }, default: 70, min: 0, max: 360, step: 1, unit: 'deg' },
    { key: 'scale', type: 'number', group: 'shape', label: { 'zh-CN': '大小', en: 'Size' }, default: 0.6, min: 0.2, max: 1.2, step: 0.01, safe: [0.4, 0.9] },
    { key: 'speed', type: 'number', group: 'motion', label: { 'zh-CN': '速度', en: 'Speed' }, default: 1, min: 0, max: 3, step: 0.05, unit: 'x', safe: [0.3, 2] },
  ],
  presets: [
    { id: 'chrome', name: { 'zh-CN': '镀铬', en: 'Chrome' }, values: {} },
    { id: 'noir', name: { 'zh-CN': '暗夜', en: 'Noir' }, values: { colorBack: '#000000', colorTint: '#606060', softness: 0.45, repetition: 1.5, shiftRed: 0, shiftBlue: 0, distortion: 0, contour: 0, angle: 90 } },
    { id: 'gilded', name: { 'zh-CN': '鎏金', en: 'Gilded' }, values: { font: 'serif', text: 'Aa', colorBack: '#140f08', colorTint: '#e8b04a', softness: 0.25, shiftRed: 0.15, shiftBlue: -0.2, contour: 0.55 } },
    { id: 'stripes', name: { 'zh-CN': '条纹', en: 'Stripes' }, values: { mark: 'circle', colorBack: '#000000', colorTint: '#2c5d72', softness: 0.8, repetition: 6, shiftRed: 1, shiftBlue: -1, distortion: 0.4, contour: 0.4, angle: 0 } },
  ],
  dependencies: ['@motif/runtime', '@paper-design/shaders-react'],
  fonts: ['Archivo Black', 'Syne Variable', 'DM Serif Display'],
  perf: { webgl: true, maxDpr: 2 },
  a11y: { reducedMotion: 'static' },
  guidance: {
    use: ['A hero mark, a launch or event title, or a product logo moment. One per view: it is a centrepiece, not a texture.'],
    rules: [
      'Keep the text to one letter or one short word in a heavy face; thin strokes lose the chrome stripes.',
      'The mark is decorative: put the real name in accessible text nearby (or aria-label on the container).',
      'A transparent-background PNG logo also works as the image prop if you swap the canvas mark for your own asset.',
    ],
  },
  capture: { posterTime: 2.6, loop: 8 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'paper-shaders',
      repo: 'paper-design/shaders',
      sha: '43cd68db79fa0b1759f72ffc941b3238e2a3954c',
      paths: ['packages/shaders-react/src/shaders/liquid-metal.tsx', 'docs/src/shader-defs/liquid-metal-def.ts'],
      spdx: 'Apache-2.0',
      copyright: ['Paper Shaders (https://shaders.paper.design)'],
    },
    modifications: [
      'The mask is a text mark drawn on a canvas at runtime (trimmed to the glyphs), so the item needs no image assets; the upstream shapes stay available.',
      'Parameter ranges adapted from the Paper docs; Noir and Stripes follow the upstream presets, Chrome darkens the upstream default background, Gilded is Motif’s.',
      'Renders a static frame when the user prefers reduced motion.',
    ],
    assets: [],
  },
})
