import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'text-animate',
  status: 'published',
  title: { 'zh-CN': '文字入场', en: 'Text Animate' },
  summary: {
    'zh-CN': '文字按词、按字或整段依次入场，十种动画可选：模糊上浮、滑入、缩放等。适合首屏标题、章节标题和引言。',
    en: 'Text that enters word by word, letter by letter or all at once, with ten animations from blur-rise to slide and scale. Made for hero headlines, section titles and pull quotes.',
  },
  category: 'text',
  tags: ['text', 'stagger', 'reveal', 'headline', 'blur', 'typography'],
  runtime: ['react', 'motion'],
  entry: { file: 'text-animate.tsx', export: 'TextAnimate' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'text-animate.tsx', role: 'component' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    { key: 'text', type: 'text', label: { 'zh-CN': '文案', en: 'Text' }, default: 'Type that arrives with intent', maxLength: 80, group: 'content' },
    {
      key: 'animation',
      type: 'select',
      label: { 'zh-CN': '动画', en: 'Animation' },
      default: 'blurInUp',
      options: [
        { value: 'blurInUp', label: { 'zh-CN': '模糊上浮', en: 'Blur in up' } },
        { value: 'blurInDown', label: { 'zh-CN': '模糊下落', en: 'Blur in down' } },
        { value: 'blurIn', label: { 'zh-CN': '模糊淡入', en: 'Blur in' } },
        { value: 'fadeIn', label: { 'zh-CN': '淡入上移', en: 'Fade in' } },
        { value: 'slideUp', label: { 'zh-CN': '上滑', en: 'Slide up' } },
        { value: 'slideDown', label: { 'zh-CN': '下滑', en: 'Slide down' } },
        { value: 'slideLeft', label: { 'zh-CN': '左滑', en: 'Slide left' } },
        { value: 'slideRight', label: { 'zh-CN': '右滑', en: 'Slide right' } },
        { value: 'scaleUp', label: { 'zh-CN': '放大弹入', en: 'Scale up' } },
        { value: 'scaleDown', label: { 'zh-CN': '缩小落定', en: 'Scale down' } },
      ],
      group: 'motion',
    },
    {
      key: 'by',
      type: 'select',
      label: { 'zh-CN': '拆分方式', en: 'Split by' },
      default: 'word',
      options: [
        { value: 'word', label: { 'zh-CN': '按词', en: 'Word' } },
        { value: 'character', label: { 'zh-CN': '按字', en: 'Character' } },
        { value: 'text', label: { 'zh-CN': '整段', en: 'Whole text' } },
      ],
      group: 'motion',
    },
    { key: 'duration', type: 'number', label: { 'zh-CN': '单段时长', en: 'Segment duration' }, default: 0.6, min: 0.1, max: 2, step: 0.05, unit: 's', safe: [0.3, 1], group: 'motion' },
    { key: 'spread', type: 'number', label: { 'zh-CN': '错开总时长', en: 'Stagger spread' }, hint: { 'zh-CN': '从第一段到最后一段开始入场之间的时间', en: 'Time between the first and last segment starting' }, default: 0.6, min: 0, max: 3, step: 0.05, unit: 's', safe: [0.2, 1.4], group: 'motion' },
    { key: 'delay', type: 'number', label: { 'zh-CN': '延迟', en: 'Delay' }, default: 0, min: 0, max: 3, step: 0.05, unit: 's', group: 'motion' },
    { key: 'startOnView', type: 'boolean', label: { 'zh-CN': '进入视口时触发', en: 'Start in viewport' }, default: false, group: 'trigger' },
  ],
  presets: [
    { id: 'blur-rise', name: { 'zh-CN': '雾中浮起', en: 'Blur Rise' }, values: { animation: 'blurInUp', by: 'word', duration: 0.6, spread: 0.6 } },
    { id: 'typewriter', name: { 'zh-CN': '逐字', en: 'Typewriter' }, values: { animation: 'blurIn', by: 'character', duration: 0.35, spread: 1.1 } },
    { id: 'pop', name: { 'zh-CN': '弹入', en: 'Pop' }, values: { animation: 'scaleUp', by: 'word', duration: 0.5, spread: 0.5 } },
    { id: 'curtain', name: { 'zh-CN': '帷幕', en: 'Curtain' }, values: { animation: 'slideUp', by: 'character', duration: 0.5, spread: 0.9 } },
    { id: 'settle', name: { 'zh-CN': '落定', en: 'Settle' }, values: { animation: 'scaleDown', by: 'text', duration: 0.9, spread: 0 } },
  ],
  dependencies: ['motion/react', '@motif/runtime'],
  perf: { webgl: false, maxDpr: 2 },
  a11y: { reducedMotion: 'static' },
  capture: { zoom: 1.6, posterTime: 1.3, loop: 5 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'magicui',
      repo: 'magicuidesign/magicui',
      sha: 'd7207e5692d14c00dceafa8488d6d01f197fa0e4',
      paths: ['apps/www/registry/magicui/text-animate.tsx'],
      spdx: 'MIT',
      copyright: ['Copyright (c) Magic UI'],
    },
    modifications: [
      'Defaults moved into the generated defaults region; a text prop supplies the string when no children are passed, duration is the per-segment time and spread is the total stagger time (upstream tied both together).',
      'The ten animations are declared as plain hidden/show states with shared transitions; the exit variants, AnimatePresence, custom variants and the line split were removed. The default trigger is on mount, not in view.',
      'Motif improvement: with prefers-reduced-motion the animation becomes a short opacity fade of the whole text with no stagger, blur or movement.',
    ],
    assets: [],
  },
})
