import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'god-rays',
  status: 'published',
  title: { "zh-CN": '丁达尔光束', en: 'God Rays' },
  summary: {
    "zh-CN": '一束束光线从画面外洒入，边缘泛着柔和的光晕。适合做发布页、活动页的舞台光。',
    en: 'Beams of light fall in from off-screen with a soft bloom along the edges. Stage lighting for launch and event pages.',
  },
  kind: 'effect',
  category: 'background',
  tags: ['light', 'rays', 'beams', 'shader', 'webgl', 'hero'],
  runtime: ['react', 'webgl2'],
  entry: { file: 'god-rays.tsx', export: 'GodRaysBackground' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'god-rays.tsx', role: 'component' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    {
      key: 'colors',
      type: 'palette',
      label: { "zh-CN": '光线颜色', en: 'Ray colors' },
      hint: { "zh-CN": '支持半透明色', en: 'Translucent colors work well' },
      default: ['#a600ff6e', '#6200fff0', '#ffffff', '#33fff5'],
      minItems: 1,
      maxItems: 5,
    },
    { key: 'colorBack', type: 'color', label: { "zh-CN": '底色', en: 'Background' }, default: '#000000' },
    { key: 'colorBloom', type: 'color', label: { "zh-CN": '辉光色', en: 'Bloom color' }, default: '#0000ff' },
    {
      key: 'density',
      type: 'number',
      label: { "zh-CN": '密度', en: 'Density' },
      default: 0.3,
      min: 0,
      max: 1,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'spotty',
      type: 'number',
      label: { "zh-CN": '光斑', en: 'Spottiness' },
      default: 0.3,
      min: 0,
      max: 1,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'intensity',
      type: 'number',
      label: { "zh-CN": '强度', en: 'Intensity' },
      default: 0.8,
      min: 0.2,
      max: 1,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'bloom',
      type: 'number',
      label: { "zh-CN": '辉光', en: 'Bloom' },
      default: 0.4,
      min: 0,
      max: 1,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'speed',
      type: 'number',
      label: { "zh-CN": '速度', en: 'Speed' },
      default: 0.75,
      min: 0,
      max: 3,
      step: 0.01,
      safe: [0.1, 2],
      unit: 'x',
      group: 'motion',
    },
    {
      key: 'offsetX',
      type: 'number',
      label: { "zh-CN": '光源水平位置', en: 'Source X' },
      default: 0,
      min: -1,
      max: 1,
      step: 0.01,
      group: 'layout',
    },
    {
      key: 'offsetY',
      type: 'number',
      label: { "zh-CN": '光源垂直位置', en: 'Source Y' },
      default: -0.55,
      min: -1,
      max: 1,
      step: 0.01,
      group: 'layout',
    },
  ],
  presets: [
    {
      id: 'cathedral',
      name: { "zh-CN": '教堂', en: 'Cathedral' },
      values: {
        colors: ['#a600ff6e', '#6200fff0', '#ffffff', '#33fff5'],
        colorBack: '#000000',
        colorBloom: '#0000ff',
        density: 0.3,
        spotty: 0.3,
        intensity: 0.8,
        bloom: 0.4,
        speed: 0.75,
        offsetX: 0,
        offsetY: -0.55,
      },
    },
    {
      id: 'warp',
      name: { "zh-CN": '曲速', en: 'Warp drive' },
      values: {
        colors: ['#ff47d4', '#ff8c00', '#ffffff'],
        colorBack: '#000000',
        colorBloom: '#222288',
        density: 0.45,
        spotty: 0.15,
        intensity: 0.79,
        bloom: 0.4,
        speed: 2,
        offsetX: 0,
        offsetY: -0.55,
      },
    },
    {
      id: 'ether',
      name: { "zh-CN": '以太', en: 'Ether' },
      values: {
        colors: ['#148effa6', '#c4dffebe', '#232a47'],
        colorBack: '#090f1d',
        colorBloom: '#ffffff',
        density: 0.03,
        spotty: 0.77,
        intensity: 0.6,
        bloom: 0.6,
        speed: 1,
        offsetX: -0.6,
        offsetY: -0.55,
      },
    },
    {
      id: 'dawn',
      name: { "zh-CN": '晨光', en: 'Dawn' },
      values: {
        colors: ['#ffd7a86e', '#ff9a5cf0', '#fff3e0', '#ffb3c6'],
        colorBack: '#0b0a1a',
        colorBloom: '#ff7a3d',
        density: 0.35,
        spotty: 0.25,
        intensity: 0.85,
        bloom: 0.55,
        speed: 0.5,
        offsetX: 0.25,
        offsetY: -0.7,
      },
    },
  ],
  dependencies: ['@paper-design/shaders-react', '@motif/runtime'],
  perf: { webgl: true, maxDpr: 1.5 },
  a11y: { reducedMotion: 'static' },
  capture: { posterTime: 2 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'paper-shaders',
      repo: 'paper-design/shaders',
      sha: '43cd68db79fa0b1759f72ffc941b3238e2a3954c',
      paths: ['packages/shaders-react/src/shaders/god-rays.tsx', 'docs/src/shader-defs/god-rays-def.ts'],
      spdx: 'Apache-2.0',
      copyright: ['Paper Shaders (https://shaders.paper.design)'],
    },
    modifications: ['Wrapped the Paper GodRays component as a full-bleed background that can hold children.', 'Mid-glow size and intensity are fixed at the upstream defaults rather than exposed as parameters.', 'Parameter ranges adapted from the Paper docs; Cathedral (default), Warp drive (upstream Warp) and Ether follow the upstream presets (the Ether mid-glow values are not applied); Dawn is Motif’s.', 'Renders a static frame when the user prefers reduced motion.'],
    assets: [],
  },
})
