import type { SourceRecord } from '@motif/checker'
import type { ItemSource } from '@motif/schema'

/** 站点和预览沙箱随附分发的第三方运行时与字体（不在 sources.json 里，因为不是整合进来的条目代码）。 */
const BUNDLED: { name: string; license: string; url: string; use: string }[] = [
  { name: 'React, React DOM', license: 'MIT', url: 'https://github.com/facebook/react', use: 'site and preview sandbox runtime' },
  { name: 'motion', license: 'MIT', url: 'https://github.com/motiondivision/motion', use: 'preview sandbox and exported items' },
  { name: 'three.js', license: 'MIT', url: 'https://github.com/mrdoob/three.js', use: 'preview sandbox' },
  { name: '@paper-design/shaders-react', license: 'Apache-2.0', url: 'https://github.com/paper-design/shaders', use: 'preview sandbox and exported items (NOTICE: "Powered by Paper Shaders")' },
  { name: 'cobe', license: 'MIT', url: 'https://github.com/shuding/cobe', use: 'preview sandbox and exported items' },
  { name: 'clsx', license: 'MIT', url: 'https://github.com/lukeed/clsx', use: 'motif-runtime' },
  { name: 'tailwind-merge', license: 'MIT', url: 'https://github.com/dcastil/tailwind-merge', use: 'motif-runtime' },
  { name: 'Tailwind CSS, tw-animate-css', license: 'MIT', url: 'https://github.com/tailwindlabs/tailwindcss', use: 'item styles' },
  { name: 'Geist, Geist Mono (via Fontsource)', license: 'OFL-1.1', url: 'https://github.com/vercel/geist-font', use: 'site typography' },
  { name: 'Bricolage Grotesque (via Fontsource)', license: 'OFL-1.1', url: 'https://github.com/ateliertriay/bricolage', use: 'site display typography' },
]

/**
 * 生成 THIRD_PARTY_NOTICES.md：每个上游仓库的固定提交、许可证、版权声明，以及用到它的条目。
 * 由 pnpm notices 写出；测试保证提交的文件与生成结果一致。
 */
export function renderNotices(items: ItemSource[], sources: readonly SourceRecord[]): string {
  const lines = [
    '# Third-Party Notices',
    '',
    '<!-- Generated by `pnpm notices` from sources/sources.json and each item’s provenance. Do not edit by hand. -->',
    '',
    'Motif’s own code is MIT licensed (see LICENSE). Market items integrated from upstream projects keep their original license and copyright notices, which also appear in the header of every such file. Each upstream is pinned to the commit we reviewed.',
    '',
    'We only integrate code whose license allows redistribution (MIT, Apache-2.0, ISC, BSD, Zlib, Unlicense, CC0). Projects under Commons Clause, non-commercial, AGPL or no license are linked, never copied.',
    '',
    '## Integrated upstream projects',
    '',
  ]

  for (const source of sources) {
    const using = items
      .filter((item) => item.manifest.provenance.upstream?.source === source.id)
      .map((item) => item.manifest.slug)
      .sort()
    if (using.length === 0) continue
    lines.push(`### ${source.repo}`, '')
    lines.push(`- License: ${source.spdx}`)
    lines.push(`- Commit: [\`${source.sha.slice(0, 7)}\`](https://github.com/${source.repo}/tree/${source.sha})`)
    for (const copyright of source.copyright) lines.push(`- ${copyright}`)
    lines.push(`- Used by: ${using.map((slug) => `\`${slug}\``).join(', ')}`)
    const origins = [...new Set(items.flatMap((item) => (item.manifest.provenance.upstream?.source === source.id && item.manifest.provenance.upstream.origin ? [item.manifest.provenance.upstream.origin] : [])))]
    if (origins.length > 0) lines.push(`- Upstream-declared origins: ${origins.join('; ')}`)
    lines.push('')
  }

  lines.push('## Bundled runtimes and fonts', '', '| Package | License | Used for |', '| --- | --- | --- |')
  for (const entry of BUNDLED) lines.push(`| [${entry.name}](${entry.url}) | ${entry.license} | ${entry.use} |`)
  lines.push('')
  return lines.join('\n')
}
