import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'neuro-noise',
  status: 'published',
  title: { "zh-CN": '神经噪声', en: 'Neuro Noise' },
  summary: {
    "zh-CN": '发光的细丝交织成神经网络般的纹理，像闪电、血管或星轨。适合科技感的背景。',
    en: 'Glowing filaments weave into a neural-network texture, like lightning, veins or star trails. A backdrop with a technical edge.',
  },
  kind: 'effect',
  category: 'shader',
  tags: ['neural', 'noise', 'lightning', 'shader', 'webgl', 'tech'],
  runtime: ['react', 'webgl2'],
  entry: { file: 'neuro-noise.tsx', export: 'NeuroNoiseBackground' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'neuro-noise.tsx', role: 'component' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    { key: 'colorFront', type: 'color', label: { "zh-CN": '前景色', en: 'Front color' }, default: '#ffffff' },
    { key: 'colorMid', type: 'color', label: { "zh-CN": '中间色', en: 'Mid color' }, default: '#47a6ff' },
    { key: 'colorBack', type: 'color', label: { "zh-CN": '底色', en: 'Background' }, default: '#000000' },
    {
      key: 'brightness',
      type: 'number',
      label: { "zh-CN": '亮度', en: 'Brightness' },
      default: 0.05,
      min: 0,
      max: 0.5,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'contrast',
      type: 'number',
      label: { "zh-CN": '对比度', en: 'Contrast' },
      default: 0.3,
      min: 0.05,
      max: 1,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'speed',
      type: 'number',
      label: { "zh-CN": '速度', en: 'Speed' },
      default: 1,
      min: 0,
      max: 3,
      step: 0.01,
      safe: [0.1, 2],
      unit: 'x',
      group: 'motion',
    },
    {
      key: 'scale',
      type: 'number',
      label: { "zh-CN": '缩放', en: 'Scale' },
      default: 1,
      min: 0.3,
      max: 4,
      step: 0.01,
      safe: [0.4, 3],
      unit: 'x',
      group: 'layout',
    },
    {
      key: 'rotation',
      type: 'number',
      label: { "zh-CN": '旋转', en: 'Rotation' },
      default: 0,
      min: 0,
      max: 360,
      step: 1,
      unit: 'deg',
      group: 'layout',
    },
  ],
  presets: [
    {
      id: 'synapse',
      name: { "zh-CN": '突触', en: 'Synapse' },
      values: { colorFront: '#ffffff', colorMid: '#47a6ff', colorBack: '#000000', brightness: 0.05, contrast: 0.3, speed: 1, scale: 1, rotation: 0 },
    },
    {
      id: 'sensation',
      name: { "zh-CN": '通感', en: 'Sensation' },
      values: { colorFront: '#00c8ff', colorMid: '#fbff00', colorBack: '#8b42ff', brightness: 0.19, contrast: 0.12, speed: 1, scale: 3, rotation: 0 },
    },
    {
      id: 'bloodstream',
      name: { "zh-CN": '血流', en: 'Bloodstream' },
      values: { colorFront: '#ff0000', colorMid: '#ff0000', colorBack: '#ffffff', brightness: 0.24, contrast: 0.17, speed: 1, scale: 0.7, rotation: 0 },
    },
    {
      id: 'ghost',
      name: { "zh-CN": '幽灵', en: 'Ghost' },
      values: { colorFront: '#ffffff', colorMid: '#000000', colorBack: '#ffffff', brightness: 0, contrast: 1, speed: 1, scale: 0.55, rotation: 0 },
    },
    {
      id: 'deepsea',
      name: { "zh-CN": '深海', en: 'Deep sea' },
      values: { colorFront: '#b8fff2', colorMid: '#0fb5ae', colorBack: '#020b14', brightness: 0.12, contrast: 0.25, speed: 1, scale: 1.4, rotation: 0 },
    },
  ],
  dependencies: ['@paper-design/shaders-react', '@motif/runtime'],
  perf: { webgl: true, maxDpr: 1.5 },
  a11y: { reducedMotion: 'static' },
  capture: { posterTime: 2 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'paper-shaders',
      repo: 'paper-design/shaders',
      sha: '43cd68db79fa0b1759f72ffc941b3238e2a3954c',
      paths: ['packages/shaders-react/src/shaders/neuro-noise.tsx', 'docs/src/shader-defs/neuro-noise-def.ts'],
      spdx: 'Apache-2.0',
      copyright: ['Paper Shaders (https://shaders.paper.design)'],
    },
    modifications: ['Wrapped the Paper NeuroNoise component as a full-bleed background that can hold children.', 'Parameter ranges adapted from the Paper docs; Synapse (default), Sensation, Bloodstream and Ghost follow the upstream presets; Deep sea is Motif’s.', 'Renders a static frame when the user prefers reduced motion.'],
    assets: [],
  },
})
