import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'waves',
  status: 'published',
  title: { "zh-CN": '波纹线', en: 'Waves' },
  summary: {
    "zh-CN": '一排排起伏的线条，可以是平静的波纹，也可以缠成一团。适合做极简、印刷风的背景或分隔。',
    en: 'Rows of undulating lines, from calm ripples to tangled knots. For minimal, print-inspired backdrops and dividers.',
  },
  category: 'shader',
  tags: ['waves', 'lines', 'stripes', 'shader', 'webgl', 'print'],
  runtime: ['react', 'webgl2'],
  entry: { file: 'waves.tsx', export: 'WavesBackground' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'waves.tsx', role: 'component' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    { key: 'colorFront', type: 'color', label: { "zh-CN": '线条色', en: 'Line color' }, default: '#ffc21a' },
    { key: 'colorBack', type: 'color', label: { "zh-CN": '底色', en: 'Background' }, default: '#0b0b0f' },
    {
      key: 'shape',
      type: 'number',
      label: { "zh-CN": '形态', en: 'Shape' },
      hint: { "zh-CN": '从平缓到缠绕的连续变化', en: 'A continuous morph from calm to tangled' },
      default: 2.25,
      min: 0,
      max: 3,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'frequency',
      type: 'number',
      label: { "zh-CN": '频率', en: 'Frequency' },
      default: 0.2,
      min: 0.1,
      max: 1.2,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'amplitude',
      type: 'number',
      label: { "zh-CN": '振幅', en: 'Amplitude' },
      default: 1,
      min: 0.05,
      max: 1,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'spacing',
      type: 'number',
      label: { "zh-CN": '线距', en: 'Spacing' },
      default: 1.25,
      min: 0.8,
      max: 2,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'proportion',
      type: 'number',
      label: { "zh-CN": '线宽比例', en: 'Line proportion' },
      default: 0.6,
      min: 0.05,
      max: 1,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'speed',
      type: 'number',
      label: { "zh-CN": '速度', en: 'Speed' },
      default: 0.6,
      min: 0,
      max: 2,
      step: 0.01,
      safe: [0.1, 1.2],
      unit: 'x',
      group: 'motion',
    },
    {
      key: 'scale',
      type: 'number',
      label: { "zh-CN": '缩放', en: 'Scale' },
      default: 1.7,
      min: 0.3,
      max: 6,
      step: 0.01,
      safe: [0.4, 5],
      unit: 'x',
      group: 'layout',
    },
    {
      key: 'rotation',
      type: 'number',
      label: { "zh-CN": '旋转', en: 'Rotation' },
      default: 0,
      min: 0,
      max: 360,
      step: 1,
      unit: 'deg',
      group: 'layout',
    },
  ],
  presets: [
    {
      id: 'amber',
      name: { "zh-CN": '琥珀', en: 'Amber' },
      values: {
        colorFront: '#ffc21a',
        colorBack: '#0b0b0f',
        shape: 2.25,
        frequency: 0.2,
        amplitude: 1,
        spacing: 1.25,
        proportion: 0.6,
        speed: 0.6,
        scale: 1.7,
        rotation: 0,
      },
    },
    {
      id: 'zigzag',
      name: { "zh-CN": '锯齿', en: 'Zigzag' },
      values: {
        colorFront: '#ffbb00',
        colorBack: '#000000',
        shape: 0,
        frequency: 0.5,
        amplitude: 0.5,
        spacing: 1.2,
        proportion: 0.1,
        speed: 0.6,
        scale: 0.6,
        rotation: 0,
      },
    },
    {
      id: 'groovy',
      name: { "zh-CN": '律动', en: 'Groovy' },
      values: {
        colorFront: '#fcfcee',
        colorBack: '#ff896b',
        shape: 3,
        frequency: 0.2,
        amplitude: 0.25,
        spacing: 1.17,
        proportion: 0.57,
        speed: 0.6,
        scale: 5,
        rotation: 90,
      },
    },
    {
      id: 'tangled',
      name: { "zh-CN": '纠缠', en: 'Tangled up' },
      values: {
        colorFront: '#133a41',
        colorBack: '#c2d8b6',
        shape: 2.07,
        frequency: 0.44,
        amplitude: 0.57,
        spacing: 1.05,
        proportion: 0.75,
        speed: 0.6,
        scale: 0.5,
        rotation: 0,
      },
    },
    {
      id: 'ride',
      name: { "zh-CN": '乘浪', en: 'Ride the wave' },
      values: {
        colorFront: '#fdffe6',
        colorBack: '#1f1f1f',
        shape: 2.25,
        frequency: 0.2,
        amplitude: 1,
        spacing: 1.25,
        proportion: 1,
        speed: 0.6,
        scale: 1.7,
        rotation: 0,
      },
    },
  ],
  dependencies: ['@paper-design/shaders-react', '@motif/runtime'],
  perf: { webgl: true, maxDpr: 1.5 },
  a11y: { reducedMotion: 'static' },
  capture: { posterTime: 2 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'paper-shaders',
      repo: 'paper-design/shaders',
      sha: '43cd68db79fa0b1759f72ffc941b3238e2a3954c',
      paths: ['packages/shaders-react/src/shaders/waves.tsx', 'docs/src/shader-defs/waves-def.ts'],
      spdx: 'Apache-2.0',
      copyright: ['Paper Shaders (https://shaders.paper.design)'],
    },
    modifications: ['Wrapped the Paper Waves component as a full-bleed background that can hold children.', 'The upstream shader is static; Motif adds a slow breathing motion by drifting the vertical offset and morphing the shape parameter over time.', 'Parameter ranges adapted from the Paper docs; Amber (default), Groovy, Tangled up and Ride the wave follow the upstream presets.', 'Renders a static frame when the user prefers reduced motion.'],
    assets: [],
  },
})
