import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'style-terminal',
  status: 'published',
  title: { 'zh-CN': '终端', en: 'Terminal' },
  summary: {
    'zh-CN': '等宽字体铺满整页：细线边框、反色按钮、一抹荧光强调色和闪烁的光标，命令提示符风格的分节。适合开发者工具、CLI 文档和技术博客。',
    en: 'Monospace all the way down: hairline borders, inverse-video buttons, one phosphor accent, a blinking caret and prompt-style sections. For developer tools, CLI docs and technical blogs.',
  },
  kind: 'style',
  category: 'technical',
  tags: ['terminal', 'tui', 'monospace', 'cli', 'developer', 'tokens', 'design system'],
  runtime: ['react', 'css'],
  entry: { file: 'style-terminal.tsx', export: 'Terminal' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'style-terminal.tsx', role: 'component' },
    { path: 'style-terminal.css', role: 'style' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    {
      key: 'accent',
      type: 'color',
      group: 'look',
      label: { 'zh-CN': '荧光强调色', en: 'Phosphor accent' },
      hint: { 'zh-CN': '提示符、光标、主按钮和选中态的颜色', en: 'Prompt, caret, primary button and selected state' },
      default: '#5af78e',
    },
    {
      key: 'radius',
      type: 'number',
      group: 'shape',
      label: { 'zh-CN': '圆角', en: 'Corner radius' },
      default: 2,
      min: 0,
      max: 8,
      step: 1,
      unit: 'px',
      safe: [0, 6],
    },
    {
      key: 'borderWidth',
      type: 'number',
      group: 'shape',
      label: { 'zh-CN': '线宽', en: 'Line width' },
      default: 1,
      min: 1,
      max: 2,
      step: 0.5,
      unit: 'px',
      safe: [1, 2],
    },
    {
      key: 'fontPairing',
      type: 'select',
      group: 'type',
      label: { 'zh-CN': '字体搭配', en: 'Font pairing' },
      default: 'jetbrains',
      options: [
        { value: 'jetbrains', label: { 'zh-CN': 'JetBrains Mono', en: 'JetBrains Mono' } },
        { value: 'geist-mono', label: { 'zh-CN': 'Geist Mono', en: 'Geist Mono' } },
        { value: 'plex-mono', label: { 'zh-CN': 'IBM Plex Mono', en: 'IBM Plex Mono' } },
        { value: 'vt323', label: { 'zh-CN': 'VT323 复古终端', en: 'VT323 CRT' } },
      ],
    },
    {
      key: 'glow',
      type: 'number',
      group: 'look',
      label: { 'zh-CN': '荧光辉光', en: 'Phosphor glow' },
      default: 0.5,
      min: 0,
      max: 1,
      step: 0.1,
      safe: [0, 0.8],
    },
    {
      key: 'density',
      type: 'number',
      group: 'layout',
      label: { 'zh-CN': '疏密', en: 'Density' },
      default: 1,
      min: 0.85,
      max: 1.2,
      step: 0.05,
      unit: 'x',
      safe: [0.9, 1.15],
    },
    {
      key: 'mode',
      type: 'select',
      group: 'look',
      label: { 'zh-CN': '深浅', en: 'Mode' },
      default: 'dark',
      options: [
        { value: 'dark', label: { 'zh-CN': '深色', en: 'Dark' } },
        { value: 'light', label: { 'zh-CN': '浅色', en: 'Light' } },
      ],
    },
    {
      key: 'scanlines',
      type: 'boolean',
      group: 'look',
      label: { 'zh-CN': '扫描线', en: 'Scanlines' },
      default: true,
    },
  ],
  presets: [
    {
      id: 'phosphor',
      name: { 'zh-CN': '磷光绿', en: 'Phosphor green' },
      values: {
        accent: '#5af78e',
        radius: 2,
        borderWidth: 1,
        glow: 0.5,
        density: 1,
        fontPairing: 'jetbrains',
        mode: 'dark',
        scanlines: true,
      },
    },
    {
      id: 'amber',
      name: { 'zh-CN': '琥珀', en: 'Amber' },
      values: {
        accent: '#ffb000',
        radius: 0,
        borderWidth: 1,
        glow: 0.8,
        density: 1,
        fontPairing: 'vt323',
        mode: 'dark',
        scanlines: true,
      },
    },
    {
      id: 'ice',
      name: { 'zh-CN': '冰蓝', en: 'Ice' },
      values: {
        accent: '#57c7ff',
        radius: 4,
        borderWidth: 1,
        glow: 0.3,
        density: 1,
        fontPairing: 'geist-mono',
        mode: 'dark',
        scanlines: false,
      },
    },
    {
      id: 'paper-tty',
      name: { 'zh-CN': '纸面终端', en: 'Paper tty' },
      values: {
        accent: '#1a7f5a',
        radius: 2,
        borderWidth: 1,
        glow: 0,
        density: 1.05,
        fontPairing: 'plex-mono',
        mode: 'light',
        scanlines: false,
      },
    },
  ],
  dependencies: ['@motif/runtime'],
  fonts: ['JetBrains Mono Variable', 'Geist Mono Variable', 'IBM Plex Mono', 'VT323'],
  guidance: {
    use: [
      'Use for developer tools, CLI and API documentation, technical blogs, status pages and hacker-event sites where the audience lives in a terminal.',
      'Avoid for consumer, lifestyle or image-led brands.',
    ],
    rules: [
      'Typography: one monospace family for everything (JetBrains Mono, Geist Mono, IBM Plex Mono or VT323). Body 15px / line-height 1.6, headings only differ by size and weight 700, never by family. Markdown-style prefixes (## , ### , $ ) mark levels; tight negative tracking only on the display size.',
      'Palette ratio: about 80% near-black ground (tinted 4% by the accent) and dim surfaces, 12% foreground text (#d5dde4) and dim comments (#7d8a96), 6% the phosphor accent, 2% tag colors (yellow, cyan, pink) used only for status. Light mode inverts to warm paper with near-black ink. Text is never pure white.',
      'Borders are 1px hairlines in a translucent foreground, with the accent reserved for the active or focused element. Radius is 0-4px. No box shadows except the accent glow on the featured card and the window; no fills except flat surface tints.',
      'Buttons are inverse-video blocks in the accent (dark text on accent); on hover they invert to an outline. Secondary buttons render as [ bracketed ] text, ghost buttons get a > prefix, switches read [x] / [ ], alerts start with [i], [ok] or [!], and inputs are prefixed by a $ label.',
      'Sections start with a prompt line (~/shell $ show palette) above the heading. Use code-like content in demos: commands, logs, version numbers; never lorem ipsum.',
      'Motion is minimal and instant: 60ms linear color swaps and a blinking block caret with steps(1). No easing, no movement, no fades. Reduced motion stops the caret.',
      'Do not use gradients, rounded 12px+ cards, drop shadows, emoji, illustrations or more than one accent color per screen. Do not mix a proportional font into the interface.',
    ],
  },
  perf: { webgl: false, maxDpr: 2 },
  a11y: { reducedMotion: 'static' },
  capture: { scroll: true, posterTime: 0.5, loop: 8 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'webtui',
      repo: 'webtui/webtui',
      sha: 'c8eaf2c10a08e33082602be353ec20affc43770e',
      paths: [
        'packages/css/src/base.css',
        'packages/css/src/components/button.css',
        'packages/css/src/components/badge.css',
        'packages/css/src/components/input.css',
      ],
      spdx: 'MIT',
      copyright: ['Copyright (c) 2025 WebTUI'],
    },
    modifications: [
      'Kept the WebTUI ideas of a monospace grid, inverse-video buttons and hover/active color swaps, and a small set of foreground/background tokens, but rewrote them as CSS variables scoped to a .tm-root element (no global element selectors or custom attributes) driven by component props.',
      'Replaced the attribute-based components (is-="button", box-) with class-based React primitives (button, card, field, badge, tabs, alert, [x] switch) in one CSS file; borders are hairlines in the ch/em grid rather than box-drawing pseudo elements.',
      'Added accent-derived ground colors, phosphor glow, optional scanlines, a dark / light mode, a bracketed secondary button and prompt-style section headers. The terminal window in the demo is drawn with plain elements; no gallery images are used.',
      'Fonts are self-hosted OFL monospace families from the Motif font list (JetBrains Mono, Geist Mono, IBM Plex Mono, VT323).',
    ],
    assets: [],
  },
})
