import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'cta-ripple-panel',
  status: 'published',
  title: { 'zh-CN': '涟漪行动号召面板', en: 'Ripple CTA Panel' },
  summary: {
    'zh-CN': '一块圆角面板，底部升起同心圆环并缓缓收放，配上网格线、大标题和主按钮。可切成左文右邮箱表单的版式。放在页面末尾做最后一次转化。',
    en: 'A rounded panel with concentric rings rising from the bottom and gently breathing, over a faint grid, with a big headline and one main button. Switch to a split layout with an email form. The last conversion push at the end of a page.',
  },
  kind: 'section',
  category: 'cta',
  tags: ['cta', 'call to action', 'ripple', 'rings', 'signup', 'conversion'],
  runtime: ['react', 'css'],
  entry: { file: 'cta-ripple-panel.tsx', export: 'CtaRipplePanel' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'cta-ripple-panel.tsx', role: 'component' },
    { path: 'cta-ripple-panel.css', role: 'style' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    { key: 'eyebrow', type: 'text', label: { 'zh-CN': '小标签', en: 'Eyebrow' }, default: 'Free for 14 days', maxLength: 26, group: 'content' },
    { key: 'heading', type: 'text', label: { 'zh-CN': '标题', en: 'Heading' }, default: 'Ship the next release with the whole timeline in view', maxLength: 70, group: 'content' },
    {
      key: 'subline',
      type: 'text',
      label: { 'zh-CN': '副标题', en: 'Subline' },
      default: 'Connect your repo in two minutes. Your first trace shows up before the coffee is ready.',
      maxLength: 130,
      group: 'content',
    },
    { key: 'cta', type: 'text', label: { 'zh-CN': '主按钮', en: 'Button label' }, default: 'Start free trial', maxLength: 24, group: 'content' },
    { key: 'note', type: 'text', label: { 'zh-CN': '按钮下的小字', en: 'Small print' }, default: 'No card required. Cancel from settings.', maxLength: 60, group: 'content' },
    { key: 'accent', type: 'color', label: { 'zh-CN': '主色', en: 'Accent color' }, default: '#8b7bff', group: 'look' },
    {
      key: 'tone',
      type: 'select',
      label: { 'zh-CN': '明暗', en: 'Tone' },
      default: 'dark',
      options: [
        { value: 'dark', label: { 'zh-CN': '深色', en: 'Dark' } },
        { value: 'light', label: { 'zh-CN': '浅色', en: 'Light' } },
      ],
      group: 'look',
    },
    {
      key: 'font',
      type: 'select',
      label: { 'zh-CN': '标题字体', en: 'Heading font' },
      default: 'geist',
      options: [
        { value: 'geist', label: { 'zh-CN': 'Geist 无衬线', en: 'Geist sans' } },
        { value: 'grotesk', label: { 'zh-CN': 'Space Grotesk', en: 'Space Grotesk' } },
        { value: 'serif', label: { 'zh-CN': 'Instrument 衬线', en: 'Instrument serif' } },
      ],
      group: 'look',
    },
    { key: 'radius', type: 'number', label: { 'zh-CN': '面板圆角', en: 'Panel radius' }, default: 32, min: 0, max: 48, step: 1, unit: 'px', safe: [12, 40], group: 'look' },
    {
      key: 'layout',
      type: 'select',
      label: { 'zh-CN': '版式', en: 'Layout' },
      default: 'centered',
      options: [
        { value: 'centered', label: { 'zh-CN': '居中', en: 'Centered' } },
        { value: 'split', label: { 'zh-CN': '左文右表单', en: 'Split with form' } },
      ],
      group: 'layout',
    },
    { key: 'rings', type: 'number', label: { 'zh-CN': '圆环数量', en: 'Ring count' }, default: 6, min: 3, max: 9, step: 1, safe: [4, 8], group: 'motion' },
    { key: 'speed', type: 'number', label: { 'zh-CN': '收放一次用时', en: 'Breath duration' }, default: 4, min: 3, max: 14, step: 0.5, unit: 's', safe: [3, 10], group: 'motion' },
  ],
  presets: [
    { id: 'violet-tide', name: { 'zh-CN': '紫潮', en: 'Violet Tide' }, values: {} },
    { id: 'ember-split', name: { 'zh-CN': '余烬', en: 'Ember' }, values: { accent: '#ff7a3d', layout: 'split', font: 'grotesk', rings: 5 } },
    { id: 'porcelain', name: { 'zh-CN': '瓷白', en: 'Porcelain' }, values: { tone: 'light', accent: '#2563eb', font: 'serif', radius: 24 } },
  ],
  dependencies: ['@motif/runtime'],
  fonts: ['Geist Variable', 'Space Grotesk Variable', 'Instrument Serif'],
  guidance: {
    rules: [
      'One primary action only. The secondary button is quiet (outline) and must never use the accent fill.',
      'Headline states the outcome in under twelve words; the small print removes a fear (no card, cancel any time).',
      'Place it right before the footer; do not stack two CTA panels on the same page.',
    ],
  },
  perf: { webgl: false, maxDpr: 2 },
  a11y: { reducedMotion: 'static' },
  capture: { posterTime: 2, loop: 8 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'eldoraui',
      repo: 'karthikmudunuri/eldoraui',
      sha: '6bb8fd211ecbdfa983f5780bead27d9f3890f20a',
      paths: ['apps/www/registry/blocks/cta-03/components/ripple-bg.tsx', 'apps/www/registry/blocks/cta-03/components/cta-03.tsx'],
      spdx: 'MIT',
      copyright: ['Copyright (c) Mudunuri Bhaskara Karthikeya Varma'],
    },
    modifications: [
      'Kept the Ripple idea (concentric rings that scale between 1 and 0.9 with staggered delays); rings are anchored to the panel bottom, tinted by the accent and masked to fade upward.',
      'The panel, grid, headline, form layout and copy are new; shadcn Button and the theme variables were replaced by inline-style tokens with a light/dark tone.',
      'The ring keyframes live in cta-ripple-panel.css and stop under prefers-reduced-motion.',
    ],
    assets: [],
  },
})
