import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'dithering',
  status: 'published',
  title: { "zh-CN": '抖动像素', en: 'Dithering' },
  summary: {
    "zh-CN": '双色抖动网点勾勒出球体、水波或漩涡，带着复古位图的味道。适合做有个性的背景或像素风视觉。',
    en: 'Two-tone dither dots sketch spheres, ripples or swirls with a retro bitmap feel. For characterful backdrops and pixel-art visuals.',
  },
  kind: 'effect',
  category: 'shader',
  tags: ['dither', 'pixel', 'retro', 'bitmap', 'shader', 'webgl'],
  runtime: ['react', 'webgl2'],
  entry: { file: 'dithering.tsx', export: 'DitheringBackground' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'dithering.tsx', role: 'component' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    { key: 'colorBack', type: 'color', label: { "zh-CN": '底色', en: 'Background' }, default: '#000000' },
    { key: 'colorFront', type: 'color', label: { "zh-CN": '前景色', en: 'Front color' }, default: '#3db9ff' },
    {
      key: 'shape',
      type: 'select',
      label: { "zh-CN": '图案', en: 'Pattern' },
      default: 'sphere',
      options: [
        { value: 'sphere', label: { "zh-CN": '球体', en: 'Sphere' } },
        { value: 'warp', label: { "zh-CN": '扭曲', en: 'Warp' } },
        { value: 'wave', label: { "zh-CN": '正弦波', en: 'Sine wave' } },
        { value: 'ripple', label: { "zh-CN": '水波', en: 'Ripple' } },
        { value: 'swirl', label: { "zh-CN": '漩涡', en: 'Swirl' } },
        { value: 'dots', label: { "zh-CN": '圆点', en: 'Dots' } },
        { value: 'simplex', label: { "zh-CN": '噪声', en: 'Simplex' } },
      ],
      group: 'look',
    },
    {
      key: 'type',
      type: 'select',
      label: { "zh-CN": '抖动算法', en: 'Dither type' },
      default: '4x4',
      options: [
        { value: '4x4', label: { "zh-CN": '4×4 矩阵', en: '4×4 matrix' } },
        { value: '2x2', label: { "zh-CN": '2×2 矩阵', en: '2×2 matrix' } },
        { value: '8x8', label: { "zh-CN": '8×8 矩阵', en: '8×8 matrix' } },
        { value: 'random', label: { "zh-CN": '随机', en: 'Random' } },
      ],
      group: 'look',
    },
    {
      key: 'size',
      type: 'number',
      label: { "zh-CN": '像素大小', en: 'Pixel size' },
      default: 2,
      min: 1,
      max: 12,
      step: 0.5,
      safe: [1.5, 8],
      unit: 'px',
      group: 'look',
    },
    {
      key: 'speed',
      type: 'number',
      label: { "zh-CN": '速度', en: 'Speed' },
      default: 1,
      min: 0,
      max: 3,
      step: 0.01,
      safe: [0.1, 2],
      unit: 'x',
      group: 'motion',
    },
    {
      key: 'scale',
      type: 'number',
      label: { "zh-CN": '缩放', en: 'Scale' },
      default: 0.6,
      min: 0.3,
      max: 3,
      step: 0.01,
      safe: [0.4, 2],
      unit: 'x',
      group: 'layout',
    },
  ],
  presets: [
    {
      id: 'cobalt',
      name: { "zh-CN": '钴蓝', en: 'Cobalt' },
      values: { colorBack: '#000000', colorFront: '#3db9ff', shape: 'sphere', type: '4x4', size: 2, speed: 1, scale: 0.6 },
    },
    {
      id: 'warp',
      name: { "zh-CN": '藤蔓', en: 'Vine' },
      values: { colorBack: '#301c2a', colorFront: '#56ae6c', shape: 'warp', type: '4x4', size: 2.5, speed: 1, scale: 0.6 },
    },
    {
      id: 'sine',
      name: { "zh-CN": '正弦', en: 'Sine wave' },
      values: { colorBack: '#730d54', colorFront: '#00becc', shape: 'wave', type: '4x4', size: 11, speed: 1, scale: 1.2 },
    },
    {
      id: 'copper',
      name: { "zh-CN": '铜色涟漪', en: 'Copper ripple' },
      values: { colorBack: '#603520', colorFront: '#c67953', shape: 'ripple', type: '2x2', size: 3, speed: 1, scale: 0.6 },
    },
    {
      id: 'frost',
      name: { "zh-CN": '霜纹', en: 'Frost' },
      values: { colorBack: '#050b1a', colorFront: '#47a8e1', shape: 'swirl', type: '8x8', size: 2, speed: 1, scale: 0.6 },
    },
  ],
  dependencies: ['@paper-design/shaders-react', '@motif/runtime'],
  perf: { webgl: true, maxDpr: 1.5 },
  a11y: { reducedMotion: 'static' },
  capture: { posterTime: 2 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'paper-shaders',
      repo: 'paper-design/shaders',
      sha: '43cd68db79fa0b1759f72ffc941b3238e2a3954c',
      paths: ['packages/shaders-react/src/shaders/dithering.tsx', 'docs/src/shader-defs/dithering-def.ts'],
      spdx: 'Apache-2.0',
      copyright: ['Paper Shaders (https://shaders.paper.design)'],
    },
    modifications: ['Wrapped the Paper Dithering component as a full-bleed background that can hold children; ripple, swirl and warp use contain fit and the other patterns use pattern sizing, as in the upstream presets.', 'Parameter ranges adapted from the Paper docs; Cobalt (default), Vine (upstream Warp), Sine wave, Copper ripple (upstream Ripple) and Frost (upstream Swirl, on an opaque base) follow the upstream presets.', 'Renders a static frame when the user prefers reduced motion.'],
    assets: [],
  },
})
