import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'dashboard-area-chart',
  status: 'published',
  title: { 'zh-CN': '交互图表卡', en: 'Interactive Chart Card' },
  summary: {
    'zh-CN': '带时间范围切换的双序列图表卡：面积、柱状、折线三种画法，悬停出十字线和数据提示。手绘 SVG，不依赖图表库。',
    en: 'A two-series chart card with a time-range switch, area, bar or line drawing and a crosshair tooltip. Hand-drawn SVG, no chart library.',
  },
  kind: 'section',
  category: 'dashboard',
  tags: ['dashboard', 'chart', 'area chart', 'bar chart', 'tooltip', 'svg chart'],
  runtime: ['react', 'motion', 'svg'],
  entry: { file: 'dashboard-area-chart.tsx', export: 'DashboardAreaChart' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'dashboard-area-chart.tsx', role: 'component' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    { key: 'accent', type: 'color', label: { 'zh-CN': '主色', en: 'Primary series' }, default: '#7c8cff', group: 'look' },
    { key: 'secondary', type: 'color', label: { 'zh-CN': '副色', en: 'Secondary series' }, default: '#38bdf8', group: 'look' },
    {
      key: 'chart',
      type: 'select',
      label: { 'zh-CN': '图表类型', en: 'Chart type' },
      default: 'area',
      options: [
        { value: 'area', label: { 'zh-CN': '面积', en: 'Area' } },
        { value: 'lines', label: { 'zh-CN': '折线', en: 'Lines' } },
        { value: 'bars', label: { 'zh-CN': '柱状', en: 'Bars' } },
      ],
      group: 'look',
    },
    {
      key: 'range',
      type: 'select',
      label: { 'zh-CN': '默认范围', en: 'Default range' },
      default: '30d',
      options: [
        { value: '7d', label: { 'zh-CN': '7 天', en: '7 days' } },
        { value: '30d', label: { 'zh-CN': '30 天', en: '30 days' } },
        { value: '90d', label: { 'zh-CN': '90 天', en: '90 days' } },
      ],
      group: 'content',
    },
    {
      key: 'density',
      type: 'select',
      label: { 'zh-CN': '图表高度', en: 'Chart height' },
      default: 'comfortable',
      options: [
        { value: 'compact', label: { 'zh-CN': '紧凑', en: 'Compact' } },
        { value: 'comfortable', label: { 'zh-CN': '舒适', en: 'Comfortable' } },
        { value: 'spacious', label: { 'zh-CN': '宽松', en: 'Spacious' } },
      ],
      group: 'layout',
    },
    { key: 'seed', type: 'number', label: { 'zh-CN': '数据种子', en: 'Data seed' }, default: 11, min: 1, max: 999, step: 1, group: 'content' },
    { key: 'title', type: 'text', label: { 'zh-CN': '标题', en: 'Title' }, default: 'Visitors', maxLength: 28, group: 'content' },
    { key: 'subtitle', type: 'text', label: { 'zh-CN': '副标题', en: 'Subtitle' }, default: 'Sessions by device, counted daily', maxLength: 56, group: 'content' },
    { key: 'showGrid', type: 'boolean', label: { 'zh-CN': '显示网格线', en: 'Show gridlines' }, default: true, group: 'look' },
    { key: 'animate', type: 'boolean', label: { 'zh-CN': '入场动画', en: 'Entrance animation' }, default: true, group: 'motion' },
  ],
  presets: [
    { id: 'nocturne', name: { 'zh-CN': '夜曲', en: 'Nocturne' }, values: { accent: '#7c8cff', secondary: '#38bdf8', chart: 'area' } },
    { id: 'tidal', name: { 'zh-CN': '潮汐', en: 'Tidal' }, values: { accent: '#2dd4bf', secondary: '#60a5fa', chart: 'lines', range: '90d', seed: 5 } },
    { id: 'ember', name: { 'zh-CN': '余烬', en: 'Ember' }, values: { accent: '#fb923c', secondary: '#f472b6', chart: 'bars', range: '7d', seed: 30 } },
    { id: 'mono', name: { 'zh-CN': '素白', en: 'Mono' }, values: { accent: '#e4e4e7', secondary: '#71717a', chart: 'area', seed: 2 } },
  ],
  dependencies: ['motion/react', '@motif/runtime'],
  fonts: ['Geist Variable'],
  perf: { webgl: false, maxDpr: 2 },
  a11y: { reducedMotion: 'static' },
  guidance: {
    use: ['Use as the main chart of an analytics page, under a KPI strip. It measures its own width, so give it a container, not a fixed size.'],
    rules: ['The chart is plain SVG computed from data arrays; replace makeData with real series and keep the axes helpers.'],
  },
  capture: { zoom: 1.1, posterTime: 3, loop: 6 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'shadcn-ui',
      repo: 'shadcn-ui/ui',
      sha: '08ab84f7d1952cc1f36055aa8931213a86b01bbd',
      paths: ['apps/v4/registry/new-york-v4/blocks/dashboard-01/components/chart-area-interactive.tsx'],
      spdx: 'MIT',
      copyright: ['Copyright (c) 2023 shadcn'],
    },
    modifications: [
      'Replaced recharts with hand-drawn SVG: smooth area/line paths, bars, nice axis ticks, crosshair and tooltip.',
      'Data is invented and generated from a seed; the range switcher uses a motion layoutId pill.',
      'Added series toggles, chart-type and density params, a clip-path reveal and a reduced-motion path.',
    ],
    assets: [],
  },
})
