import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'magnetic',
  status: 'published',
  title: { 'zh-CN': '磁吸', en: 'Magnetic' },
  summary: {
    'zh-CN': '指针靠近时，按钮、图标被轻轻吸向指针，离开后弹回原位。给工具栏、行动按钮加一点有手感的反馈。',
    en: 'Buttons and icons drift toward the pointer as it approaches, then spring back when it leaves. A tactile touch for toolbars and calls to action.',
  },
  category: 'cursor',
  tags: ['magnetic', 'hover', 'pointer', 'button', 'spring', 'interactive'],
  runtime: ['react', 'motion'],
  entry: { file: 'magnetic.tsx', export: 'Magnetic' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'magnetic.tsx', role: 'component' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    {
      key: 'intensity',
      type: 'number',
      label: { 'zh-CN': '吸力', en: 'Pull' },
      hint: { 'zh-CN': '元素跟随指针位移的比例', en: 'How much of the pointer offset the element follows' },
      default: 0.5,
      min: 0.1,
      max: 1,
      step: 0.01,
      safe: [0.25, 0.75],
      group: 'interaction',
    },
    {
      key: 'range',
      type: 'number',
      label: { 'zh-CN': '感应半径', en: 'Reach' },
      hint: { 'zh-CN': '指针距中心多近开始被吸引', en: 'How close the pointer must be to start pulling' },
      default: 120,
      min: 40,
      max: 300,
      step: 1,
      unit: 'px',
      safe: [80, 200],
      group: 'interaction',
    },
    {
      key: 'actionArea',
      type: 'select',
      label: { 'zh-CN': '生效区域', en: 'Active area' },
      default: 'parent',
      options: [
        { value: 'self', label: { 'zh-CN': '元素自身', en: 'The element itself' } },
        { value: 'parent', label: { 'zh-CN': '父容器', en: 'Its parent' } },
        { value: 'global', label: { 'zh-CN': '整个页面', en: 'Whole page' } },
      ],
      group: 'interaction',
    },
    {
      key: 'spring',
      type: 'spring',
      label: { 'zh-CN': '回弹', en: 'Spring' },
      hint: { 'zh-CN': '时长越短越跟手，弹性越大越晃', en: 'Shorter is snappier, more bounce wobbles longer' },
      default: { visualDuration: 0.45, bounce: 0.3 },
      group: 'motion',
    },
  ],
  presets: [
    { id: 'gentle', name: { 'zh-CN': '轻抚', en: 'Gentle' }, values: { intensity: 0.35, range: 140, spring: { visualDuration: 0.6, bounce: 0.15 } } },
    { id: 'rubber', name: { 'zh-CN': '橡皮筋', en: 'Rubber band' }, values: { intensity: 0.7, range: 110, spring: { visualDuration: 0.5, bounce: 0.5 } } },
    { id: 'snap', name: { 'zh-CN': '吸附', en: 'Snap' }, values: { intensity: 0.6, range: 90, spring: { visualDuration: 0.25, bounce: 0.1 } } },
    { id: 'field', name: { 'zh-CN': '力场', en: 'Field' }, values: { intensity: 0.45, range: 240, actionArea: 'global', spring: { visualDuration: 0.7, bounce: 0.2 } } },
  ],
  dependencies: ['motion/react', '@motif/runtime'],
  perf: { webgl: false, maxDpr: 2 },
  a11y: { reducedMotion: 'not-animated' },
  capture: { zoom: 1.8, posterTime: 3.4, loop: 8 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'motion-primitives',
      repo: 'ibelick/motion-primitives',
      sha: '120f64f6ca60348e251f929e9c81f11ccbe45eda',
      paths: ['components/core/magnetic.tsx'],
      spdx: 'MIT',
      copyright: ['Copyright (c) 2024 ibelick'],
    },
    modifications: [
      'framer-motion imports moved to motion/react; the spring is now described with visualDuration and bounce.',
      'Pointer tracking uses a single window pointermove listener (touch and pen included) and measures an untransformed wrapper, so the pull no longer feeds back into its own position; the hover state was removed.',
      'Added reduced-motion handling (upstream has none): the element stays put.',
      'Defaults moved into the generated defaults region.',
    ],
    assets: [],
  },
})
