import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'text-effect',
  status: 'published',
  title: { 'zh-CN': '文字入场', en: 'Text Effect' },
  summary: {
    'zh-CN': '文字按词或按字依次浮现，可选模糊聚焦、上浮、缩放等入场方式，退场时反向收起。适合标题、引言和首屏文案。',
    en: 'Text reveals word by word or letter by letter with blur-focus, rise, scale or fade entrances, and folds back in reverse on exit. Made for headlines, quotes and hero copy.',
  },
  category: 'text',
  tags: ['text', 'reveal', 'stagger', 'blur', 'headline', 'motion'],
  runtime: ['react', 'motion'],
  entry: { file: 'text-effect.tsx', export: 'TextEffect' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'text-effect.tsx', role: 'component' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    {
      key: 'text',
      type: 'text',
      label: { 'zh-CN': '文字', en: 'Text' },
      default: 'Craft the details people feel but never notice.',
      maxLength: 120,
    },
    {
      key: 'preset',
      type: 'select',
      label: { 'zh-CN': '入场方式', en: 'Entrance' },
      default: 'fade-in-blur',
      options: [
        { value: 'fade-in-blur', label: { 'zh-CN': '上浮 + 模糊', en: 'Rise + blur' } },
        { value: 'blur', label: { 'zh-CN': '模糊聚焦', en: 'Blur focus' } },
        { value: 'slide', label: { 'zh-CN': '上浮', en: 'Rise' } },
        { value: 'scale', label: { 'zh-CN': '缩放', en: 'Scale' } },
        { value: 'fade', label: { 'zh-CN': '淡入', en: 'Fade' } },
      ],
    },
    {
      key: 'per',
      type: 'select',
      label: { 'zh-CN': '拆分单位', en: 'Split by' },
      default: 'word',
      options: [
        { value: 'word', label: { 'zh-CN': '按词', en: 'Word' } },
        { value: 'char', label: { 'zh-CN': '按字', en: 'Letter' } },
      ],
    },
    {
      key: 'speedReveal',
      type: 'number',
      label: { 'zh-CN': '出现节奏', en: 'Reveal pace' },
      hint: { 'zh-CN': '越大，相邻两段的间隔越短', en: 'Higher values shorten the gap between segments' },
      default: 0.7,
      min: 0.3,
      max: 3,
      step: 0.05,
      unit: 'x',
      safe: [0.6, 2],
      group: 'motion',
    },
    {
      key: 'speedSegment',
      type: 'number',
      label: { 'zh-CN': '单段速度', en: 'Segment speed' },
      hint: { 'zh-CN': '越大，每个词或字完成得越快', en: 'Higher values finish each word or letter faster' },
      default: 1,
      min: 0.4,
      max: 3,
      step: 0.05,
      unit: 'x',
      safe: [0.6, 2],
      group: 'motion',
    },
    {
      key: 'delay',
      type: 'number',
      label: { 'zh-CN': '起始延迟', en: 'Start delay' },
      default: 0,
      min: 0,
      max: 2,
      step: 0.05,
      unit: 's',
      group: 'motion',
    },
    {
      key: 'blur',
      type: 'number',
      label: { 'zh-CN': '模糊半径', en: 'Blur radius' },
      hint: { 'zh-CN': '对「模糊」类入场生效', en: 'Applies to the blur entrances' },
      default: 12,
      min: 0,
      max: 24,
      step: 1,
      unit: 'px',
      safe: [4, 16],
      group: 'look',
    },
    {
      key: 'distance',
      type: 'number',
      label: { 'zh-CN': '上浮距离', en: 'Rise distance' },
      hint: { 'zh-CN': '对「上浮」类入场生效', en: 'Applies to the rise entrances' },
      default: 20,
      min: 0,
      max: 60,
      step: 1,
      unit: 'px',
      safe: [8, 32],
      group: 'look',
    },
  ],
  presets: [
    {
      id: 'rise',
      name: { 'zh-CN': '浮起', en: 'Rise' },
      values: { preset: 'fade-in-blur', per: 'word', speedReveal: 0.7, speedSegment: 1, blur: 12, distance: 20 },
    },
    {
      id: 'focus',
      name: { 'zh-CN': '聚焦', en: 'Focus' },
      values: { preset: 'blur', per: 'char', speedReveal: 2.2, speedSegment: 0.8, blur: 14 },
    },
    {
      id: 'ripple',
      name: { 'zh-CN': '涟漪', en: 'Ripple' },
      values: { preset: 'slide', per: 'char', speedReveal: 1.8, speedSegment: 1, distance: 14 },
    },
    {
      id: 'pop',
      name: { 'zh-CN': '弹出', en: 'Pop' },
      values: { preset: 'scale', per: 'word', speedReveal: 0.8, speedSegment: 1.3 },
    },
    {
      id: 'hush',
      name: { 'zh-CN': '低语', en: 'Hush' },
      values: { preset: 'fade', per: 'word', speedReveal: 0.6, speedSegment: 0.6, delay: 0.2 },
    },
  ],
  dependencies: ['motion/react', '@motif/runtime'],
  perf: { webgl: false, maxDpr: 2 },
  a11y: { reducedMotion: 'static' },
  capture: { zoom: 1.3, posterTime: 0.85, loop: 8 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'motion-primitives',
      repo: 'ibelick/motion-primitives',
      sha: '120f64f6ca60348e251f929e9c81f11ccbe45eda',
      paths: ['components/core/text-effect.tsx'],
      spdx: 'MIT',
      copyright: ['Copyright (c) 2024 ibelick'],
    },
    modifications: [
      'framer-motion imports moved to motion/react and cn now comes from motif-runtime.',
      'Text comes from a text prop (children still works); blur radius and rise distance became props, and the line mode and custom variants API were removed.',
      'Added reduced-motion handling (upstream has none): the text renders fully visible and static.',
      'Defaults moved into the generated defaults region.',
    ],
    assets: [],
  },
})
