import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'border-trail',
  status: 'published',
  title: { 'zh-CN': '边框流光', en: 'Border Trail' },
  summary: {
    'zh-CN': '一条或几条带亮头的彗尾沿输入框、卡片的边框追逐绕行，可调数量、长度与颜色。适合提示词输入框、聚焦态和强调卡片。',
    en: 'One or several comet trails with bright heads chase each other around the border of an input or card, with adjustable count, length and color. Great for prompt boxes, focus states and highlighted cards.',
  },
  category: 'card',
  tags: ['border', 'trail', 'comet', 'glow', 'input', 'focus', 'css offset-path'],
  runtime: ['react', 'motion', 'css'],
  entry: { file: 'border-trail.tsx', export: 'BorderTrail' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'border-trail.tsx', role: 'component' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    { key: 'color', type: 'color', label: { 'zh-CN': '彗尾颜色', en: 'Trail color' }, default: '#6366f1', group: 'look' },
    { key: 'headColor', type: 'color', label: { 'zh-CN': '亮头颜色', en: 'Head color' }, default: '#c7d2fe', group: 'look' },
    {
      key: 'size',
      type: 'number',
      label: { 'zh-CN': '彗尾长度', en: 'Trail length' },
      default: 120,
      min: 20,
      max: 400,
      step: 1,
      unit: 'px',
      safe: [60, 240],
      group: 'look',
    },
    {
      key: 'borderWidth',
      type: 'number',
      label: { 'zh-CN': '边框粗细', en: 'Border width' },
      default: 2,
      min: 0.5,
      max: 5,
      step: 0.5,
      unit: 'px',
      safe: [1, 3],
      group: 'look',
    },
    {
      key: 'glow',
      type: 'number',
      label: { 'zh-CN': '光晕', en: 'Glow' },
      hint: { 'zh-CN': '边框外溢出的柔光强度', en: 'Soft light spilling past the border' },
      default: 0.6,
      min: 0,
      max: 1,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'count',
      type: 'number',
      label: { 'zh-CN': '彗尾数量', en: 'Trails' },
      hint: { 'zh-CN': '多条彗尾会等距分布', en: 'Several trails are spaced evenly' },
      default: 1,
      min: 1,
      max: 4,
      step: 1,
      group: 'motion',
    },
    {
      key: 'duration',
      type: 'number',
      label: { 'zh-CN': '绕一圈用时', en: 'Loop duration' },
      default: 6,
      min: 1.5,
      max: 20,
      step: 0.1,
      unit: 's',
      safe: [3, 12],
      group: 'motion',
    },
    { key: 'reverse', type: 'boolean', label: { 'zh-CN': '逆时针', en: 'Counter-clockwise' }, default: false, group: 'motion' },
  ],
  presets: [
    { id: 'indigo', name: { 'zh-CN': '靛蓝', en: 'Indigo' }, values: { color: '#6366f1', headColor: '#c7d2fe', size: 120, count: 1, duration: 6 } },
    { id: 'tandem', name: { 'zh-CN': '双星', en: 'Tandem' }, values: { color: '#10b981', headColor: '#a7f3d0', size: 100, count: 2, duration: 8 } },
    { id: 'neon', name: { 'zh-CN': '霓虹', en: 'Neon' }, values: { color: '#ec4899', headColor: '#fbcfe8', size: 160, borderWidth: 2, glow: 0.9, count: 1, duration: 4.5 } },
    { id: 'chase', name: { 'zh-CN': '追逐', en: 'Chase' }, values: { color: '#94a3b8', headColor: '#ffffff', size: 60, borderWidth: 1, glow: 0.3, count: 4, duration: 7 } },
  ],
  dependencies: ['motion/react', '@motif/runtime'],
  perf: { webgl: false, maxDpr: 2 },
  a11y: { reducedMotion: 'static' },
  capture: { zoom: 1.8, posterTime: 1.0, loop: 6 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'motion-primitives',
      repo: 'ibelick/motion-primitives',
      sha: '120f64f6ca60348e251f929e9c81f11ccbe45eda',
      paths: ['components/core/border-trail.tsx'],
      spdx: 'MIT',
      copyright: ['Copyright (c) 2024 ibelick'],
    },
    modifications: [
      'framer-motion imports moved to motion/react and cn now comes from motif-runtime.',
      'The trail color is no longer set through a class: color, head color, length, border width, count, duration and direction are props, and the trail is a gradient from a bright head to a fading tail.',
      'Several evenly spaced trails can circle at once (count) and a blurred glow spills past the border (glow); the transition and onAnimationComplete props were dropped.',
      'Added reduced-motion handling (upstream has none): the trails rest at fixed points along the border instead of moving.',
      'Defaults moved into the generated defaults region.',
    ],
    assets: [],
  },
})
