import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'crt',
  status: 'published',
  title: { 'zh-CN': '弧面显像管', en: 'CRT Tube' },
  summary: {
    'zh-CN': '一块带曲率的老式显像管：扫描线、荧光点阵、色散和辉光俱全，屏幕上可以是终端启动日志、电影倒计时片头、信号故障蓝屏或 8 位街机标题画面。适合做复古科技、极客风格的背景。',
    en: 'A curved CRT tube with scanlines, phosphor triads, chromatic fringing and halation. The screen can show a terminal boot log, a film leader countdown, a signal-fault blue screen or an 8-bit arcade title. A backdrop for retro-tech and hacker aesthetics.',
  },
  category: 'shader',
  tags: ['crt', 'retro', 'scanlines', 'terminal', 'phosphor', 'glitch', 'vhs', 'pixel', 'webgl', 'canvas2d', 'background', 'variants'],
  runtime: ['react', 'webgl', 'canvas2d'],
  entry: { file: 'crt.tsx', export: 'Crt' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'crt.tsx', role: 'component' },
    { path: 'screens.ts', role: 'lib' },
    { path: 'shaders.ts', role: 'shader' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    {
      key: 'variant',
      type: 'select',
      label: { 'zh-CN': '屏幕内容', en: 'Screen' },
      default: 'terminal',
      options: [
        { value: 'terminal', label: { 'zh-CN': '终端日志', en: 'Terminal' } },
        { value: 'cinematic', label: { 'zh-CN': '电影片头', en: 'Film leader' } },
        { value: 'blue-screen', label: { 'zh-CN': '故障蓝屏', en: 'Fault screen' } },
        { value: 'arcade', label: { 'zh-CN': '8 位街机', en: '8-bit arcade' } },
      ],
    },
    { key: 'speed', type: 'number', label: { 'zh-CN': '速度', en: 'Speed' }, default: 1, min: 0.3, max: 2, step: 0.01, unit: 'x', safe: [0.5, 1.5], group: 'motion' },
    {
      key: 'typeSpeed',
      type: 'number',
      label: { 'zh-CN': '打字速度', en: 'Typing speed' },
      hint: { 'zh-CN': '只对终端日志生效', en: 'Terminal screen only' },
      default: 1,
      min: 0.3,
      max: 3,
      step: 0.01,
      group: 'motion',
    },
    {
      key: 'motion',
      type: 'number',
      label: { 'zh-CN': '扫描动态', en: 'Scan motion' },
      hint: { 'zh-CN': '滚动的亮条、扫描线漂移和闪烁的强度', en: 'Strength of the rolling bar, scanline drift and flicker' },
      default: 1,
      min: 0,
      max: 2,
      step: 0.01,
      group: 'look',
    },
    { key: 'brightness', type: 'number', label: { 'zh-CN': '亮度', en: 'Brightness' }, default: 1, min: 0.7, max: 1.5, step: 0.01, group: 'color' },
    { key: 'saturation', type: 'number', label: { 'zh-CN': '饱和度', en: 'Saturation' }, default: 1, min: 0.3, max: 1.6, step: 0.01, group: 'color' },
    {
      key: 'hue',
      type: 'number',
      label: { 'zh-CN': '色相偏移', en: 'Hue shift' },
      default: 0,
      min: -180,
      max: 180,
      step: 1,
      unit: 'deg',
      group: 'color',
    },
  ],
  presets: [
    { id: 'phosphor', name: { 'zh-CN': '绿磷', en: 'Green phosphor' }, values: { variant: 'terminal' } },
    { id: 'amber', name: { 'zh-CN': '琥珀', en: 'Amber' }, values: { variant: 'terminal', hue: -75, saturation: 1.1, typeSpeed: 1.4 } },
    { id: 'leader', name: { 'zh-CN': '片头', en: 'Film leader' }, values: { variant: 'cinematic' } },
    { id: 'fault', name: { 'zh-CN': '信号故障', en: 'Signal fault' }, values: { variant: 'blue-screen', motion: 1.4 } },
    { id: 'arcade', name: { 'zh-CN': '街机', en: 'Arcade' }, values: { variant: 'arcade', brightness: 1.1 } },
  ],
  dependencies: ['@motif/runtime'],
  perf: { webgl: true, maxDpr: 1.5 },
  a11y: { reducedMotion: 'static' },
  capture: { posterTime: 12 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'threeui',
      repo: 'MengTo/threeui',
      sha: '68802d5428071ada5c20db8094b1649e6bb770ed',
      paths: ['src/shaders/crt/CrtBackground.tsx', 'src/shaders/crt/crtRenderer.ts', 'src/shaders/crt/crtScreens.ts', 'src/shaders/crt/crtShaders.ts'],
      spdx: 'MIT',
      copyright: ['Copyright (c) 2026 Meng To'],
      origin: 'Neuform export',
    },
    modifications: [
      'The render loop now uses motif-runtime: pauses offscreen and in hidden tabs, renders a static frame under reduced motion (the terminal shows its full log), and caps DPR at 1.5 and the buffer at 2.4 megapixels.',
      'Handles WebGL context loss and restore, and releases the context on unmount.',
      'The terminal typing is driven by animation time instead of a per-frame counter, and loops (type, hold, restart); its boot log is reworded to remove references to a film franchise.',
      'The 8-bit screen variant is renamed from the upstream id to arcade and its credit line reads (C) 1987 MOTIF instead of the upstream name.',
      'The renderer is folded into the component; opacity is dropped as a parameter and screen painters are otherwise unchanged.',
      'Defaults moved into the generated defaults region; children can be layered on top.',
    ],
    assets: [],
  },
})
