import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'liquid-form',
  status: 'published',
  title: { 'zh-CN': '液态银', en: 'Liquid Form' },
  summary: {
    'zh-CN': '画面中央一团光线步进渲染的液态金属，表面随噪声缓慢起伏，反射随指针偏转。适合做产品首屏的视觉焦点。',
    en: 'A ray-marched blob of liquid silver at the center, its surface slowly rippling with noise and its reflections following the pointer. A focal point for product heroes.',
  },
  kind: 'effect',
  category: 'shader',
  tags: ['raymarching', 'metal', 'chrome', 'webgl', 'hero', 'interactive'],
  runtime: ['react', 'webgl'],
  entry: { file: 'liquid-form.tsx', export: 'LiquidForm' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'liquid-form.tsx', role: 'component' },
    { path: 'shaders.ts', role: 'shader' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    { key: 'speed', type: 'number', label: { 'zh-CN': '速度', en: 'Speed' }, default: 1, min: 0, max: 2, step: 0.01, unit: 'x', safe: [0.2, 1.5] },
    {
      key: 'morph',
      type: 'number',
      label: { 'zh-CN': '形变', en: 'Morph' },
      hint: { 'zh-CN': '表面起伏的幅度', en: 'How much the surface ripples' },
      default: 1,
      min: 0,
      max: 2,
      step: 0.01,
    },
    {
      key: 'noiseScale',
      type: 'number',
      label: { 'zh-CN': '噪声尺度', en: 'Noise scale' },
      hint: { 'zh-CN': '越大起伏越细碎', en: 'Higher values make finer ripples' },
      default: 1,
      min: 0.4,
      max: 2.5,
      step: 0.01,
    },
    {
      key: 'mouseAmount',
      type: 'number',
      label: { 'zh-CN': '指针影响', en: 'Pointer influence' },
      default: 0.15,
      min: 0,
      max: 0.4,
      step: 0.01,
      group: 'interaction',
    },
    { key: 'metal', type: 'number', label: { 'zh-CN': '金属感', en: 'Metalness' }, default: 1, min: 0.3, max: 1.8, step: 0.01, group: 'look' },
    {
      key: 'camera',
      type: 'number',
      label: { 'zh-CN': '镜头距离', en: 'Camera distance' },
      default: 5.5,
      min: 4,
      max: 7,
      step: 0.1,
      group: 'look',
    },
    { key: 'tintHue', type: 'number', label: { 'zh-CN': '色调', en: 'Tint hue' }, default: 220, min: 0, max: 360, step: 1, unit: 'deg', group: 'tint' },
    { key: 'tintAmount', type: 'number', label: { 'zh-CN': '着色强度', en: 'Tint amount' }, default: 0, min: 0, max: 1, step: 0.01, group: 'tint' },
  ],
  presets: [
    { id: 'mercury', name: { 'zh-CN': '水银', en: 'Mercury' }, values: { speed: 0.6, morph: 1.3, metal: 1.2 } },
    { id: 'rose-gold', name: { 'zh-CN': '玫瑰金', en: 'Rose gold' }, values: { tintHue: 10, tintAmount: 0.35, metal: 1.3 } },
    { id: 'cobalt', name: { 'zh-CN': '钴蓝', en: 'Cobalt' }, values: { tintHue: 225, tintAmount: 0.55, morph: 0.8, speed: 0.8 } },
    { id: 'restless', name: { 'zh-CN': '躁动', en: 'Restless' }, values: { speed: 1.6, morph: 1.8, noiseScale: 1.8, mouseAmount: 0.3 } },
  ],
  dependencies: ['@motif/runtime'],
  perf: { webgl: true, maxDpr: 1.5 },
  a11y: { reducedMotion: 'static' },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'threeui',
      repo: 'MengTo/threeui',
      sha: '68802d5428071ada5c20db8094b1649e6bb770ed',
      paths: ['src/shaders/liquid-form/LiquidFormBackground.tsx', 'src/shaders/liquid-form/liquidFormShaders.ts'],
      spdx: 'MIT',
      copyright: ['Copyright (c) 2026 Meng To'],
      origin: 'Neuform export (as declared by threeui); the simplex noise is Ashima Arts’ MIT-licensed webgl-noise.',
    },
    modifications: [
      'The render loop now uses motif-runtime: pauses offscreen and in hidden tabs, renders a static frame under reduced motion, and caps DPR at 1.5.',
      'Handles WebGL context loss and restore, and releases the context on unmount.',
      'Children can be layered on top; defaults moved into the generated defaults region.',
    ],
    assets: [],
  },
})
