import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'metaballs',
  status: 'published',
  title: { "zh-CN": '融球', en: 'Metaballs' },
  summary: {
    "zh-CN": '一群彩色的球体靠近时互相融合、分开时又拉出细丝，像熔岩灯。适合做首屏背景。',
    en: 'Colorful blobs melt together when close and pull apart into strands, like a lava lamp. Made for hero backgrounds.',
  },
  kind: 'effect',
  category: 'background',
  tags: ['metaballs', 'blobs', 'lava', 'shader', 'webgl', 'background'],
  runtime: ['react', 'webgl2'],
  entry: { file: 'metaballs.tsx', export: 'MetaballsBackground' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'metaballs.tsx', role: 'component' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    {
      key: 'colors',
      type: 'palette',
      label: { "zh-CN": '颜色', en: 'Colors' },
      hint: { "zh-CN": '每个球从中取色，最多 8 个', en: 'Each blob takes one of these, up to 8' },
      default: ['#6e33cc', '#ff5500', '#ffc105', '#ffc800', '#f585ff'],
      minItems: 1,
      maxItems: 8,
    },
    { key: 'colorBack', type: 'color', label: { "zh-CN": '底色', en: 'Background' }, default: '#000000' },
    {
      key: 'count',
      type: 'number',
      label: { "zh-CN": '数量', en: 'Count' },
      default: 12,
      min: 2,
      max: 20,
      step: 1,
      group: 'look',
    },
    {
      key: 'size',
      type: 'number',
      label: { "zh-CN": '大小', en: 'Size' },
      default: 0.6,
      min: 0.1,
      max: 1,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'speed',
      type: 'number',
      label: { "zh-CN": '速度', en: 'Speed' },
      default: 1,
      min: 0,
      max: 3,
      step: 0.01,
      safe: [0.2, 2],
      unit: 'x',
      group: 'motion',
    },
    {
      key: 'scale',
      type: 'number',
      label: { "zh-CN": '缩放', en: 'Scale' },
      default: 1,
      min: 0.4,
      max: 4,
      step: 0.01,
      safe: [0.6, 3],
      unit: 'x',
      group: 'layout',
    },
    {
      key: 'rotation',
      type: 'number',
      label: { "zh-CN": '旋转', en: 'Rotation' },
      default: 0,
      min: 0,
      max: 360,
      step: 1,
      unit: 'deg',
      group: 'layout',
    },
  ],
  presets: [
    {
      id: 'lava',
      name: { "zh-CN": '熔岩', en: 'Lava' },
      values: {
        colors: ['#6e33cc', '#ff5500', '#ffc105', '#ffc800', '#f585ff'],
        colorBack: '#000000',
        count: 12,
        size: 0.6,
        speed: 1,
        scale: 1,
        rotation: 0,
      },
    },
    {
      id: 'solar',
      name: { "zh-CN": '日晕', en: 'Solar' },
      values: {
        colors: ['#ffc800', '#ff5500', '#ffc105'],
        colorBack: '#102f84',
        count: 7,
        size: 0.75,
        speed: 1,
        scale: 1,
        rotation: 0,
      },
    },
    {
      id: 'nightbloom',
      name: { "zh-CN": '夜绽', en: 'Night bloom' },
      values: {
        colors: ['#ae00ff', '#00ff95', '#ffc105'],
        colorBack: '#2a273f',
        count: 13,
        size: 0.81,
        speed: 0.5,
        scale: 4,
        rotation: 0,
      },
    },
    {
      id: 'ink',
      name: { "zh-CN": '墨滴', en: 'Ink drops' },
      values: { colors: ['#000000'], colorBack: '#ffffff', count: 18, size: 0.1, speed: 2, scale: 1, rotation: 0 },
    },
    {
      id: 'mint',
      name: { "zh-CN": '薄荷', en: 'Mint' },
      values: {
        colors: ['#22d3a5', '#7cf3d1', '#e6fff7'],
        colorBack: '#062b2b',
        count: 9,
        size: 0.7,
        speed: 0.7,
        scale: 1.2,
        rotation: 0,
      },
    },
  ],
  dependencies: ['@paper-design/shaders-react', '@motif/runtime'],
  perf: { webgl: true, maxDpr: 1.5 },
  a11y: { reducedMotion: 'static' },
  capture: { posterTime: 2 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'paper-shaders',
      repo: 'paper-design/shaders',
      sha: '43cd68db79fa0b1759f72ffc941b3238e2a3954c',
      paths: ['packages/shaders-react/src/shaders/metaballs.tsx', 'docs/src/shader-defs/metaballs-def.ts'],
      spdx: 'Apache-2.0',
      copyright: ['Paper Shaders (https://shaders.paper.design)'],
    },
    modifications: ['Wrapped the Paper Metaballs component as a full-bleed background that can hold children.', 'Parameter ranges adapted from the Paper docs; Lava (default), Solar, Night bloom (upstream Background, without the horizontal offset) and Ink drops (opaque white base) follow the upstream presets; Mint is Motif’s.', 'Renders a static frame when the user prefers reduced motion.'],
    assets: [],
  },
})
