import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'style-8bit',
  status: 'published',
  title: { 'zh-CN': '8 位像素', en: '8-Bit Pixel' },
  summary: {
    'zh-CN': '缺角的像素描边、Press Start 2P 标题、按帧步进的动效和 16 色调色板：每个控件都像街机菜单里的一个方块。适合游戏、独立开发者主页和怀旧活动页。',
    en: 'Notched pixel outlines, Press Start 2P headings, stepped motion and a 16-color palette: every control is a block from an arcade menu. For games, indie dev sites and nostalgic event pages.',
  },
  kind: 'style',
  category: 'retro',
  tags: ['8-bit', 'pixel', 'arcade', 'retro game', 'press start 2p', 'tokens', 'design system'],
  runtime: ['react', 'css'],
  entry: { file: 'style-8bit.tsx', export: 'EightBit' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'style-8bit.tsx', role: 'component' },
    { path: 'style-8bit.css', role: 'style' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    {
      key: 'accent',
      type: 'color',
      group: 'look',
      label: { 'zh-CN': '强调色', en: 'Accent color' },
      hint: { 'zh-CN': '按钮、选中态和标签页的主色', en: 'Buttons, selected tabs and highlights' },
      default: '#ef7d57',
    },
    {
      key: 'pixel',
      type: 'number',
      group: 'shape',
      label: { 'zh-CN': '像素单位', en: 'Pixel size' },
      hint: { 'zh-CN': '描边和缺角的粗细', en: 'Outline and notch thickness' },
      default: 4,
      min: 2,
      max: 6,
      step: 1,
      unit: 'px',
      safe: [3, 5],
    },
    {
      key: 'fontPairing',
      type: 'select',
      group: 'type',
      label: { 'zh-CN': '字体搭配', en: 'Font pairing' },
      default: 'press-vt',
      options: [
        { value: 'press-vt', label: { 'zh-CN': 'Press Start + VT323', en: 'Press Start + VT323' } },
        { value: 'press-plex', label: { 'zh-CN': 'Press Start + Plex Mono', en: 'Press Start + Plex Mono' } },
        { value: 'vt-mono', label: { 'zh-CN': 'VT323 + JetBrains Mono', en: 'VT323 + JetBrains Mono' } },
      ],
    },
    {
      key: 'shadeDepth',
      type: 'number',
      group: 'shape',
      label: { 'zh-CN': '高光与阴影厚度', en: 'Bevel depth' },
      default: 4,
      min: 0,
      max: 8,
      step: 1,
      unit: 'px',
      safe: [2, 6],
    },
    {
      key: 'density',
      type: 'number',
      group: 'layout',
      label: { 'zh-CN': '疏密', en: 'Density' },
      default: 1,
      min: 0.85,
      max: 1.2,
      step: 0.05,
      unit: 'x',
      safe: [0.9, 1.15],
    },
    {
      key: 'mode',
      type: 'select',
      group: 'look',
      label: { 'zh-CN': '昼夜', en: 'Palette mode' },
      default: 'night',
      options: [
        { value: 'night', label: { 'zh-CN': '夜间', en: 'Night' } },
        { value: 'day', label: { 'zh-CN': '日间', en: 'Day' } },
      ],
    },
  ],
  presets: [
    {
      id: 'arcade-night',
      name: { 'zh-CN': '街机之夜', en: 'Arcade night' },
      values: { accent: '#ef7d57', pixel: 4, shadeDepth: 4, density: 1, fontPairing: 'press-vt', mode: 'night' },
    },
    {
      id: 'gameboy-green',
      name: { 'zh-CN': '掌机绿', en: 'Handheld green' },
      values: { accent: '#a7f070', pixel: 4, shadeDepth: 4, density: 1, fontPairing: 'press-vt', mode: 'night' },
    },
    {
      id: 'cyan-terminal',
      name: { 'zh-CN': '青色终端', en: 'Cyan console' },
      values: { accent: '#41a6f6', pixel: 3, shadeDepth: 3, density: 0.95, fontPairing: 'press-plex', mode: 'night' },
    },
    {
      id: 'paper-day',
      name: { 'zh-CN': '纸质日间', en: 'Paper day' },
      values: { accent: '#b13e53', pixel: 4, shadeDepth: 4, density: 1.05, fontPairing: 'press-vt', mode: 'day' },
    },
    {
      id: 'chunky',
      name: { 'zh-CN': '大颗粒', en: 'Chunky' },
      values: { accent: '#ffcd75', pixel: 6, shadeDepth: 6, density: 1.1, fontPairing: 'vt-mono', mode: 'night' },
    },
  ],
  dependencies: ['@motif/runtime'],
  fonts: ['Press Start 2P', 'VT323', 'IBM Plex Mono', 'JetBrains Mono Variable'],
  guidance: {
    use: [
      'Use for games, indie-dev portfolios, hackathons, retro tech events and playful tools that can lean on arcade nostalgia.',
      'Avoid for long-form reading, dense data tables or serious financial and medical products.',
    ],
    rules: [
      'Palette: a 16-color sweetie-style palette. Night mode is about 60% deep navy ground (#1a1c2c) with 25% slightly lighter panels (#262b44), 10% one accent, 5% highlight colors (yellow, pink, lime, cyan). Day mode swaps to warm paper with navy ink. Outlines are always the ink color, never gray.',
      'Everything is built on a pixel unit (2-6px). Outlines are notched: four bars with the corner pixel left empty, never border-radius. Panels get a light top edge and a darker bottom edge one unit thick, and cards get a hard drop shadow two units offset. No blur, no gradients other than hard-stop patterns, no rounded corners.',
      'Typography: Press Start 2P (or VT323) uppercase for headings, buttons, labels and badges at small sizes (8-13px, line-height 1.5-1.6), never for paragraphs. Body copy uses VT323 (larger, ~22px) or a mono face. Disable font smoothing effects; keep letter-spacing default.',
      'Motion is stepped: transitions use steps(2-3) and last 80ms, presses move the box down by one pixel unit and remove the bottom shade. A block caret may blink with steps(1). Nothing eases, fades, springs or scales; reduced motion stops the blink.',
      'Icons and art are pixel sprites drawn on a grid (SVG rects with crispEdges), 5-8 cells wide, in palette colors. Do not use smooth vector icons, photos or emoji.',
      'Toggles read ON / OFF in the font, alerts use one-letter glyph blocks (i, !, OK). Focus is a dotted outline in yellow.',
      'Do not use drop shadows with blur, translucent glass, gradients, rounded corners, thin 1px lines, or more than five hues on one screen. Do not copy characters or sprites from real games.',
    ],
  },
  perf: { webgl: false, maxDpr: 2 },
  a11y: { reducedMotion: 'static' },
  capture: { scroll: true, posterTime: 0.5, loop: 8 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: '8bitcn',
      repo: 'TheOrcDev/8bitcn-ui',
      sha: '37031e37d6f68aad4b147ce699b70dba22af7841',
      paths: ['components/ui/8bit/styles/retro.css', 'components/ui/8bit/button.tsx', 'components/ui/8bit/card.tsx'],
      spdx: 'MIT',
      copyright: ['Copyright (c) 2025 8bitcn'],
    },
    modifications: [
      'Kept the upstream look (Press Start 2P, line-height 1.5, pixelated corners built from bars around the box, a 1.5-unit bottom shade on buttons) but rebuilt it as pure CSS: the notched outline is four box-shadow bars and the fill is a plus-shaped stack of gradients, so no decoration spans are needed.',
      'The pixel unit, shade depth, palette mode (night / day), accent and font pairing are parameters wired to CSS variables on one .bit-root element instead of Tailwind classes.',
      'Replaced the shadcn/Radix components with plain React primitives (button, card, field, badge, tabs, alert, ON/OFF switch) and a pixel-sprite helper in the demo; the alien, ship, heart and coin sprites are generic shapes drawn for this item.',
      'Press Start 2P and VT323 come from the Motif self-hosted font list (OFL); the upstream Google Fonts import is not used. The palette is inspired by the CC0 Sweetie 16 palette; no upstream screenshots or assets are included.',
    ],
    assets: [],
  },
})
