import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'hero-dithering-orb',
  status: 'published',
  title: { 'zh-CN': '抖动光球首屏', en: 'Dithering Orb Hero' },
  summary: {
    'zh-CN': '左侧标题与行动按钮，右侧是一颗由 4×4 抖动像素组成的缓慢旋转光球，叠着一张用 JSX 画的追踪面板。适合开发者工具、可观测性和 AI 基础设施的官网首屏。',
    en: 'Headline and calls to action on the left, a slowly turning orb of 4×4 dithered pixels on the right with a JSX-drawn trace panel floating over it. Made for developer tools, observability and AI infrastructure landing pages.',
  },
  kind: 'section',
  category: 'hero',
  tags: ['hero', 'dithering', 'shader', 'orb', 'developer tools', 'dark'],
  runtime: ['react', 'motion', 'webgl'],
  entry: { file: 'hero-dithering-orb.tsx', export: 'HeroDitheringOrb' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'hero-dithering-orb.tsx', role: 'component' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    { key: 'brand', type: 'text', label: { 'zh-CN': '品牌名', en: 'Brand name' }, default: 'Halcyon', maxLength: 18, group: 'content' },
    { key: 'headline', type: 'text', label: { 'zh-CN': '主标题', en: 'Headline' }, default: 'Every deploy, traced end to end', maxLength: 64, group: 'content' },
    {
      key: 'subline',
      type: 'text',
      label: { 'zh-CN': '副标题', en: 'Subline' },
      default: 'Halcyon stitches logs, traces and rollbacks into one timeline, so the 3 a.m. page takes four minutes instead of forty.',
      maxLength: 160,
      group: 'content',
    },
    { key: 'cta', type: 'text', label: { 'zh-CN': '主按钮文案', en: 'Button label' }, default: 'Start free trial', maxLength: 24, group: 'content' },
    { key: 'accent', type: 'color', label: { 'zh-CN': '主色', en: 'Accent color' }, default: '#22d3ee', group: 'look' },
    {
      key: 'tone',
      type: 'select',
      label: { 'zh-CN': '明暗', en: 'Tone' },
      default: 'dark',
      options: [
        { value: 'dark', label: { 'zh-CN': '深色', en: 'Dark' } },
        { value: 'light', label: { 'zh-CN': '浅色', en: 'Light' } },
      ],
      group: 'look',
    },
    {
      key: 'font',
      type: 'select',
      label: { 'zh-CN': '标题字体', en: 'Heading font' },
      default: 'geist',
      options: [
        { value: 'geist', label: { 'zh-CN': 'Geist 无衬线', en: 'Geist sans' } },
        { value: 'grotesk', label: { 'zh-CN': 'Space Grotesk', en: 'Space Grotesk' } },
        { value: 'serif', label: { 'zh-CN': 'Instrument 衬线', en: 'Instrument serif' } },
      ],
      group: 'look',
    },
    { key: 'radius', type: 'number', label: { 'zh-CN': '按钮圆角', en: 'Button radius' }, default: 12, min: 0, max: 28, step: 1, unit: 'px', safe: [6, 20], group: 'look' },
    {
      key: 'layout',
      type: 'select',
      label: { 'zh-CN': '布局', en: 'Layout' },
      default: 'split',
      options: [
        { value: 'split', label: { 'zh-CN': '左文右球', en: 'Split' } },
        { value: 'centered', label: { 'zh-CN': '居中', en: 'Centered' } },
      ],
      group: 'layout',
    },
    {
      key: 'shape',
      type: 'select',
      label: { 'zh-CN': '光球形态', en: 'Orb shape' },
      default: 'swirl',
      options: [
        { value: 'swirl', label: { 'zh-CN': '旋涡', en: 'Swirl' } },
        { value: 'sphere', label: { 'zh-CN': '球体', en: 'Sphere' } },
        { value: 'warp', label: { 'zh-CN': '扭曲', en: 'Warp' } },
        { value: 'ripple', label: { 'zh-CN': '涟漪', en: 'Ripple' } },
      ],
      group: 'motion',
    },
    { key: 'pixel', type: 'number', label: { 'zh-CN': '像素大小', en: 'Pixel size' }, default: 2, min: 1, max: 6, step: 0.5, unit: 'px', safe: [1.5, 4], group: 'motion' },
    { key: 'speed', type: 'number', label: { 'zh-CN': '流动速度', en: 'Speed' }, default: 0.8, min: 0.1, max: 2, step: 0.1, safe: [0.4, 1.4], group: 'motion' },
  ],
  presets: [
    { id: 'tidewater', name: { 'zh-CN': '潮汐', en: 'Tidewater' }, values: {} },
    { id: 'ember', name: { 'zh-CN': '余烬', en: 'Ember' }, values: { accent: '#ff7a3d', shape: 'sphere', font: 'grotesk', brand: 'Kiln' } },
    { id: 'paper', name: { 'zh-CN': '纸本', en: 'Paper' }, values: { tone: 'light', accent: '#2f3bff', font: 'serif', shape: 'warp', layout: 'centered', pixel: 2.5 } },
    { id: 'moss', name: { 'zh-CN': '苔原', en: 'Moss' }, values: { accent: '#a3e635', shape: 'ripple', speed: 0.5 } },
  ],
  dependencies: ['@paper-design/shaders-react', 'motion/react', '@motif/runtime'],
  fonts: ['Geist Variable', 'Space Grotesk Variable', 'Instrument Serif'],
  guidance: {
    use: ['Use as the first screen of a developer-tool or infrastructure landing page. Keep the headline under ten words.'],
    rules: [
      'Keep the orb the single focal graphic: do not add a second shader or a background image next to it.',
      'Use one accent color; the dithering, badge and button all take it from the accent param.',
      'Headline and subline are content params, do not hard-code copy inside the component.',
    ],
  },
  perf: { webgl: true, maxDpr: 2 },
  a11y: { reducedMotion: 'static' },
  capture: { posterTime: 1.6, loop: 6 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'cult-ui',
      repo: 'nolly-studio/cult-ui',
      sha: 'ee98a5dd2e319b63cc2e707dd968d6af04209b7e',
      paths: ['apps/www/registry/default/ui/hero-dithering.tsx'],
      spdx: 'MIT',
      copyright: ['Copyright (c) 2023 Jordan-Gilliam'],
    },
    modifications: [
      'Kept the idea of a Dithering shader orb beside the headline; the layout, navbar, badge and copy were rewritten and the AI SDK / Next.js badges and links were removed.',
      'Added a JSX trace panel and latency chip over the orb, light and dark tones, a centered layout, heading font choices and content params.',
      'Shader speed is 0 and the frame fixed when the user prefers reduced motion; framer-style entrance animations are skipped then.',
      'Replaced shadcn Button and Badge with inline-styled elements, lucide icons with inline SVG, and the brand mark with an invented one.',
    ],
    assets: [],
  },
})
