import { defineItem } from '@motif/schema'

const accentOption = (value: string, zh: string, en: string) => ({ value, label: { 'zh-CN': zh, en } })

export default defineItem({
  schemaVersion: 1,
  slug: 'style-soft-pastel',
  status: 'published',
  title: { 'zh-CN': '柔和粉彩', en: 'Soft Pastel' },
  summary: {
    'zh-CN': '基于 Catppuccin 调色板的圆润风格：粉彩底色的卡片、按钮底部一道会被按下去的厚边、圆点纸背景。四种风味（一浅三深）、九种强调色，适合习惯、学习、生活方式类产品和面向个人的小工具。',
    en: 'A rounded, friendly style on the Catppuccin palette: pastel-tinted cards, buttons on a thick edge that presses down, a dotted-paper backdrop. Four flavors (one light, three dark) and nine accents, for habit, learning and lifestyle apps.',
  },
  kind: 'style',
  category: 'playful',
  tags: ['pastel', 'catppuccin', 'soft', 'rounded', 'friendly', 'cute'],
  runtime: ['react', 'css'],
  entry: { file: 'style-soft-pastel.tsx', export: 'StyleSoftPastel' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'light' },
  files: [
    { path: 'style-soft-pastel.tsx', role: 'component' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    {
      key: 'flavor',
      type: 'select',
      group: 'look',
      label: { 'zh-CN': '风味', en: 'Flavor' },
      hint: { 'zh-CN': 'Latte 为浅色，其余三档为深色', en: 'Latte is light; the other three are dark' },
      default: 'latte',
      options: [accentOption('latte', 'Latte（浅）', 'Latte (light)'), accentOption('frappe', 'Frappé', 'Frappé'), accentOption('macchiato', 'Macchiato', 'Macchiato'), accentOption('mocha', 'Mocha（最深）', 'Mocha (darkest)')],
    },
    {
      key: 'accent',
      type: 'select',
      group: 'look',
      label: { 'zh-CN': '强调色', en: 'Accent' },
      default: 'mauve',
      options: [
        accentOption('mauve', '紫藤 Mauve', 'Mauve'),
        accentOption('pink', '粉 Pink', 'Pink'),
        accentOption('flamingo', '火烈鸟 Flamingo', 'Flamingo'),
        accentOption('peach', '蜜桃 Peach', 'Peach'),
        accentOption('yellow', '奶黄 Yellow', 'Yellow'),
        accentOption('green', '嫩绿 Green', 'Green'),
        accentOption('teal', '青 Teal', 'Teal'),
        accentOption('blue', '蓝 Blue', 'Blue'),
        accentOption('lavender', '薰衣草 Lavender', 'Lavender'),
      ],
    },
    { key: 'radius', type: 'number', group: 'shape', label: { 'zh-CN': '圆角', en: 'Radius' }, default: 20, min: 10, max: 32, step: 1, unit: 'px', safe: [14, 28] },
    { key: 'borderWidth', type: 'number', group: 'shape', label: { 'zh-CN': '描边粗细', en: 'Border width' }, default: 2, min: 1, max: 3, step: 0.5, unit: 'px', safe: [1.5, 2.5] },
    { key: 'depth', type: 'number', group: 'shape', label: { 'zh-CN': '厚边与阴影深度', en: 'Edge and shadow depth' }, hint: { 'zh-CN': '按钮底边的厚度和卡片阴影的柔和程度', en: 'Thickness of the button edge and softness of card shadows' }, default: 0.6, min: 0, max: 1, step: 0.05, safe: [0.3, 0.9] },
    {
      key: 'fontPairing',
      type: 'select',
      group: 'type',
      label: { 'zh-CN': '字体搭配', en: 'Font pairing' },
      default: 'bricolage',
      options: [
        accentOption('bricolage', 'Bricolage Grotesque + Plus Jakarta Sans', 'Bricolage Grotesque + Plus Jakarta Sans'),
        accentOption('outfit', 'Outfit', 'Outfit'),
        accentOption('fraunces', 'Fraunces + Manrope（软衬线）', 'Fraunces + Manrope (soft serif)'),
        accentOption('manrope', 'Manrope', 'Manrope'),
      ],
    },
  ],
  presets: [
    { id: 'marshmallow', name: { 'zh-CN': '棉花糖', en: 'Marshmallow' }, values: { flavor: 'latte', accent: 'mauve', radius: 20, borderWidth: 2, depth: 0.6, fontPairing: 'bricolage' } },
    { id: 'sorbet', name: { 'zh-CN': '果子露', en: 'Sorbet' }, values: { flavor: 'latte', accent: 'peach', radius: 26, borderWidth: 2, depth: 0.7, fontPairing: 'outfit' } },
    { id: 'lilac-dusk', name: { 'zh-CN': '暮紫', en: 'Lilac dusk' }, values: { flavor: 'macchiato', accent: 'mauve', radius: 22, borderWidth: 2, depth: 0.6, fontPairing: 'bricolage' } },
    { id: 'midnight-mint', name: { 'zh-CN': '午夜薄荷', en: 'Midnight mint' }, values: { flavor: 'mocha', accent: 'teal', radius: 16, borderWidth: 2, depth: 0.5, fontPairing: 'manrope' } },
    { id: 'storybook', name: { 'zh-CN': '绘本', en: 'Storybook' }, values: { flavor: 'frappe', accent: 'flamingo', radius: 28, borderWidth: 2.5, depth: 0.8, fontPairing: 'fraunces' } },
  ],
  dependencies: ['@motif/runtime'],
  fonts: ['Bricolage Grotesque Variable', 'Plus Jakarta Sans Variable', 'Outfit Variable', 'Fraunces Variable', 'Manrope Variable', 'JetBrains Mono Variable'],
  guidance: {
    use: [
      'Use for friendly consumer products: habit and wellness trackers, learning apps, kids and family tools, personal dashboards, indie product sites that want warmth over authority.',
      'Avoid for finance, security or enterprise admin surfaces where a playful tone undermines trust.',
    ],
    rules: [
      'Palette is Catppuccin, nothing else. Use the named tokens (base, mantle, crust for surfaces; surface0-2 and overlay0-2 for lines; text, subtext1, subtext0 for type) and pick one accent from the 14 named colours. Never invent hex values or mix flavors on one page.',
      'Colour ratio: 70% base/mantle, 20% pastel tints (an accent at 16 to 22% over base), 10% saturated accent. The saturated accent is reserved for the primary button, the active tab or switch and one focal illustration.',
      'Cards are pastel-tinted rather than white: background is a named colour at 18% over base with a border of the same colour at 44%. Use at most three different tints in one viewport and vary them by meaning, not decoration.',
      'Buttons have a solid bottom edge (1px + 4px x depth) in a darker mix of their colour and no blur; hover lifts 2px, active presses the button down onto its edge. Never add a glow.',
      'Shapes are round: card radius 20px, controls 72% of that, chips and switches fully rounded. Borders are 2px and always visible; a card without a border looks unfinished.',
      'Shadows are soft and tinted with the accent mixed into crust, never neutral black. Shadow depth controls both the card shadow and the button edge thickness.',
      'Type: a rounded or friendly grotesk for headings at 700 weight and -0.03em tracking, a humanist sans for body. Highlight one word per headline with the marker underline (.cp-hl). Body text is subtext0, headings are text.',
      'Text on tinted surfaces uses the tone mixed 62% with text colour so pastel chips stay readable. Check contrast on Latte: accent text uses accent-ink, a darker mix.',
      'Motion is springy and short (140 to 320ms with a slight overshoot). Small celebratory moments are fine; nothing loops. Respect prefers-reduced-motion.',
      'Background is the base colour with a faint dot grid (overlay0 at 30%, 24px pitch). Decorative rotation of up to 3 degrees is allowed on showcase cards only, never on forms.',
      'Forbidden: gradients on buttons, pure black or white, neon colours, sharp 0-radius corners, drop shadows without tint, more than one saturated accent.',
    ],
  },
  perf: { webgl: false, maxDpr: 2 },
  a11y: { reducedMotion: 'static' },
  capture: { scroll: true, posterTime: 0.5, loop: 8 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'catppuccin',
      repo: 'catppuccin/catppuccin',
      sha: 'd09787dd98ca6fba08af5ef2ae94a7e09f17daca',
      paths: ['README.md'],
      spdx: 'MIT',
      copyright: ['Copyright (c) 2021 Catppuccin'],
    },
    modifications: [
      'Palette values for Latte, Frappé, Macchiato and Mocha are taken from the palette tables in the upstream README and left unchanged.',
      'Everything else (tokens, primitives, tinted cards, chunky edge buttons, style sheet) is original Motif design built on those colours.',
    ],
    assets: [],
  },
})
