import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'style-classic-desktop',
  status: 'published',
  title: { 'zh-CN': '经典桌面', en: 'Classic Desktop' },
  summary: {
    'zh-CN': '灰色斜面按钮、海军蓝标题栏、凹陷的输入框和青色桌面：老式窗口系统的手感，没有任何操作系统的图标或标志。适合作品集彩蛋、工具站和怀旧产品页。',
    en: 'Gray bevels, a navy title bar, sunken fields and a teal desktop: the tactile feel of an early windowing desktop, with no operating-system icons or logos. For portfolio easter eggs, tool sites and nostalgic products.',
  },
  kind: 'style',
  category: 'retro',
  tags: ['classic desktop', 'bevel', 'window', 'win98', 'retro ui', 'tokens', 'design system'],
  runtime: ['react', 'css'],
  entry: { file: 'style-classic-desktop.tsx', export: 'ClassicDesktop' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'style-classic-desktop.tsx', role: 'component' },
    { path: 'style-classic-desktop.css', role: 'style' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    {
      key: 'accent',
      type: 'color',
      group: 'look',
      label: { 'zh-CN': '标题栏颜色', en: 'Title bar color' },
      hint: { 'zh-CN': '也用于选中态、进度条和高亮', en: 'Also used for selection, progress and highlights' },
      default: '#0a2a7a',
    },
    {
      key: 'desktop',
      type: 'color',
      group: 'look',
      label: { 'zh-CN': '桌面颜色', en: 'Desktop color' },
      default: '#008080',
    },
    {
      key: 'bevel',
      type: 'number',
      group: 'shape',
      label: { 'zh-CN': '斜面粗细', en: 'Bevel thickness' },
      default: 1,
      min: 1,
      max: 3,
      step: 1,
      unit: 'px',
      safe: [1, 2],
    },
    {
      key: 'radius',
      type: 'number',
      group: 'shape',
      label: { 'zh-CN': '圆角', en: 'Corner radius' },
      default: 0,
      min: 0,
      max: 8,
      step: 1,
      unit: 'px',
      safe: [0, 6],
    },
    {
      key: 'fontPairing',
      type: 'select',
      group: 'type',
      label: { 'zh-CN': '字体搭配', en: 'Font pairing' },
      default: 'plex-sans',
      options: [
        { value: 'plex-sans', label: { 'zh-CN': 'IBM Plex Sans', en: 'IBM Plex Sans' } },
        { value: 'geist', label: { 'zh-CN': 'Geist', en: 'Geist' } },
        { value: 'plex-mono', label: { 'zh-CN': 'IBM Plex Mono 等宽', en: 'IBM Plex Mono' } },
        { value: 'grotesk', label: { 'zh-CN': '太空怪诞体 + Plex Sans', en: 'Space Grotesk + Plex Sans' } },
      ],
    },
    {
      key: 'density',
      type: 'number',
      group: 'layout',
      label: { 'zh-CN': '疏密', en: 'Density' },
      default: 1,
      min: 0.9,
      max: 1.2,
      step: 0.05,
      unit: 'x',
      safe: [0.9, 1.15],
    },
    {
      key: 'gradient',
      type: 'boolean',
      group: 'look',
      label: { 'zh-CN': '标题栏渐变', en: 'Title bar gradient' },
      default: true,
    },
  ],
  presets: [
    {
      id: 'teal-navy',
      name: { 'zh-CN': '青桌面·海军蓝', en: 'Teal and navy' },
      values: {
        accent: '#0a2a7a',
        desktop: '#008080',
        bevel: 1,
        radius: 0,
        density: 1,
        fontPairing: 'plex-sans',
        gradient: true,
      },
    },
    {
      id: 'meadow',
      name: { 'zh-CN': '草地', en: 'Meadow' },
      values: {
        accent: '#245edb',
        desktop: '#5b8f3a',
        bevel: 1,
        radius: 6,
        density: 1,
        fontPairing: 'geist',
        gradient: true,
      },
    },
    {
      id: 'rose-quartz',
      name: { 'zh-CN': '玫瑰石英', en: 'Rose quartz' },
      values: {
        accent: '#8a2f5c',
        desktop: '#c98da6',
        bevel: 2,
        radius: 0,
        density: 1.05,
        fontPairing: 'grotesk',
        gradient: false,
      },
    },
    {
      id: 'graphite',
      name: { 'zh-CN': '石墨', en: 'Graphite' },
      values: {
        accent: '#2f3540',
        desktop: '#5a6673',
        bevel: 1,
        radius: 2,
        density: 1,
        fontPairing: 'plex-mono',
        gradient: false,
      },
    },
  ],
  dependencies: ['@motif/runtime'],
  fonts: ['IBM Plex Sans Variable', 'Geist Variable', 'IBM Plex Mono', 'Space Grotesk Variable'],
  guidance: {
    use: [
      'Use for portfolio easter eggs, utility and tool sites, indie software pages, nostalgic products and playful launch pages that can lean on early-desktop nostalgia.',
      'Avoid for anything that should feel modern, minimal or premium, and for dense mobile-first apps (the bevels need room).',
    ],
    rules: [
      'Palette: a flat #c0c0c0 face for every control and window (about 55% of pixels), white sunken fields and client areas (about 20%), a desktop color behind everything (about 15%), one accent for title bars, selection and progress (about 8%), and a tooltip yellow (#ffffe1) for hints. Text is near-black on gray, white on the accent. No other hues except status glyph colors (green, red, gold).',
      'Depth comes only from 1-3px bevels made of four inset shadows: white and face-light on the top-left, dark and shadow-gray on the bottom-right for raised; reversed for sunken. Never use blur, translucency, rounded pill shapes or soft drop shadows; a hard offset shadow (3px, 38% black) is allowed under windows only.',
      'Structure: content lives in windows (title bar with icon, title and three drawn controls, optional menu bar, sunken white client area, right-aligned button row). Buttons are raised, sink on press (1px content nudge), and the default action is bold with a black outline. Focus is a 1px dotted inner outline.',
      'Typography: a humanist sans (IBM Plex Sans) at 13-14px for UI, bold for titles and default buttons; titles are short nouns. Headings are bold and tight; no light weights, no letter-spaced caps.',
      'Icons are drawn from flat shapes with a 1.5px near-black outline and a few flat fills. Do not use, imitate or trace any operating-system logo, flag, icon, wallpaper or bitmap font. Use neutral names (Menu, Projects, Trash) instead of vendor terms.',
      'Motion is nearly absent: state changes are instant. If anything moves, it is a stepped progress bar. No fades, springs or easing; reduced motion needs no changes.',
      'Do not add gradients other than the title bar, glassy highlights, gray outlines thinner than the bevel, or modern card shadows.',
    ],
  },
  perf: { webgl: false, maxDpr: 2 },
  a11y: { reducedMotion: 'static' },
  capture: { scroll: true, posterTime: 0.5, loop: 8 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: '98-css',
      repo: 'jdan/98.css',
      sha: 'b1d7a907371bbe523d6f64e3af97f714fdbd6d6a',
      paths: ['style.css'],
      spdx: 'MIT',
      copyright: ['Copyright 2020 Jordan Scales'],
    },
    modifications: [
      'Kept the 98.css bevel model (raised / sunken outer and inner edge shadows in white, light gray, gray and near-black on a #c0c0c0 face) but parameterised the edge thickness and rebuilt it as CSS variables scoped to a .cd-root element; XP.css-style rounded title bars are available through the radius parameter and the gradient toggle.',
      'Replaced the element-selector stylesheet with class-based React primitives (button, card, field, badge, tabs, message box, check box) plus a Window (title bar with drawn controls) and a segmented progress bar.',
      'Title bar color, desktop color and the text color on the title bar are parameters (text color is chosen by contrast). No Microsoft artwork, logos, icons, sounds or bitmap fonts are used: the desktop icons, window glyphs and message-box icons are drawn with CSS and inline SVG, and fonts are self-hosted OFL families from the Motif font list.',
    ],
    assets: [],
  },
})
