import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'text-scramble',
  status: 'published',
  title: { 'zh-CN': '乱码解码', en: 'Text Scramble' },
  summary: {
    'zh-CN': '文字先是一串乱跳的字符，再逐个「解码」成正文，未解出的字符带着一点色彩。适合终端风标题、状态提示和悬停彩蛋。',
    en: 'Text starts as a churn of random glyphs and resolves into the real copy one character at a time, the unresolved ones tinted. Suits terminal-style headings, status lines and hover easter eggs.',
  },
  category: 'text',
  tags: ['text', 'scramble', 'decode', 'terminal', 'hover', 'glitch'],
  runtime: ['react'],
  entry: { file: 'text-scramble.tsx', export: 'TextScramble' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'text-scramble.tsx', role: 'component' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    { key: 'text', type: 'text', label: { 'zh-CN': '文字', en: 'Text' }, default: 'Decrypting the signal', maxLength: 60 },
    {
      key: 'duration',
      type: 'number',
      label: { 'zh-CN': '解码时长', en: 'Duration' },
      default: 1.4,
      min: 0.3,
      max: 4,
      step: 0.05,
      unit: 's',
      safe: [0.6, 2.5],
      group: 'motion',
    },
    {
      key: 'rate',
      type: 'number',
      label: { 'zh-CN': '乱码刷新率', en: 'Churn rate' },
      hint: { 'zh-CN': '每秒换多少次乱码字符', en: 'How many times per second the random glyphs change' },
      default: 24,
      min: 6,
      max: 60,
      step: 1,
      safe: [12, 40],
      group: 'motion',
    },
    {
      key: 'order',
      type: 'select',
      label: { 'zh-CN': '解码顺序', en: 'Resolve order' },
      default: 'random',
      options: [
        { value: 'random', label: { 'zh-CN': '随机', en: 'Random' } },
        { value: 'sequential', label: { 'zh-CN': '从左到右', en: 'Left to right' } },
      ],
      group: 'motion',
    },
    {
      key: 'characterSet',
      type: 'select',
      label: { 'zh-CN': '乱码字符', en: 'Glyphs' },
      default: 'symbols',
      options: [
        { value: 'symbols', label: { 'zh-CN': '符号', en: 'Symbols' } },
        { value: 'letters', label: { 'zh-CN': '字母数字', en: 'Letters & digits' } },
        { value: 'binary', label: { 'zh-CN': '二进制', en: 'Binary' } },
        { value: 'hex', label: { 'zh-CN': '十六进制', en: 'Hex' } },
      ],
      group: 'look',
    },
    { key: 'glyphColor', type: 'color', label: { 'zh-CN': '乱码颜色', en: 'Glyph color' }, default: '#7dd3fc', group: 'look' },
    {
      key: 'replayOnHover',
      type: 'boolean',
      label: { 'zh-CN': '悬停时重播', en: 'Replay on hover' },
      default: true,
      group: 'interaction',
    },
  ],
  presets: [
    { id: 'terminal', name: { 'zh-CN': '终端', en: 'Terminal' }, values: { characterSet: 'symbols', glyphColor: '#7dd3fc', order: 'random', duration: 1.4, rate: 24 } },
    { id: 'matrix', name: { 'zh-CN': '矩阵', en: 'Matrix' }, values: { characterSet: 'binary', glyphColor: '#4ade80', order: 'sequential', duration: 1.8, rate: 32 } },
    { id: 'cipher', name: { 'zh-CN': '密文', en: 'Cipher' }, values: { characterSet: 'hex', glyphColor: '#f0abfc', order: 'random', duration: 1.1, rate: 18 } },
    { id: 'static', name: { 'zh-CN': '雪花', en: 'Static' }, values: { characterSet: 'letters', glyphColor: '#a1a1aa', order: 'random', duration: 0.9, rate: 40 } },
  ],
  dependencies: ['@motif/runtime'],
  perf: { webgl: false, maxDpr: 2 },
  a11y: { reducedMotion: 'static' },
  capture: { zoom: 1.5, posterTime: 0.75, loop: 8 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'motion-primitives',
      repo: 'ibelick/motion-primitives',
      sha: '120f64f6ca60348e251f929e9c81f11ccbe45eda',
      paths: ['components/core/text-scramble.tsx'],
      spdx: 'MIT',
      copyright: ['Copyright (c) 2024 ibelick'],
    },
    modifications: [
      'The setInterval loop was rewritten as a requestAnimationFrame loop that reads performance.now, and motion.create per render (which remounted the element every render) was dropped, so the component no longer depends on motion.',
      'Text comes from a text prop (children still works); characters can resolve in random order, unresolved characters are tinted, and the glyph set is a select (symbols, letters, binary, hex); speed became rate.',
      'Added optional replay on hover and screen-reader friendly markup (the real text stays in an sr-only span).',
      'Added reduced-motion handling (upstream has none): the final text is shown immediately.',
      'Defaults moved into the generated defaults region.',
    ],
    assets: [],
  },
})
