import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'saas-dashboard-landing',
  status: 'published',
  title: { 'zh-CN': '发布看板 SaaS 落地页', en: 'Dashboard SaaS Landing' },
  summary: {
    'zh-CN': '深色为主的 SaaS 整站：光晕首屏配一张纯 JSX 画出的产品仪表盘，客户字标、八宫格功能、三步流程、数据、评价、定价与 FAQ 一气呵成。',
    en: 'A dark-first SaaS site: a glowing hero over a product dashboard drawn entirely in JSX, then logos, an eight-up feature grid, three steps, stats, quotes, pricing and FAQ.',
  },
  kind: 'template',
  category: 'saas',
  tags: ['saas', 'landing', 'dark', 'dashboard', 'pricing', 'faq', 'container queries'],
  runtime: ['react', 'motion', 'css', 'svg'],
  entry: { file: 'saas-dashboard-landing.tsx', export: 'SaasDashboardLanding' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'saas-dashboard-landing.tsx', role: 'component' },
    { path: 'sections.tsx', role: 'component' },
    { path: 'mockup.tsx', role: 'component' },
    { path: 'parts.tsx', role: 'lib' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    { key: 'brandName', type: 'text', label: { 'zh-CN': '品牌名', en: 'Brand name' }, default: 'Kestrel', maxLength: 18, group: 'brand' },
    { key: 'accent', type: 'color', label: { 'zh-CN': '主色', en: 'Accent color' }, default: '#7c6cff', group: 'brand' },
    {
      key: 'fontPair',
      type: 'select',
      label: { 'zh-CN': '字体搭配', en: 'Font pairing' },
      default: 'geist',
      options: [
        { value: 'geist', label: { 'zh-CN': 'Geist（中性精确）', en: 'Geist, precise' } },
        { value: 'grotesk', label: { 'zh-CN': 'Space Grotesk + Inter Tight（工程感）', en: 'Space Grotesk + Inter Tight, engineered' } },
        { value: 'editorial', label: { 'zh-CN': 'Instrument Serif + Geist（编辑感）', en: 'Instrument Serif + Geist, editorial' } },
        { value: 'jakarta', label: { 'zh-CN': 'Plus Jakarta Sans（友好）', en: 'Plus Jakarta Sans, friendly' } },
      ],
      group: 'brand',
    },
    { key: 'radius', type: 'number', label: { 'zh-CN': '圆角', en: 'Corner radius' }, default: 10, min: 2, max: 20, step: 1, unit: 'px', safe: [4, 16], group: 'look' },
    { key: 'dark', type: 'boolean', label: { 'zh-CN': '深色模式', en: 'Dark mode' }, default: true, group: 'look' },
    {
      key: 'headline',
      type: 'text',
      label: { 'zh-CN': '首屏标题', en: 'Hero headline' },
      hint: { 'zh-CN': '最好 60 字符以内，一句话说清产品做什么', en: 'Best under 60 characters; say what the product does' },
      default: 'Know a release is healthy before your users tell you',
      maxLength: 90,
      group: 'copy',
    },
    {
      key: 'subhead',
      type: 'text',
      label: { 'zh-CN': '首屏副标题', en: 'Hero sub-headline' },
      default: 'Watch crash rates, latency and error budgets across every deploy, and roll back the ones that go wrong before anyone files a ticket.',
      maxLength: 200,
      group: 'copy',
    },
  ],
  presets: [
    { id: 'nocturne', name: { 'zh-CN': '夜曲', en: 'Nocturne' }, values: { accent: '#7c6cff', fontPair: 'geist', dark: true, radius: 10 } },
    {
      id: 'ember',
      name: { 'zh-CN': '余烬', en: 'Ember' },
      values: { accent: '#ff6a3d', fontPair: 'grotesk', dark: true, radius: 6, brandName: 'Emberly' },
    },
    {
      id: 'folio',
      name: { 'zh-CN': '手稿', en: 'Folio' },
      values: { accent: '#1f3a5f', fontPair: 'editorial', dark: false, radius: 4, brandName: 'Folio' },
    },
    { id: 'lagoon', name: { 'zh-CN': '泻湖', en: 'Lagoon' }, values: { accent: '#0f9d8a', fontPair: 'jakarta', dark: false, radius: 16, brandName: 'Tidewatch' } },
  ],
  dependencies: ['motion/react', '@motif/runtime'],
  fonts: ['Geist Variable', 'Geist Mono Variable', 'Space Grotesk Variable', 'Inter Tight Variable', 'JetBrains Mono Variable', 'Instrument Serif', 'Plus Jakarta Sans Variable', 'IBM Plex Mono'],
  guidance: {
    use: [
      'A full SaaS marketing site for a developer or ops-facing product: navbar, glowing hero with a product mockup, logo wall, feature grid, how-it-works, stats, testimonials, pricing, FAQ, closing CTA and footer.',
      'Best when the product has a data-dense UI worth showing. Swap the dashboard mockup for a UI that matches your product, built in JSX or SVG, never a bitmap.',
    ],
    rules: [
      'Keep the section order: navbar, hero, logos, features, steps, stats, testimonials, pricing, FAQ, CTA, footer. Remove sections you cannot fill honestly rather than padding them.',
      'Everything themes through CSS variables set on the root element (themeStyle). Change brand, accent, radius, font pairing and mode through props, not by editing class names.',
      'Layout responds to the container width (@2xl, @3xl, @5xl variants), so the page works inside any preview width. Do not switch to viewport breakpoints.',
      'The accent color is used sparingly: primary buttons, the hero glow, small icons, one featured pricing tier. Everything else stays neutral.',
      'Copy is specific and restrained: real-sounding product names, concrete numbers, no superlatives. Replace the invented logos with your own wordmarks; never use real company logos.',
      'Never add photos or screenshots; use gradient initials for people and JSX or SVG mockups for product UI.',
    ],
  },
  perf: { webgl: false, maxDpr: 2 },
  a11y: { reducedMotion: 'static' },
  capture: { scroll: true, posterTime: 0.5, loop: 8 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'launch-ui',
      repo: 'launch-ui/launch-ui',
      sha: 'b0d4d5bce91d13523450416ce1797109076b2787',
      paths: [
        'app/page.tsx',
        'components/sections/hero/default.tsx',
        'components/sections/logos/default.tsx',
        'components/sections/items/default.tsx',
        'components/sections/stats/default.tsx',
        'components/sections/pricing/default.tsx',
        'components/sections/faq/default.tsx',
        'components/sections/cta/default.tsx',
        'components/sections/footer/default.tsx',
      ],
      spdx: 'MIT',
      copyright: ['Copyright (c) 2024 Mikolaj Dobrucki'],
    },
    modifications: [
      'Rewrote the section composition for React 19 without Next.js, shadcn/ui or lucide-react; icons are inline SVG and theming is driven by props through CSS variables.',
      'Replaced the product screenshots with a dashboard mockup built in JSX and SVG, and the brand logos with invented SVG wordmarks.',
      'Switched viewport breakpoints to container queries; added a how-it-works section and a testimonials section that the upstream layout does not have.',
      'Copy, stats, pricing and FAQ are new; the hero glow, layout lines, bordered feature grid and pricing structure follow the upstream design.',
    ],
    assets: [],
  },
})
