import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'bell-field',
  status: 'published',
  title: { 'zh-CN': '钟鸣场', en: 'Bell Field' },
  summary: {
    'zh-CN': '像敲响一口铜钟：青铜与铜绿的节线图案缓缓漂移，冲击环定时扩散，指针轻轻牵引，铸造火星从底部升起。适合做音频、品牌叙事类页面的背景。',
    en: 'Like a struck bronze bell: verdigris nodal lines drift across dark metal, shock rings ripple out on a timer, the pointer nudges the pattern and foundry embers rise. A backdrop for audio and brand-story pages.',
  },
  category: 'shader',
  tags: ['chladni', 'cymatics', 'metal', 'nodal', 'rings', 'embers', 'particles', 'webgl', 'background', 'interactive'],
  runtime: ['react', 'webgl', 'canvas2d'],
  entry: { file: 'bell-field.tsx', export: 'BellField' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'bell-field.tsx', role: 'component' },
    { path: 'shaders.ts', role: 'shader' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    { key: 'speed', type: 'number', label: { 'zh-CN': '速度', en: 'Speed' }, default: 1, min: 0.2, max: 2.5, step: 0.01, unit: 'x', safe: [0.4, 1.8], group: 'motion' },
    {
      key: 'strikeDuration',
      type: 'number',
      label: { 'zh-CN': '冲击环时长', en: 'Strike duration' },
      hint: { 'zh-CN': '每次敲击的余韵有多长', en: 'How long each strike rings out' },
      default: 2400,
      min: 1200,
      max: 5000,
      step: 50,
      unit: 'ms',
      group: 'motion',
    },
    {
      key: 'pointerAmount',
      type: 'number',
      label: { 'zh-CN': '指针牵引', en: 'Pointer pull' },
      default: 1,
      min: 0,
      max: 1.6,
      step: 0.01,
      group: 'interaction',
    },
    { key: 'emberAmount', type: 'number', label: { 'zh-CN': '火星数量', en: 'Embers' }, default: 1, min: 0, max: 1.5, step: 0.01, group: 'look' },
    { key: 'hue', type: 'number', label: { 'zh-CN': '色相', en: 'Hue' }, default: 0, min: -180, max: 180, step: 1, unit: 'deg', group: 'color' },
    { key: 'saturation', type: 'number', label: { 'zh-CN': '饱和度', en: 'Saturation' }, default: 1, min: 0.3, max: 1.6, step: 0.01, group: 'color' },
    { key: 'brightness', type: 'number', label: { 'zh-CN': '亮度', en: 'Brightness' }, default: 1.4, min: 0.8, max: 2, step: 0.01, group: 'color' },
  ],
  presets: [
    { id: 'verdigris', name: { 'zh-CN': '铜绿', en: 'Verdigris' }, values: {} },
    { id: 'forge', name: { 'zh-CN': '炉火', en: 'Forge' }, values: { hue: -130, saturation: 1.35, brightness: 1.6, emberAmount: 1.4, speed: 1.3 } },
    { id: 'midnight', name: { 'zh-CN': '子夜', en: 'Midnight' }, values: { hue: 75, saturation: 1.2, brightness: 1.5, speed: 0.6, emberAmount: 0.5, strikeDuration: 4200 } },
    { id: 'silver', name: { 'zh-CN': '银钟', en: 'Silver' }, values: { saturation: 0.35, brightness: 1.7, emberAmount: 0.3, speed: 0.8 } },
  ],
  dependencies: ['@motif/runtime'],
  perf: { webgl: true, maxDpr: 1.5 },
  a11y: { reducedMotion: 'static' },
  capture: { posterTime: 0.2 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'threeui',
      repo: 'MengTo/threeui',
      sha: '68802d5428071ada5c20db8094b1649e6bb770ed',
      paths: ['src/shaders/bell-field/BellFieldBackground.tsx', 'src/shaders/bell-field/bellFieldShaders.ts'],
      spdx: 'MIT',
      copyright: ['Copyright (c) 2026 Meng To'],
      origin: 'Neuform export',
    },
    modifications: [
      'The render loop now uses motif-runtime: pauses offscreen and in hidden tabs, renders a static frame under reduced motion, and caps DPR at 1.5.',
      'Handles WebGL context loss and restore, and releases the context on unmount.',
      'Strikes are scheduled on animation time (first at 1.7 s, then every 8.2 s) instead of wall-clock timers, so they pause with the animation; click still strikes.',
      'Ember positions are normalised and advanced by frame delta with a deterministic initial layout instead of Math.random; the ember cap is raised to 90 so the amount slider can exceed 1.',
      'The angular mode number is crossfaded between the two neighbouring integer modes to remove the atan seam the fractional mode left on the left edge (the only shader change). Opacity is dropped as a parameter; defaults moved into the generated defaults region; children can be layered on top.',
    ],
    assets: [],
  },
})
