import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'ferrant-product-site',
  status: 'published',
  title: { 'zh-CN': '工具品牌官网', en: 'Ferrant Product Site' },
  summary: {
    'zh-CN': '工业风的产品公司官网：公告条、带矢量产品图的首屏、客户字标、可切换的功能页签、滚动计数的数据、产品卡、评价、服务计划和常见问题，收尾是一块醒目的报价区。',
    en: 'An industrial product-company site: announcement bar, a hero with a vector-drawn product, client wordmarks, switchable feature tabs, counting stats, product cards, reviews, service plans and an FAQ, closing on a bold quote block.',
  },
  kind: 'template',
  category: 'product',
  tags: ['product', 'company', 'hardware', 'industrial', 'tabs', 'pricing', 'faq', 'responsive'],
  runtime: ['react', 'motion', 'svg'],
  entry: { file: 'ferrant-product-site.tsx', export: 'FerrantProductSite' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'light' },
  files: [
    { path: 'ferrant-product-site.tsx', role: 'component' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    { key: 'name', type: 'text', label: { 'zh-CN': '品牌名', en: 'Brand name' }, hint: { 'zh-CN': '导航、页脚、字标和文案里的名字', en: 'Used in nav, footer, mark and copy' }, default: 'Ferrant', maxLength: 18, group: 'content' },
    { key: 'headline', type: 'text', label: { 'zh-CN': '首屏标题文案', en: 'Headline' }, default: 'Cordless tools built for the ninth hour of the day.', maxLength: 70, group: 'content' },
    { key: 'accent', type: 'color', label: { 'zh-CN': '主色', en: 'Accent' }, hint: { 'zh-CN': '产品机身、按钮、勾选和横幅底色都跟着它变', en: 'Product body, buttons, ticks and the closing banner follow it' }, default: '#ee7a14', group: 'look' },
    {
      key: 'fontPair',
      type: 'select',
      label: { 'zh-CN': '字体搭配', en: 'Font pairing' },
      default: 'industrial',
      options: [
        { value: 'industrial', label: { 'zh-CN': 'Archivo Black + Inter Tight', en: 'Archivo Black + Inter Tight' } },
        { value: 'plex', label: { 'zh-CN': 'IBM Plex', en: 'IBM Plex' } },
        { value: 'jakarta', label: { 'zh-CN': 'Plus Jakarta Sans', en: 'Plus Jakarta Sans' } },
        { value: 'geist', label: { 'zh-CN': 'Geist + Geist Mono', en: 'Geist + Geist Mono' } },
      ],
      group: 'look',
    },
    { key: 'radius', type: 'number', label: { 'zh-CN': '圆角', en: 'Corner radius' }, default: 16, min: 0, max: 28, step: 1, unit: 'px', safe: [6, 24], group: 'look' },
    { key: 'dark', type: 'boolean', label: { 'zh-CN': '深色模式', en: 'Dark mode' }, default: false, group: 'look' },
    { key: 'animate', type: 'boolean', label: { 'zh-CN': '入场与计数动画', en: 'Entrance and counter animation' }, default: true, group: 'motion' },
  ],
  presets: [
    { id: 'workshop-orange', name: { 'zh-CN': '车间橙', en: 'Workshop Orange' }, values: { accent: '#ee7a14', fontPair: 'industrial', radius: 16, dark: false } },
    { id: 'night-shift', name: { 'zh-CN': '夜班', en: 'Night Shift' }, values: { accent: '#f5c518', fontPair: 'plex', radius: 6, dark: true } },
    { id: 'cold-steel', name: { 'zh-CN': '冷钢', en: 'Cold Steel' }, values: { accent: '#2f7cf6', fontPair: 'geist', radius: 12, dark: false } },
    { id: 'forest-crew', name: { 'zh-CN': '林场', en: 'Forest Crew' }, values: { accent: '#16a34a', fontPair: 'jakarta', radius: 22, dark: true } },
  ],
  dependencies: ['motion/react', '@motif/runtime'],
  fonts: ['Archivo Black', 'Inter Tight Variable', 'IBM Plex Mono', 'IBM Plex Sans Variable', 'Plus Jakarta Sans Variable', 'Geist Variable', 'Geist Mono Variable'],
  guidance: {
    use: [
      'A marketing site for a hardware or industrial product company: announcement, hero with a product render, logos, platform story, tabbed features, stats, product range, reviews, plans, FAQ, quote CTA.',
      'Adapt it by replacing the arrays at the top (PLATFORM, TABS, STATS, PRODUCTS, QUOTES, PLANS, FAQS) and redrawing the SVG product illustrations (Driver, Battery, Saw, Charger); keep them driven by var(--accent) so the accent param recolors the products.',
    ],
    rules: [
      'One accent color drives the products, buttons, ticks, the closing banner and the eyebrow rule. Neutrals are warm greys (--bg, --bg-2, --card); do not introduce a second hue.',
      'Headings use the head font with --head-weight and --head-track (heavy display faces get weight 400 and tighter tracking); labels and specs use the mono font at 10–12px uppercase.',
      'Product images are SVG built from gradients on --accent, dark grey and steel, always with a soft floor shadow. Never add photographs, real product shots or brand marks.',
      'Feature tabs swap with a short fade-slide (250ms) using AnimatePresence; stats count up once when scrolled into view. No other looping motion except the gentle float on the hero product and its spec chips.',
      'Keep at most one filled accent button per viewport, secondary actions are outlined. Announcement bar is dark (--fg on --bg inverted) and dismissible.',
      'Copy uses real specs: torque, minutes, kilograms, years. Client names are invented SVG wordmarks.',
    ],
  },
  perf: { webgl: false, maxDpr: 2 },
  a11y: { reducedMotion: 'static' },
  capture: { scroll: true, posterTime: 0.5, loop: 8 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'screwfast',
      repo: 'mearashadowfax/ScrewFast',
      sha: 'aa9da9ad278a2bdb005e04ab644a980543797157',
      paths: [
        'src/views/HomeView.astro',
        'src/components/sections/landing/HeroSection.astro',
        'src/components/sections/landing/ClientsSection.astro',
        'src/components/sections/features/FeaturesGeneral.astro',
        'src/components/sections/features/FeaturesNavs.astro',
        'src/components/sections/features/FeaturesStats.astro',
        'src/components/sections/testimonials/TestimonialsSection.astro',
        'src/components/sections/pricing/PricingSection.astro',
        'src/components/sections/misc/FAQ.astro',
        'src/components/sections/navbar&footer/Navbar.astro',
        'src/components/sections/navbar&footer/FooterSection.astro',
      ],
      spdx: 'MIT',
      copyright: ['Copyright (c) 2024 Emil Gulamov'],
    },
    modifications: [
      'Astro views and sections rewritten as one React 19 + Tailwind v4 component; section order (banner, hero with reviews, clients, features, tabbed features, stats, testimonials, pricing, FAQ, CTA, footer) is kept.',
      'GSAP and the Preline tab/accordion scripts were replaced by motion (fade-slide tab swap with AnimatePresence, animated accordion height, in-view counters).',
      'All photographs were replaced by vector product illustrations drawn in SVG (driver, saw, battery, charger) that recolor from the accent; avatars are initials on gradients; clients are invented SVG wordmarks; the multi-language routing was removed.',
      'The catalogue, prices, specs, reviews and plans are invented for a fictional tool brand.',
      'Theming is driven by accent, font pairing, radius and a dark flag via CSS variables.',
    ],
    assets: [],
  },
})
