import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'stream-convergence',
  status: 'published',
  title: { 'zh-CN': '汇流光束', en: 'Stream Convergence' },
  summary: {
    'zh-CN': '三道红、绿、蓝色散分离的波前斜向穿过暗场，叠出紫罗兰色的流光，四角渐隐。适合做产品发布页或活动页的全屏背景。',
    en: 'Three chromatically split wavefronts sweep diagonally through a dark field and blend into violet streams, fading into a vignette. A full-bleed background for launches and event pages.',
  },
  kind: 'effect',
  category: 'background',
  tags: ['waves', 'wavefront', 'chromatic', 'violet', 'vignette', 'webgl', 'hero'],
  runtime: ['react', 'webgl'],
  entry: { file: 'stream-convergence.tsx', export: 'StreamConvergence' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'stream-convergence.tsx', role: 'component' },
    { path: 'shaders.ts', role: 'shader' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    { key: 'speed', type: 'number', label: { 'zh-CN': '速度', en: 'Speed' }, default: 1, min: 0.1, max: 2.5, step: 0.01, unit: 'x', safe: [0.3, 1.8], group: 'motion' },
    {
      key: 'fidelity',
      type: 'number',
      label: { 'zh-CN': '色散', en: 'Dispersion' },
      hint: { 'zh-CN': '三道波前之间的分离程度', en: 'How far apart the three wavefronts sit' },
      default: 0.3,
      min: 0,
      max: 1,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'scale',
      type: 'number',
      label: { 'zh-CN': '缩放', en: 'Zoom' },
      hint: { 'zh-CN': '放大后裁掉边缘，暗角随之外移', en: 'Zooms in and crops the edges' },
      default: 1.1,
      min: 1,
      max: 1.5,
      step: 0.01,
      group: 'look',
    },
    { key: 'hue', type: 'number', label: { 'zh-CN': '色相', en: 'Hue' }, default: 0, min: -180, max: 180, step: 1, unit: 'deg', group: 'color' },
    { key: 'saturation', type: 'number', label: { 'zh-CN': '饱和度', en: 'Saturation' }, default: 0.9, min: 0, max: 1.6, step: 0.01, group: 'color' },
    { key: 'brightness', type: 'number', label: { 'zh-CN': '亮度', en: 'Brightness' }, default: 1, min: 0.6, max: 1.6, step: 0.01, group: 'color' },
    { key: 'opacity', type: 'number', label: { 'zh-CN': '不透明度', en: 'Opacity' }, default: 1, min: 0.3, max: 1, step: 0.01, group: 'color' },
  ],
  presets: [
    { id: 'violet-drift', name: { 'zh-CN': '紫罗兰', en: 'Violet drift' }, values: {} },
    { id: 'solar-flare', name: { 'zh-CN': '耀斑', en: 'Solar flare' }, values: { hue: 110, brightness: 1.15, fidelity: 0.8, speed: 1.3 } },
    { id: 'deep-sea', name: { 'zh-CN': '深海', en: 'Deep sea' }, values: { hue: -95, saturation: 1.2, speed: 0.55, fidelity: 0.3 } },
    { id: 'silver-thread', name: { 'zh-CN': '银线', en: 'Silver thread' }, values: { saturation: 0, brightness: 1.3, fidelity: 0.15, scale: 1.2, speed: 0.7 } },
  ],
  dependencies: ['@motif/runtime'],
  perf: { webgl: true, maxDpr: 1.5 },
  a11y: { reducedMotion: 'static' },
  capture: { posterTime: 5 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'threeui',
      repo: 'MengTo/threeui',
      sha: '68802d5428071ada5c20db8094b1649e6bb770ed',
      paths: ['src/shaders/stream-convergence/StreamConvergenceBackground.tsx', 'src/shaders/stream-convergence/streamConvergenceShaders.ts'],
      spdx: 'MIT',
      copyright: ['Copyright (c) 2026 Meng To'],
      origin: 'Neuform export',
    },
    modifications: [
      'The render loop now uses motif-runtime: pauses offscreen and in hidden tabs, renders a static frame under reduced motion, and caps DPR at 1.5.',
      'Handles WebGL context loss and restore, and releases the context on unmount.',
      'Zoom range tightened to 1-1.5 so the canvas never reveals its edges; the "fidelity" control is labelled Dispersion. Children can be layered on top; defaults moved into the generated defaults region.',
    ],
    assets: [],
  },
})
