import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'pulsing-border',
  status: 'published',
  title: { "zh-CN": '脉冲光边', en: 'Pulsing Border' },
  summary: {
    "zh-CN": '流动的彩色光斑沿着边框游走、呼吸，汇成一圈发光的轮廓。适合给卡片、输入框或 AI 面板加一圈灵气。',
    en: 'Luminous color spots travel and breathe along the edge into a glowing contour. Gives cards, inputs and AI panels an alive outline.',
  },
  kind: 'effect',
  category: 'card',
  tags: ['border', 'glow', 'card', 'shader', 'webgl', 'ai'],
  runtime: ['react', 'webgl2'],
  entry: { file: 'pulsing-border.tsx', export: 'PulsingBorderCard' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'pulsing-border.tsx', role: 'component' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    {
      key: 'colors',
      type: 'palette',
      label: { "zh-CN": '光斑颜色', en: 'Spot colors' },
      hint: { "zh-CN": '每种颜色生成几团沿边游走的光斑', en: 'Each color spawns a few spots that travel along the edge' },
      default: ['#0dc1fd', '#d915ef', '#ff3f2ecc'],
      minItems: 1,
      maxItems: 5,
    },
    {
      key: 'colorBack',
      type: 'color',
      label: { "zh-CN": '底色', en: 'Background' },
      hint: { "zh-CN": '带透明度时，卡片内部透出下面的背景', en: 'Translucent lets the surface behind show through' },
      default: '#00000000',
    },
    {
      key: 'roundness',
      type: 'number',
      label: { "zh-CN": '圆角', en: 'Roundness' },
      default: 0.25,
      min: 0,
      max: 1,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'thickness',
      type: 'number',
      label: { "zh-CN": '边框厚度', en: 'Thickness' },
      default: 0.1,
      min: 0.02,
      max: 1,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'softness',
      type: 'number',
      label: { "zh-CN": '柔和度', en: 'Softness' },
      default: 0.75,
      min: 0,
      max: 1,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'bloom',
      type: 'number',
      label: { "zh-CN": '辉光', en: 'Bloom' },
      default: 0.25,
      min: 0,
      max: 1,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'spotSize',
      type: 'number',
      label: { "zh-CN": '光斑大小', en: 'Spot size' },
      default: 0.5,
      min: 0.1,
      max: 1,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'pulse',
      type: 'number',
      label: { "zh-CN": '脉动', en: 'Pulse' },
      default: 0.25,
      min: 0,
      max: 1,
      step: 0.01,
      group: 'motion',
    },
    {
      key: 'smoke',
      type: 'number',
      label: { "zh-CN": '烟雾', en: 'Smoke' },
      default: 0.3,
      min: 0,
      max: 1,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'speed',
      type: 'number',
      label: { "zh-CN": '速度', en: 'Speed' },
      default: 1,
      min: 0,
      max: 3,
      step: 0.01,
      safe: [0.2, 2],
      unit: 'x',
      group: 'motion',
    },
  ],
  presets: [
    {
      id: 'neon',
      name: { "zh-CN": '霓虹', en: 'Neon' },
      values: {
        colors: ['#0dc1fd', '#d915ef', '#ff3f2ecc'],
        colorBack: '#00000000',
        roundness: 0.25,
        thickness: 0.1,
        softness: 0.75,
        bloom: 0.25,
        spotSize: 0.5,
        pulse: 0.25,
        smoke: 0.3,
        speed: 1,
      },
    },
    {
      id: 'aurora',
      name: { "zh-CN": '极光', en: 'Northern lights' },
      values: {
        colors: ['#4c4794', '#774a7d', '#12694a', '#0aff78', '#4733cc'],
        colorBack: '#0c182c',
        roundness: 0,
        thickness: 1,
        softness: 1,
        bloom: 0.2,
        spotSize: 0.25,
        pulse: 0,
        smoke: 0.32,
        speed: 0.18,
      },
    },
    {
      id: 'ember',
      name: { "zh-CN": '余烬', en: 'Ember' },
      values: {
        colors: ['#ff5a1f', '#ffb347', '#ff2d55'],
        colorBack: '#00000000',
        roundness: 0.2,
        thickness: 0.08,
        softness: 0.6,
        bloom: 0.45,
        spotSize: 0.4,
        pulse: 0.4,
        smoke: 0.45,
        speed: 0.8,
      },
    },
    {
      id: 'frost',
      name: { "zh-CN": '霜刃', en: 'Frost' },
      values: {
        colors: ['#e6f3ff'],
        colorBack: '#00000000',
        roundness: 0.15,
        thickness: 0.05,
        softness: 0.3,
        bloom: 0.5,
        spotSize: 0.8,
        pulse: 0,
        smoke: 0,
        speed: 0.8,
      },
    },
  ],
  dependencies: ['@paper-design/shaders-react', '@motif/runtime'],
  perf: { webgl: true, maxDpr: 1.5 },
  a11y: { reducedMotion: 'static' },
  capture: { posterTime: 2.5, zoom: 1.8 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'paper-shaders',
      repo: 'paper-design/shaders',
      sha: '43cd68db79fa0b1759f72ffc941b3238e2a3954c',
      paths: ['packages/shaders-react/src/shaders/pulsing-border.tsx', 'docs/src/shader-defs/pulsing-border-def.ts'],
      spdx: 'Apache-2.0',
      copyright: ['Paper Shaders (https://shaders.paper.design)'],
    },
    modifications: ['Wrapped the Paper PulsingBorder component as a card frame that lays children over the glowing border (margin, spot count, spot intensity and smoke size are fixed at upstream defaults).', 'Parameter ranges adapted from the Paper docs; Neon (default) and Northern lights follow the upstream presets; Ember and Frost are Motif’s.', 'Renders a static frame when the user prefers reduced motion.'],
    assets: [],
  },
})
