import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'particle-button',
  status: 'published',
  title: { 'zh-CN': '粒子按钮', en: 'Particle Button' },
  summary: {
    'zh-CN': '点击后从按钮中心迸出一圈彩色粒子和光晕，文案切换成完成状态。适合发送、收藏、提交这类需要一点仪式感的操作。',
    en: 'A click bursts colored sparks and a soft ring out of the button while the label flips to a done state. For send, save and submit actions that deserve a little ceremony.',
  },
  category: 'button',
  tags: ['button', 'particles', 'confetti', 'click', 'feedback'],
  runtime: ['react', 'motion'],
  entry: { file: 'particle-button.tsx', export: 'ParticleButton' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'particle-button.tsx', role: 'component' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    { key: 'label', type: 'text', group: 'content', label: { 'zh-CN': '按钮文案', en: 'Label' }, default: 'Send message', maxLength: 24 },
    { key: 'doneLabel', type: 'text', group: 'content', label: { 'zh-CN': '完成文案', en: 'Done label' }, default: 'Sent', maxLength: 24 },
    { key: 'particleCount', type: 'number', group: 'burst', label: { 'zh-CN': '粒子数量', en: 'Particles' }, default: 20, min: 6, max: 40, step: 1, safe: [12, 28] },
    { key: 'spread', type: 'number', group: 'burst', label: { 'zh-CN': '扩散半径', en: 'Spread' }, default: 104, min: 40, max: 160, step: 1, unit: 'px', safe: [60, 120] },
    { key: 'particleSize', type: 'number', group: 'burst', label: { 'zh-CN': '粒子大小', en: 'Particle size' }, default: 7, min: 3, max: 12, step: 0.5, unit: 'px', safe: [4, 8] },
    { key: 'duration', type: 'number', group: 'burst', label: { 'zh-CN': '迸发时长', en: 'Burst duration' }, default: 0.9, min: 0.4, max: 1.8, step: 0.05, unit: 's', safe: [0.6, 1.2] },
    {
      key: 'gravity',
      type: 'number',
      group: 'burst',
      label: { 'zh-CN': '下坠', en: 'Gravity' },
      hint: { 'zh-CN': '粒子飞到最高点后向下飘落的距离', en: 'How far particles drift down after the peak' },
      default: 26,
      min: 0,
      max: 80,
      step: 1,
      unit: 'px',
      safe: [10, 50],
    },
    {
      key: 'shape',
      type: 'select',
      group: 'look',
      label: { 'zh-CN': '粒子形状', en: 'Particle shape' },
      default: 'mix',
      options: [
        { value: 'mix', label: { 'zh-CN': '圆点 + 星芒', en: 'Dots + sparks' } },
        { value: 'dot', label: { 'zh-CN': '圆点', en: 'Dots' } },
        { value: 'spark', label: { 'zh-CN': '星芒', en: 'Sparks' } },
      ],
    },
    { key: 'colors', type: 'palette', group: 'look', label: { 'zh-CN': '粒子配色', en: 'Particle colors' }, default: ['#a78bfa', '#f472b6', '#38bdf8', '#fbbf24'], minItems: 2, maxItems: 6 },
  ],
  presets: [
    { id: 'confetti', name: { 'zh-CN': '彩纸', en: 'Confetti' }, values: { colors: ['#a78bfa', '#f472b6', '#38bdf8', '#fbbf24'], shape: 'mix', particleCount: 20, spread: 104, gravity: 26 } },
    { id: 'ember', name: { 'zh-CN': '余烬', en: 'Ember' }, values: { colors: ['#fb923c', '#f97316', '#fde047', '#ef4444'], shape: 'dot', particleCount: 26, spread: 70, particleSize: 4.5, gravity: 0, duration: 1.1 } },
    { id: 'aurora', name: { 'zh-CN': '极光', en: 'Aurora' }, values: { colors: ['#34d399', '#22d3ee', '#818cf8'], shape: 'spark', particleCount: 14, spread: 110, particleSize: 9, gravity: 12, duration: 1.2 } },
    { id: 'mono', name: { 'zh-CN': '素白', en: 'Mono' }, values: { colors: ['#ffffff', '#a1a1aa', '#71717a'], shape: 'dot', particleCount: 18, spread: 76, particleSize: 4, gravity: 18, duration: 0.8 } },
  ],
  dependencies: ['motion/react', '@motif/runtime'],
  perf: { webgl: false, maxDpr: 2 },
  a11y: { reducedMotion: 'static' },
  capture: { zoom: 2.2, posterTime: 0.85, loop: 4 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'kokonutui',
      repo: 'kokonut-labs/kokonutui',
      sha: '83eec6d982d400a18438001a8efdbac1f159dd43',
      paths: ['components/kokonutui/particle-button.tsx'],
      spdx: 'MIT',
      copyright: ['Copyright (c) 2025 kokonutUI'],
    },
    modifications: [
      'Replaced the shadcn Button and lucide icon with a plain button element and Tailwind classes.',
      'Particles are rendered inside the button and positioned relative to it instead of being fixed to the viewport, so they follow scrolling and layout.',
      'Replaced Math.random with a seeded generator, added dot/spark shapes, a palette, gravity, a ring pulse and a press squash; the label now flips to a done state.',
      'The burst can also be triggered from outside through a burstKey prop (used by the demo autoplay).',
      'Reduced motion drops the particles and ring and keeps only the label change.',
      'framer-motion import path and cn now come from motion/react and motif-runtime.',
    ],
    assets: [],
  },
})
