import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'ribbon-field',
  status: 'published',
  title: { 'zh-CN': '光带点阵', en: 'Ribbon Field' },
  summary: {
    'zh-CN': '青、靛、紫三条光带缓缓起伏，被一层 7px 点阵切碎成发光的网点，左侧留出暗区。适合做 SaaS 或开发工具首屏的背景。',
    en: 'Three cyan, indigo and purple light ribbons undulate through a glowing dot matrix, leaving the left side dark for copy. A hero background for SaaS and developer tools.',
  },
  kind: 'effect',
  category: 'background',
  tags: ['ribbon', 'waves', 'dot matrix', 'glow', 'webgl', 'hero', 'dark'],
  runtime: ['react', 'webgl'],
  entry: { file: 'ribbon-field.tsx', export: 'RibbonField' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'ribbon-field.tsx', role: 'component' },
    { path: 'shaders.ts', role: 'shader' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    { key: 'speed', type: 'number', label: { 'zh-CN': '速度', en: 'Speed' }, default: 1, min: 0.1, max: 2.5, step: 0.01, unit: 'x', safe: [0.3, 1.8], group: 'motion' },
    {
      key: 'dotSize',
      type: 'number',
      label: { 'zh-CN': '点阵大小', en: 'Dot size' },
      hint: { 'zh-CN': '每个网点的像素间距', en: 'Grid pitch of the dot matrix' },
      default: 7,
      min: 4,
      max: 14,
      step: 0.5,
      unit: 'px',
      safe: [5, 11],
      group: 'look',
    },
    {
      key: 'pointerAmount',
      type: 'number',
      label: { 'zh-CN': '指针漂移', en: 'Pointer drift' },
      hint: { 'zh-CN': '光带跟随指针偏移的程度', en: 'How far the ribbons drift with the pointer' },
      default: 1,
      min: 0,
      max: 2,
      step: 0.01,
      group: 'interaction',
    },
    {
      key: 'smoothing',
      type: 'number',
      label: { 'zh-CN': '跟随缓动', en: 'Smoothing' },
      hint: { 'zh-CN': '越小越柔和', en: 'Lower is softer' },
      default: 0.035,
      min: 0.01,
      max: 0.12,
      step: 0.005,
      group: 'interaction',
    },
    { key: 'hue', type: 'number', label: { 'zh-CN': '色相', en: 'Hue' }, default: 0, min: -180, max: 180, step: 1, unit: 'deg', group: 'color' },
    { key: 'saturation', type: 'number', label: { 'zh-CN': '饱和度', en: 'Saturation' }, default: 1, min: 0, max: 1.6, step: 0.01, group: 'color' },
    { key: 'brightness', type: 'number', label: { 'zh-CN': '亮度', en: 'Brightness' }, default: 1.8, min: 0.8, max: 2.4, step: 0.01, group: 'color' },
    { key: 'opacity', type: 'number', label: { 'zh-CN': '不透明度', en: 'Opacity' }, default: 1, min: 0.3, max: 1, step: 0.01, group: 'color' },
  ],
  presets: [
    { id: 'aurora', name: { 'zh-CN': '极光', en: 'Aurora' }, values: {} },
    { id: 'ember', name: { 'zh-CN': '余烬', en: 'Ember' }, values: { hue: 150, saturation: 1.15, brightness: 1.15, speed: 0.8 } },
    { id: 'graphite', name: { 'zh-CN': '石墨', en: 'Graphite' }, values: { saturation: 0, brightness: 1.35, dotSize: 6, speed: 0.7 } },
    { id: 'fine-mist', name: { 'zh-CN': '细雾', en: 'Fine mist' }, values: { dotSize: 4.5, hue: -40, brightness: 1.3, speed: 0.6 } },
    { id: 'pixel-tide', name: { 'zh-CN': '像素潮', en: 'Pixel tide' }, values: { dotSize: 11, hue: 70, saturation: 1.3, brightness: 1.3, speed: 1.4 } },
  ],
  dependencies: ['@motif/runtime'],
  perf: { webgl: true, maxDpr: 1.5 },
  a11y: { reducedMotion: 'static' },
  capture: { posterTime: 10 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'threeui',
      repo: 'MengTo/threeui',
      sha: '68802d5428071ada5c20db8094b1649e6bb770ed',
      paths: ['src/shaders/ribbon-field/RibbonFieldBackground.tsx', 'src/shaders/ribbon-field/ribbonFieldShaders.ts'],
      spdx: 'MIT',
      copyright: ['Copyright (c) 2026 Meng To'],
      origin: 'Neuform export',
    },
    modifications: [
      'The render loop now uses motif-runtime: pauses offscreen and in hidden tabs, renders a static frame under reduced motion, and caps DPR at 1.5.',
      'Handles WebGL context loss and restore, and releases the context on unmount.',
      'The 7px dot pitch in the fragment shader became a dotSize uniform (scaled by device pixel ratio so the look is stable across displays); the rest of the GLSL is unchanged.',
      'Pointer smoothing is frame-rate independent; children can be layered on top; defaults moved into the generated defaults region.',
    ],
    assets: [],
  },
})
