import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'infinite-slider',
  status: 'published',
  title: { 'zh-CN': '无限滚动条', en: 'Infinite Slider' },
  summary: {
    'zh-CN': '内容首尾相接、匀速循环滚动，两端渐隐，悬停时平滑减速。适合客户标识墙、技术栈列表和评价跑马灯。',
    en: 'Content loops end to end at a steady pace with faded edges and eases down on hover. For logo walls, tech-stack strips and testimonial tickers.',
  },
  category: 'layout',
  tags: ['marquee', 'ticker', 'logos', 'loop', 'infinite', 'carousel'],
  runtime: ['react', 'css'],
  entry: { file: 'infinite-slider.tsx', export: 'InfiniteSlider' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'infinite-slider.tsx', role: 'component' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    {
      key: 'speed',
      type: 'number',
      label: { 'zh-CN': '速度', en: 'Speed' },
      default: 80,
      min: 10,
      max: 300,
      step: 1,
      unit: 'px',
      hint: { 'zh-CN': '每秒滚动的像素数', en: 'Pixels travelled per second' },
      safe: [40, 160],
      group: 'motion',
    },
    {
      key: 'hoverSpeed',
      type: 'number',
      label: { 'zh-CN': '悬停时速度', en: 'Speed on hover' },
      hint: { 'zh-CN': '相对正常速度的倍数，0 为悬停暂停', en: 'A multiple of the normal speed; 0 pauses on hover' },
      default: 0.25,
      min: 0,
      max: 1,
      step: 0.05,
      unit: 'x',
      group: 'interaction',
    },
    {
      key: 'gap',
      type: 'number',
      label: { 'zh-CN': '间距', en: 'Gap' },
      default: 32,
      min: 0,
      max: 96,
      step: 1,
      unit: 'px',
      safe: [16, 56],
      group: 'layout',
    },
    {
      key: 'direction',
      type: 'select',
      label: { 'zh-CN': '方向', en: 'Direction' },
      default: 'horizontal',
      options: [
        { value: 'horizontal', label: { 'zh-CN': '横向', en: 'Horizontal' } },
        { value: 'vertical', label: { 'zh-CN': '纵向', en: 'Vertical' } },
      ],
      group: 'layout',
    },
    { key: 'reverse', type: 'boolean', label: { 'zh-CN': '反向', en: 'Reverse' }, default: false, group: 'layout' },
    {
      key: 'fade',
      type: 'number',
      label: { 'zh-CN': '边缘渐隐', en: 'Edge fade' },
      hint: { 'zh-CN': '两端渐隐的宽度，0 为不渐隐', en: 'Width of the faded edges; 0 turns it off' },
      default: 96,
      min: 0,
      max: 240,
      step: 1,
      unit: 'px',
      safe: [48, 160],
      group: 'look',
    },
  ],
  presets: [
    { id: 'steady', name: { 'zh-CN': '从容', en: 'Steady' }, values: { speed: 80, hoverSpeed: 0.25, gap: 32, fade: 96 } },
    { id: 'glacial', name: { 'zh-CN': '缓流', en: 'Glacial' }, values: { speed: 32, hoverSpeed: 0, gap: 48, fade: 140 } },
    { id: 'ticker', name: { 'zh-CN': '快讯', en: 'Ticker' }, values: { speed: 180, hoverSpeed: 0.5, gap: 20, fade: 48 } },
    { id: 'vertical', name: { 'zh-CN': '竖流', en: 'Vertical' }, values: { direction: 'vertical', speed: 50, gap: 20, fade: 64 } },
  ],
  dependencies: ['@motif/runtime'],
  perf: { webgl: false, maxDpr: 2 },
  a11y: { reducedMotion: 'static' },
  capture: { zoom: 1.5, posterTime: 3, loop: 12 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'motion-primitives',
      repo: 'ibelick/motion-primitives',
      sha: '120f64f6ca60348e251f929e9c81f11ccbe45eda',
      paths: ['components/core/infinite-slider.tsx'],
      spdx: 'MIT',
      copyright: ['Copyright (c) 2024 ibelick'],
    },
    modifications: [
      'cn now comes from motif-runtime and react-use-measure was replaced by ResizeObserver.',
      'The motion animate() loop was replaced by motif-runtime useFrameLoop, so it pauses offscreen and in hidden tabs; hover eases the speed toward a multiple of the normal speed (hoverSpeed) instead of restarting the animation.',
      'The content is repeated as many times as needed to cover the container (upstream repeats it exactly twice), the repeated copies are aria-hidden, and edges can fade out.',
      'Added reduced-motion handling (upstream has none): the slider stops and becomes manually scrollable.',
      'Defaults moved into the generated defaults region.',
    ],
    assets: [],
  },
})
