import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'style-hand-drawn',
  status: 'published',
  title: { 'zh-CN': '手绘草图', en: 'Hand-Drawn Sketch' },
  summary: {
    'zh-CN': '歪歪扭扭的铅笔轮廓、斜线排线的阴影、便利贴和胶带：一切都像画在笔记本页边，却完全可用。适合创意工具、儿童教育、工作室主页和轻松的品牌。',
    en: 'Wobbly pencil outlines, hatched shadows, sticky notes and tape: everything looks sketched in a notebook margin and still works. For creative tools, education, studio sites and friendly brands.',
  },
  kind: 'style',
  category: 'playful',
  tags: ['hand-drawn', 'sketch', 'paper', 'doodle', 'playful', 'tokens', 'design system'],
  runtime: ['react', 'css'],
  entry: { file: 'style-hand-drawn.tsx', export: 'HandDrawn' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'light' },
  files: [
    { path: 'style-hand-drawn.tsx', role: 'component' },
    { path: 'style-hand-drawn.css', role: 'style' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    {
      key: 'accent',
      type: 'color',
      group: 'look',
      label: { 'zh-CN': '彩铅色', en: 'Pencil color' },
      hint: {
        'zh-CN': '按钮、选中态和强调线的颜色，底色也会带一点这个色',
        en: 'Buttons, selected tabs and accents; the paper picks up a hint of it',
      },
      default: '#ff6b57',
    },
    {
      key: 'wobble',
      type: 'number',
      group: 'shape',
      label: { 'zh-CN': '歪扭程度', en: 'Wobble' },
      hint: { 'zh-CN': '0 是规整的矩形，越大边角越不规则', en: '0 gives clean rectangles, higher is looser' },
      default: 15,
      min: 0,
      max: 24,
      step: 1,
      safe: [6, 20],
    },
    {
      key: 'lineWidth',
      type: 'number',
      group: 'shape',
      label: { 'zh-CN': '铅笔线粗细', en: 'Line weight' },
      default: 2.5,
      min: 1.5,
      max: 4,
      step: 0.5,
      unit: 'px',
      safe: [2, 3.5],
    },
    {
      key: 'hatchOffset',
      type: 'number',
      group: 'shape',
      label: { 'zh-CN': '排线阴影偏移', en: 'Hatch shadow offset' },
      default: 4,
      min: 0,
      max: 8,
      step: 1,
      unit: 'px',
      safe: [2, 6],
    },
    {
      key: 'fontPairing',
      type: 'select',
      group: 'type',
      label: { 'zh-CN': '字体搭配', en: 'Font pairing' },
      default: 'bricolage',
      options: [
        { value: 'bricolage', label: { 'zh-CN': '布里科拉 + 曼罗普', en: 'Bricolage + Manrope' } },
        { value: 'fraunces', label: { 'zh-CN': '弗劳恩斯 + Jakarta', en: 'Fraunces + Jakarta Sans' } },
        { value: 'instrument', label: { 'zh-CN': '乐器衬线 + Inter Tight', en: 'Instrument Serif + Inter Tight' } },
        { value: 'syne', label: { 'zh-CN': 'Syne + Outfit', en: 'Syne + Outfit' } },
      ],
    },
    {
      key: 'density',
      type: 'number',
      group: 'layout',
      label: { 'zh-CN': '疏密', en: 'Density' },
      default: 1,
      min: 0.85,
      max: 1.2,
      step: 0.05,
      unit: 'x',
      safe: [0.9, 1.15],
    },
    {
      key: 'tilt',
      type: 'boolean',
      group: 'look',
      label: { 'zh-CN': '卡片微微歪斜', en: 'Crooked cards' },
      default: true,
    },
    {
      key: 'grid',
      type: 'boolean',
      group: 'look',
      label: { 'zh-CN': '点阵纸', en: 'Dot-grid paper' },
      default: true,
    },
  ],
  presets: [
    {
      id: 'coral-pencil',
      name: { 'zh-CN': '珊瑚彩铅', en: 'Coral pencil' },
      values: {
        accent: '#ff6b57',
        wobble: 15,
        lineWidth: 2.5,
        hatchOffset: 4,
        density: 1,
        fontPairing: 'bricolage',
        tilt: true,
        grid: true,
      },
    },
    {
      id: 'sky-marker',
      name: { 'zh-CN': '天蓝马克笔', en: 'Sky marker' },
      values: {
        accent: '#4db2ff',
        wobble: 12,
        lineWidth: 3,
        hatchOffset: 5,
        density: 1,
        fontPairing: 'syne',
        tilt: true,
        grid: true,
      },
    },
    {
      id: 'leaf-green',
      name: { 'zh-CN': '青草绿', en: 'Leaf green' },
      values: {
        accent: '#5fc47a',
        wobble: 18,
        lineWidth: 2.5,
        hatchOffset: 3,
        density: 1.05,
        fontPairing: 'fraunces',
        tilt: true,
        grid: false,
      },
    },
    {
      id: 'neat-notebook',
      name: { 'zh-CN': '整齐笔记', en: 'Neat notebook' },
      values: {
        accent: '#a58bff',
        wobble: 6,
        lineWidth: 2,
        hatchOffset: 3,
        density: 0.95,
        fontPairing: 'instrument',
        tilt: false,
        grid: true,
      },
    },
  ],
  dependencies: ['@motif/runtime'],
  fonts: [
    'Bricolage Grotesque Variable',
    'Manrope Variable',
    'Fraunces Variable',
    'Plus Jakarta Sans Variable',
    'Instrument Serif',
    'Inter Tight Variable',
    'Syne Variable',
    'Outfit Variable',
  ],
  guidance: {
    use: [
      'Use for creative tools, note and whiteboard apps, kids and education products, studio and freelancer sites, and any brand that wants to feel warm, approachable and unpolished on purpose.',
      'Avoid for enterprise, finance or security products where the wobble would read as sloppy.',
    ],
    rules: [
      'Palette ratio: about 60% warm paper ground (a cream tinted by the accent, with an optional dot grid), 25% near-white paper surfaces, 8% the accent color pencil, 7% highlighter pops (yellow, mint, pink, sky). Ink is one warm near-black pencil (#2b2623), used at 88% opacity for outlines; never pure black or gray.',
      'Shapes: every container has an irregular outline made with four elliptical corner radii (PaperCSS-style sets, 15px base at wobble 15) and a 2-3px pencil line. Use a different radius set per element type (buttons, cards, inputs, badges) and never repeat the same set on neighbors. Circles are also irregular (55/45% ellipses).',
      'Shadows are hatched, not blurred: a 135-degree line pattern in the pencil color, offset 3-6px behind the shape. No blur, no glow, no gradients except the highlighter marks and the notebook rules.',
      'Typography: a friendly quirky grotesque or a soft serif for headings at weight 700-800 with slight negative tracking, a clean humanist sans for body. Use italic for meta and placeholders. Highlight one key word per screen with a highlighter mark, and underline titles with a hand-drawn squiggle.',
      'Decoration is doodled SVG with round line caps: stars, arrows, squiggles, a pencil, tape strips and sticky notes rotated 2-5 degrees. Cards may tilt by up to 0.6 degrees; never tilt forms or body text.',
      'Motion has a playful spring: 180ms cubic-bezier(0.34, 1.56, 0.64, 1), hover lifts and tilts buttons by about 1 degree and grows the hatch, press drops them onto the page. Reduced motion removes the transitions.',
      'Do not use perfect geometry, thin 1px lines, drop shadows with blur, glass, neon colors, more than four highlighter colors on one screen, or a handwriting font for long text.',
    ],
  },
  perf: { webgl: false, maxDpr: 2 },
  a11y: { reducedMotion: 'static' },
  capture: { scroll: true, posterTime: 0.5, loop: 8 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'papercss',
      repo: 'papercss/papercss',
      sha: 'b341c1606fca5b3880307d779414f43a5ccbc9b6',
      paths: ['src/core/_mixins.scss', 'src/components/_buttons.scss', 'src/components/_cards.scss'],
      spdx: 'ISC',
      copyright: ['Copyright (c) 2017–2018, Rhyne Vlaservich <rhyneav@gmail.com>'],
    },
    modifications: [
      'Kept the PaperCSS border-style idea (four irregular elliptical corner radii that make a rectangle look hand-cut) and its six radius sets, but expressed them as calc() expressions scaled by one wobble parameter, so 0 gives clean rectangles.',
      'Replaced the SCSS class stylesheet with a scoped .hd-root CSS file and plain React primitives (button, card, field, badge, tabs, sticky-note alert, switch); outlines and hatched shadows are drawn with two pseudo-element layers instead of the upstream soft blurred shadow.',
      'Added the hatch shadow, dotted-paper ground, sticky notes, tape, highlighter marks and the inline SVG doodles (pencil, star, squiggle, arrow), all drawn for this item; the accent color drives fills and the text color on it is picked by contrast.',
      'No handwriting font is bundled: the sketch feel comes from shapes, and the type uses self-hosted OFL families from the Motif font list.',
    ],
    assets: [],
  },
})
