import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'grain-gradient',
  status: 'published',
  title: { "zh-CN": '颗粒渐变', en: 'Grain Gradient' },
  summary: {
    "zh-CN": '渐变里带着胶片般的颗粒，可以是柔和的角落光晕、波浪、圆点或水波纹。适合做有质感的首屏背景。',
    en: 'Gradients with a printed, film-like grain, shaped as soft corner glows, waves, dots or ripples. A textured backdrop for hero sections.',
  },
  category: 'background',
  tags: ['gradient', 'grain', 'noise', 'shader', 'webgl', 'texture'],
  runtime: ['react', 'webgl2'],
  entry: { file: 'grain-gradient.tsx', export: 'GrainGradientBackground' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'grain-gradient.tsx', role: 'component' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    {
      key: 'colors',
      type: 'palette',
      label: { "zh-CN": '颜色', en: 'Colors' },
      hint: { "zh-CN": '渐变里的色块，最多 7 个', en: 'Gradient colors, up to 7' },
      default: ['#7300ff', '#eba8ff', '#00bfff', '#2a00ff'],
      minItems: 1,
      maxItems: 7,
    },
    { key: 'colorBack', type: 'color', label: { "zh-CN": '底色', en: 'Background' }, default: '#000000' },
    {
      key: 'shape',
      type: 'select',
      label: { "zh-CN": '形状', en: 'Shape' },
      default: 'corners',
      options: [
        { value: 'corners', label: { "zh-CN": '角落', en: 'Corners' } },
        { value: 'wave', label: { "zh-CN": '波浪', en: 'Wave' } },
        { value: 'dots', label: { "zh-CN": '圆点', en: 'Dots' } },
        { value: 'truchet', label: { "zh-CN": '迷宫', en: 'Truchet' } },
        { value: 'ripple', label: { "zh-CN": '水波', en: 'Ripple' } },
        { value: 'blob', label: { "zh-CN": '团块', en: 'Blob' } },
        { value: 'sphere', label: { "zh-CN": '球体', en: 'Sphere' } },
      ],
      group: 'look',
    },
    {
      key: 'softness',
      type: 'number',
      label: { "zh-CN": '柔和度', en: 'Softness' },
      default: 0.5,
      min: 0,
      max: 1,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'intensity',
      type: 'number',
      label: { "zh-CN": '强度', en: 'Intensity' },
      hint: { "zh-CN": '形状之间的对比', en: 'Contrast between the shape bands' },
      default: 0.5,
      min: 0,
      max: 1,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'noise',
      type: 'number',
      label: { "zh-CN": '颗粒', en: 'Grain' },
      default: 0.25,
      min: 0,
      max: 1,
      step: 0.01,
      safe: [0.05, 0.8],
      group: 'look',
    },
    {
      key: 'speed',
      type: 'number',
      label: { "zh-CN": '速度', en: 'Speed' },
      default: 1,
      min: 0,
      max: 3,
      step: 0.01,
      safe: [0.2, 2],
      unit: 'x',
      group: 'motion',
    },
    {
      key: 'scale',
      type: 'number',
      label: { "zh-CN": '缩放', en: 'Scale' },
      default: 1,
      min: 0.3,
      max: 3,
      step: 0.01,
      safe: [0.4, 2],
      unit: 'x',
      group: 'layout',
    },
    {
      key: 'rotation',
      type: 'number',
      label: { "zh-CN": '旋转', en: 'Rotation' },
      default: 0,
      min: 0,
      max: 360,
      step: 1,
      unit: 'deg',
      group: 'layout',
    },
  ],
  presets: [
    {
      id: 'aurora',
      name: { "zh-CN": '极光', en: 'Aurora' },
      values: {
        colors: ['#7300ff', '#eba8ff', '#00bfff', '#2a00ff'],
        colorBack: '#000000',
        shape: 'corners',
        softness: 0.5,
        intensity: 0.5,
        noise: 0.25,
        speed: 1,
        scale: 1,
        rotation: 0,
      },
    },
    {
      id: 'dune',
      name: { "zh-CN": '沙丘', en: 'Dune' },
      values: {
        colors: ['#c4730b', '#bdad5f', '#d8ccc7'],
        colorBack: '#000a0f',
        shape: 'wave',
        softness: 0.7,
        intensity: 0.15,
        noise: 0.5,
        speed: 1,
        scale: 1,
        rotation: 0,
      },
    },
    {
      id: 'ember',
      name: { "zh-CN": '余烬', en: 'Ember' },
      values: {
        colors: ['#6f2d00', '#88ddae', '#2c0b1d'],
        colorBack: '#140a00',
        shape: 'ripple',
        softness: 0.5,
        intensity: 0.5,
        noise: 0.5,
        speed: 1,
        scale: 0.5,
        rotation: 0,
      },
    },
    {
      id: 'moss',
      name: { "zh-CN": '苔藓', en: 'Moss' },
      values: {
        colors: ['#3e6172', '#a49b74', '#568c50'],
        colorBack: '#0f0e18',
        shape: 'blob',
        softness: 0,
        intensity: 0.15,
        noise: 0.5,
        speed: 1,
        scale: 1.3,
        rotation: 0,
      },
    },
    {
      id: 'glacier',
      name: { "zh-CN": '冰川', en: 'Glacier' },
      values: {
        colors: ['#0b3d91', '#7fd6ff', '#e8f7ff'],
        colorBack: '#020b1f',
        shape: 'sphere',
        softness: 0.85,
        intensity: 0.35,
        noise: 0.55,
        speed: 1,
        scale: 1.1,
        rotation: 0,
      },
    },
  ],
  dependencies: ['@paper-design/shaders-react', '@motif/runtime'],
  perf: { webgl: true, maxDpr: 1.5 },
  a11y: { reducedMotion: 'static' },
  capture: { posterTime: 2 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'paper-shaders',
      repo: 'paper-design/shaders',
      sha: '43cd68db79fa0b1759f72ffc941b3238e2a3954c',
      paths: ['packages/shaders-react/src/shaders/grain-gradient.tsx', 'docs/src/shader-defs/grain-gradient-def.ts'],
      spdx: 'Apache-2.0',
      copyright: ['Paper Shaders (https://shaders.paper.design)'],
    },
    modifications: ['Wrapped the Paper GrainGradient component as a full-bleed background that can hold children; the pattern shapes switch to pattern sizing (fit none), the object shapes keep contain, as in the upstream presets.', 'Parameter ranges adapted from the Paper docs; the Aurora (default), Dune, Ember and Moss presets follow the upstream Default, Wave, Ripple and Blob presets; Glacier is Motif’s.', 'Renders a static frame when the user prefers reduced motion.'],
    assets: [],
  },
})
