import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'simplex-noise',
  status: 'published',
  title: { "zh-CN": '单纯形噪声', en: 'Simplex Noise' },
  summary: {
    "zh-CN": '一层层等高线般的色带在噪声里缓缓变形，硬边或柔边都好看。适合做地形图、糖果色或印刷风背景。',
    en: 'Contour-like color bands morph slowly through noise, hard-edged or soft. For topographic, candy-colored or print-style backdrops.',
  },
  kind: 'effect',
  category: 'background',
  tags: ['noise', 'contour', 'gradient', 'shader', 'webgl', 'pattern'],
  runtime: ['react', 'webgl2'],
  entry: { file: 'simplex-noise.tsx', export: 'SimplexNoiseBackground' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'simplex-noise.tsx', role: 'component' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    {
      key: 'colors',
      type: 'palette',
      label: { "zh-CN": '颜色', en: 'Colors' },
      default: ['#4449cf', '#ffd1e0', '#f94446', '#ffd36b', '#ffffff'],
      minItems: 2,
      maxItems: 10,
    },
    {
      key: 'stepsPerColor',
      type: 'number',
      label: { "zh-CN": '色阶数', en: 'Steps per color' },
      hint: { "zh-CN": '每两种颜色之间的层数', en: 'Bands between two neighboring colors' },
      default: 2,
      min: 1,
      max: 6,
      step: 1,
      group: 'look',
    },
    {
      key: 'softness',
      type: 'number',
      label: { "zh-CN": '柔和度', en: 'Softness' },
      default: 0,
      min: 0,
      max: 1,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'speed',
      type: 'number',
      label: { "zh-CN": '速度', en: 'Speed' },
      default: 0.5,
      min: 0,
      max: 3,
      step: 0.01,
      safe: [0.1, 2],
      unit: 'x',
      group: 'motion',
    },
    {
      key: 'scale',
      type: 'number',
      label: { "zh-CN": '缩放', en: 'Scale' },
      default: 0.6,
      min: 0.2,
      max: 3,
      step: 0.01,
      safe: [0.2, 2],
      unit: 'x',
      group: 'layout',
    },
    {
      key: 'rotation',
      type: 'number',
      label: { "zh-CN": '旋转', en: 'Rotation' },
      default: 0,
      min: 0,
      max: 360,
      step: 1,
      unit: 'deg',
      group: 'layout',
    },
  ],
  presets: [
    {
      id: 'confetti',
      name: { "zh-CN": '彩纸', en: 'Confetti' },
      values: {
        colors: ['#4449cf', '#ffd1e0', '#f94446', '#ffd36b', '#ffffff'],
        stepsPerColor: 2,
        softness: 0,
        speed: 0.5,
        scale: 0.6,
        rotation: 0,
      },
    },
    {
      id: 'bubblegum',
      name: { "zh-CN": '泡泡糖', en: 'Bubblegum' },
      values: {
        colors: ['#ffffff', '#ff9e9e', '#5f57ff', '#00f7ff'],
        stepsPerColor: 1,
        softness: 1,
        speed: 1,
        scale: 1.6,
        rotation: 0,
      },
    },
    {
      id: 'spots',
      name: { "zh-CN": '斑点', en: 'Spots' },
      values: {
        colors: ['#ff7b00', '#f9ffeb', '#320d82'],
        stepsPerColor: 1,
        softness: 0,
        speed: 0.6,
        scale: 1,
        rotation: 0,
      },
    },
    {
      id: 'contact',
      name: { "zh-CN": '第一类接触', en: 'First contact' },
      values: {
        colors: ['#e8cce6', '#120d22', '#442c44', '#e6baba', '#fff5f5'],
        stepsPerColor: 2,
        softness: 0,
        speed: 1,
        scale: 0.2,
        rotation: 0,
      },
    },
    {
      id: 'dusk',
      name: { "zh-CN": '暮色', en: 'Dusk' },
      values: {
        colors: ['#0f172a', '#4338ca', '#f472b6', '#fde68a'],
        stepsPerColor: 3,
        softness: 1,
        speed: 0.4,
        scale: 0.5,
        rotation: 0,
      },
    },
  ],
  dependencies: ['@paper-design/shaders-react', '@motif/runtime'],
  perf: { webgl: true, maxDpr: 1.5 },
  a11y: { reducedMotion: 'static' },
  capture: { posterTime: 2 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'paper-shaders',
      repo: 'paper-design/shaders',
      sha: '43cd68db79fa0b1759f72ffc941b3238e2a3954c',
      paths: ['packages/shaders-react/src/shaders/simplex-noise.tsx', 'docs/src/shader-defs/simplex-noise-def.ts'],
      spdx: 'Apache-2.0',
      copyright: ['Paper Shaders (https://shaders.paper.design)'],
    },
    modifications: ['Wrapped the Paper SimplexNoise component as a full-bleed background that can hold children.', 'Parameter ranges adapted from the Paper docs; Confetti (default), Bubblegum, Spots and First contact follow the upstream presets (speeds lowered); Dusk is Motif’s.', 'Renders a static frame when the user prefers reduced motion.'],
    assets: [],
  },
})
