import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'toast-stack',
  status: 'published',
  title: { 'zh-CN': '堆叠通知', en: 'Toast Stack' },
  summary: {
    'zh-CN': 'sonner 风格的堆叠 toast：折叠时后面的卡片缩小露出一线，悬停展开成列表并暂停计时，可以向外划走。支持加载中变成功的原地更新、操作按钮、六个位置和读屏播报。',
    en: 'Sonner-style stacking toasts: cards tuck behind the newest one, expand into a list on hover and pause their timers, and swipe away. Supports loading-to-success updates in place, action buttons, six positions and screen-reader announcements.',
  },
  kind: 'component',
  category: 'toast',
  tags: ['toast', 'notification', 'stack', 'swipe', 'sonner', 'feedback', 'accessible'],
  runtime: ['react', 'motion', 'css'],
  entry: { file: 'toast-stack.tsx', export: 'ToastStack' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'toast-stack.tsx', role: 'component' },
    { path: 'toast-stack.css', role: 'style' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    {
      key: 'position',
      type: 'select',
      group: 'layout',
      label: { 'zh-CN': '位置', en: 'Position' },
      default: 'bottom-right',
      options: [
        { value: 'bottom-right', label: { 'zh-CN': '右下', en: 'Bottom right' } },
        { value: 'bottom-center', label: { 'zh-CN': '下中', en: 'Bottom center' } },
        { value: 'bottom-left', label: { 'zh-CN': '左下', en: 'Bottom left' } },
        { value: 'top-right', label: { 'zh-CN': '右上', en: 'Top right' } },
        { value: 'top-center', label: { 'zh-CN': '上中', en: 'Top center' } },
        { value: 'top-left', label: { 'zh-CN': '左上', en: 'Top left' } },
      ],
    },
    { key: 'width', type: 'number', group: 'layout', label: { 'zh-CN': '宽度', en: 'Width' }, default: 356, min: 260, max: 460, step: 4, unit: 'px', safe: [300, 400] },
    { key: 'gap', type: 'number', group: 'layout', label: { 'zh-CN': '展开间距', en: 'Gap' }, hint: { 'zh-CN': '折叠时也决定后面卡片露出多少', en: 'Also sets how much of the cards behind peek out when collapsed' }, default: 14, min: 8, max: 24, step: 1, unit: 'px', safe: [10, 18] },
    { key: 'visibleToasts', type: 'number', group: 'layout', label: { 'zh-CN': '同时可见', en: 'Visible toasts' }, default: 3, min: 1, max: 5, step: 1 },
    { key: 'duration', type: 'number', group: 'interaction', label: { 'zh-CN': '停留时间', en: 'Duration' }, hint: { 'zh-CN': '错误类自动加倍；加载中的不会自动消失', en: 'Errors last twice as long; loading toasts never expire on their own' }, default: 4, min: 2, max: 10, step: 0.5, unit: 's', safe: [3, 6] },
    { key: 'radius', type: 'number', group: 'look', label: { 'zh-CN': '圆角', en: 'Corner radius' }, default: 14, min: 4, max: 24, step: 1, unit: 'px', safe: [8, 20] },
    { key: 'richColors', type: 'boolean', group: 'look', label: { 'zh-CN': '按类型着色', en: 'Rich colors' }, default: false },
    { key: 'expandOnHover', type: 'boolean', group: 'interaction', label: { 'zh-CN': '悬停展开', en: 'Expand on hover' }, default: true },
    { key: 'spring', type: 'spring', group: 'motion', label: { 'zh-CN': '出入弹簧', en: 'Motion spring' }, default: { visualDuration: 0.45, bounce: 0.12 } },
  ],
  presets: [
    { id: 'quiet', name: { 'zh-CN': '静默', en: 'Quiet' }, values: { position: 'bottom-right', radius: 14, richColors: false, spring: { visualDuration: 0.45, bounce: 0.12 } } },
    { id: 'signal', name: { 'zh-CN': '信号灯', en: 'Signal' }, values: { position: 'top-right', radius: 10, richColors: true, spring: { visualDuration: 0.4, bounce: 0.05 } } },
    { id: 'pill', name: { 'zh-CN': '药丸', en: 'Pill' }, values: { position: 'bottom-center', radius: 22, width: 340, richColors: false, spring: { visualDuration: 0.55, bounce: 0.3 } } },
    { id: 'compact', name: { 'zh-CN': '紧凑', en: 'Compact' }, values: { position: 'top-center', radius: 8, width: 300, gap: 10, visibleToasts: 2, duration: 3 } },
  ],
  dependencies: ['motion/react', '@motif/runtime'],
  perf: { webgl: false, maxDpr: 2 },
  a11y: { reducedMotion: 'crossfade' },
  guidance: {
    use: ['Use for transient, non-blocking feedback: saves, background jobs, incoming events. Anything the user must act on to continue belongs in a dialog or inline message, not a toast.'],
    rules: [
      'The component is controlled: keep the toast list in state, append new toasts to the end, update a toast in place by reusing its id (loading to success), and remove it in onDismiss.',
      'Mount it inside a position: relative container; it pins itself to a corner of that container.',
      'Keep titles short and put detail in description; error toasts last twice as long and use role="alert".',
      'Do not remove pause-on-hover/focus or the close button; they are what makes timed toasts accessible.',
    ],
  },
  capture: { zoom: 1.6, posterTime: 7.4, loop: 12 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'sonner',
      repo: 'emilkowalski/sonner',
      sha: '8e4662b39255120b62138312058f5d77c0139a5e',
      paths: ['src/index.tsx', 'src/styles.css', 'src/assets.tsx'],
      spdx: 'MIT',
      copyright: ['Copyright (c) 2023 Emil Kowalski'],
    },
    modifications: [
      'Rebuilt the stacking behavior as a controlled React component on motion springs instead of CSS variables and the global toast store: cards scale down 5% per layer and peek out by the gap when collapsed, and expand to their measured heights on hover or focus.',
      'Kept sonner constants (three visible, 14 px gap, 356 px width, 4 s lifetime, 45 px swipe threshold) and its icon paths and 12-bar loading spinner; timers pause on hover, focus, drag and hidden tabs but run on rAF and performance.now so they are deterministic under the capture clock.',
      'Dropped the promise API, custom JSX toasts, theming and the Toaster provider; toasts update in place by id (for example loading to success) and errors last twice as long.',
      'Added six positions with matching swipe direction, a visible-toasts limit, rich colors, action buttons and a reduced-motion state (fades only; the loading spinner freezes and breathes).',
    ],
    assets: [],
  },
})
