import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'typography-vortex',
  status: 'published',
  title: { 'zh-CN': '文字漩涡', en: 'Typography Vortex' },
  summary: {
    'zh-CN': '一圈圈缓缓旋转的文字环，指针经过时字形溶解成飘散的尘埃，点击则把尘埃吸向一点。文案可自定义，深浅两种底色。适合做品牌页、作品集的氛围背景。',
    en: 'Concentric rings of your own text rotate slowly; the pointer dissolves glyphs into drifting dust and a click sucks it into a point. Dark and light surfaces. An atmospheric backdrop for brand and portfolio pages.',
  },
  category: 'text',
  tags: ['typography', 'vortex', 'rings', 'particles', 'canvas2d', 'interactive', 'pointer', 'click'],
  runtime: ['react', 'canvas2d'],
  entry: { file: 'typography-vortex.tsx', export: 'TypographyVortex' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'typography-vortex.tsx', role: 'component' },
    { path: 'vortex-renderer.ts', role: 'component' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    {
      key: 'phrase',
      type: 'text',
      label: { 'zh-CN': '文案', en: 'Text' },
      hint: { 'zh-CN': '沿圆环重复排列，建议大写字母加分隔符', en: 'Repeated around each ring; capitals with separators work best' },
      default: 'MOTIF / DESIGN IN MOTION / ',
      maxLength: 48,
      group: 'content',
    },
    {
      key: 'mode',
      type: 'select',
      label: { 'zh-CN': '底色', en: 'Surface' },
      default: 'dark',
      options: [
        { value: 'dark', label: { 'zh-CN': '深色', en: 'Dark' } },
        { value: 'light', label: { 'zh-CN': '浅色', en: 'Light' } },
      ],
      group: 'look',
    },
    { key: 'speed', type: 'number', label: { 'zh-CN': '旋转速度', en: 'Rotation speed' }, default: 1, min: 0.2, max: 2.5, step: 0.01, unit: 'x', safe: [0.4, 1.8], group: 'motion' },
    {
      key: 'ringGrowth',
      type: 'number',
      label: { 'zh-CN': '环间距', en: 'Ring growth' },
      hint: { 'zh-CN': '越小圆环越密', en: 'Lower values pack the rings tighter' },
      default: 1.21,
      min: 1.1,
      max: 1.4,
      step: 0.01,
      group: 'look',
    },
    { key: 'opacity', type: 'number', label: { 'zh-CN': '文字浓度', en: 'Ink strength' }, default: 1, min: 0.4, max: 1, step: 0.01, group: 'look' },
    {
      key: 'dissolveRadius',
      type: 'number',
      label: { 'zh-CN': '溶解半径', en: 'Dissolve radius' },
      default: 1,
      min: 0.6,
      max: 1.5,
      step: 0.01,
      group: 'interaction',
    },
    {
      key: 'particleAmount',
      type: 'number',
      label: { 'zh-CN': '粒子数量', en: 'Particles' },
      default: 1,
      min: 0.3,
      max: 1.6,
      step: 0.05,
      group: 'interaction',
    },
    {
      key: 'suctionDuration',
      type: 'number',
      label: { 'zh-CN': '吸入时长', en: 'Suction time' },
      hint: { 'zh-CN': '点击后尘埃被吸走的时间', en: 'How long a click pulls dust in' },
      default: 920,
      min: 400,
      max: 1500,
      step: 20,
      unit: 'ms',
      group: 'interaction',
    },
  ],
  presets: [
    { id: 'signal', name: { 'zh-CN': '信号', en: 'Signal' }, values: {} },
    {
      id: 'paper',
      name: { 'zh-CN': '素纸', en: 'Paper' },
      values: { mode: 'light', phrase: 'FORM FOLLOWS FEELING / ', speed: 0.7, opacity: 0.9 },
    },
    {
      id: 'binary-rain',
      name: { 'zh-CN': '二进制雨', en: 'Binary rain' },
      values: { phrase: '01 10 11 00 ', ringGrowth: 1.11, speed: 1.5, particleAmount: 1.3 },
    },
    {
      id: 'slow-tide',
      name: { 'zh-CN': '慢潮', en: 'Slow tide' },
      values: { phrase: 'SLOW DOWN / LOOK CLOSER / ', speed: 0.45, ringGrowth: 1.3, dissolveRadius: 1.4, particleAmount: 1.5, suctionDuration: 1300 },
    },
    {
      id: 'ledger',
      name: { 'zh-CN': '账本', en: 'Ledger' },
      values: { mode: 'light', phrase: 'EST. 2026 * MOTIF * ', ringGrowth: 1.14, speed: 1.1, dissolveRadius: 0.8 },
    },
  ],
  dependencies: ['@motif/runtime'],
  perf: { webgl: false, maxDpr: 1.5 },
  a11y: { reducedMotion: 'static' },
  capture: { posterTime: 6 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'threeui',
      repo: 'MengTo/threeui',
      sha: '68802d5428071ada5c20db8094b1649e6bb770ed',
      paths: ['src/shaders/typography-vortex/TypographyVortexCanvas.tsx', 'src/shaders/typography-vortex/typographyVortexRenderer.ts'],
      spdx: 'MIT',
      copyright: ['Copyright (c) 2026 Meng To'],
      origin: 'Sable V1',
    },
    modifications: [
      'The requestAnimationFrame / IntersectionObserver loop was replaced by motif-runtime useFrameLoop: pauses offscreen and in hidden tabs, and renders one static frame under reduced motion (dust and dissolve are off).',
      'The embedded Fragment Mono font is not included; rings use a system monospace stack. The device pixel ratio is capped at 1.5 and canvas bitmaps are released on unmount.',
      'The text is a param (split by code point so emoji survive) and the built-in hint label was removed; the suction start time comes from the frame clock instead of performance.now().',
      'The demo adds a synthetic pointer that stops as soon as the real pointer moves.',
    ],
    assets: [],
  },
})
