import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'hero-glowy-waves',
  status: 'published',
  title: { 'zh-CN': '发光波浪首屏', en: 'Glowy Waves Hero' },
  summary: {
    'zh-CN': '五条彩色光线在暗底上起伏，指针靠近时局部隆起；居中大标题、按钮和三格数据叠在上面。Canvas 2D 绘制，没有着色器也很轻。',
    en: 'Five luminous lines ripple across a dark field and swell near the pointer, with a centered headline, buttons and a three-up stat strip on top. Plain Canvas 2D, no shader needed and light on the GPU.',
  },
  kind: 'section',
  category: 'hero',
  tags: ['hero', 'waves', 'canvas', 'glow', 'pointer', 'dark'],
  runtime: ['react', 'motion', 'canvas2d'],
  entry: { file: 'hero-glowy-waves.tsx', export: 'HeroGlowyWaves' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'hero-glowy-waves.tsx', role: 'component' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    { key: 'headline', type: 'text', label: { 'zh-CN': '主标题', en: 'Headline' }, default: 'Live visuals that keep up with your data', maxLength: 64, group: 'content' },
    {
      key: 'subline',
      type: 'text',
      label: { 'zh-CN': '副标题', en: 'Subline' },
      default: 'Drive installations, lobby screens and launch pages from one timeline. Sub-10ms response, no render farm.',
      maxLength: 140,
      group: 'content',
    },
    { key: 'cta', type: 'text', label: { 'zh-CN': '主按钮', en: 'Button label' }, default: 'Book a demo', maxLength: 24, group: 'content' },
    {
      key: 'palette',
      type: 'palette',
      label: { 'zh-CN': '波浪配色', en: 'Wave colors' },
      hint: { 'zh-CN': '五条波依次取色，主按钮用第一种', en: 'Waves take the colors in turn; the button uses the first' },
      default: ['#7c5cff', '#22d3ee', '#f472b6'],
      minItems: 2,
      maxItems: 5,
      group: 'look',
    },
    {
      key: 'font',
      type: 'select',
      label: { 'zh-CN': '标题字体', en: 'Heading font' },
      default: 'geist',
      options: [
        { value: 'geist', label: { 'zh-CN': 'Geist 无衬线', en: 'Geist sans' } },
        { value: 'grotesk', label: { 'zh-CN': 'Space Grotesk', en: 'Space Grotesk' } },
        { value: 'serif', label: { 'zh-CN': 'Instrument 衬线', en: 'Instrument serif' } },
      ],
      group: 'look',
    },
    { key: 'radius', type: 'number', label: { 'zh-CN': '按钮圆角', en: 'Button radius' }, default: 999, min: 0, max: 999, step: 1, unit: 'px', safe: [8, 999], group: 'look' },
    {
      key: 'layout',
      type: 'select',
      label: { 'zh-CN': '波浪位置', en: 'Wave position' },
      default: 'behind',
      options: [
        { value: 'behind', label: { 'zh-CN': '穿过标题', en: 'Behind the text' } },
        { value: 'below', label: { 'zh-CN': '在文字下方', en: 'Below the text' } },
      ],
      group: 'layout',
    },
    { key: 'amplitude', type: 'number', label: { 'zh-CN': '波幅', en: 'Amplitude' }, default: 1, min: 0.4, max: 1.6, step: 0.05, unit: 'x', safe: [0.6, 1.4], group: 'motion' },
    { key: 'speed', type: 'number', label: { 'zh-CN': '流动速度', en: 'Speed' }, default: 1, min: 0.2, max: 2.5, step: 0.1, unit: 'x', safe: [0.5, 1.6], group: 'motion' },
    { key: 'pointer', type: 'number', label: { 'zh-CN': '指针影响', en: 'Pointer influence' }, default: 1, min: 0, max: 2, step: 0.1, unit: 'x', safe: [0.5, 1.5], group: 'interaction' },
  ],
  presets: [
    { id: 'aurora-line', name: { 'zh-CN': '极光线', en: 'Aurora Line' }, values: {} },
    { id: 'solar-flare', name: { 'zh-CN': '耀斑', en: 'Solar Flare' }, values: { palette: ['#ff6a3d', '#ffd23f', '#ff3d81'], layout: 'below', font: 'grotesk' } },
    { id: 'deep-sea', name: { 'zh-CN': '深海', en: 'Deep Sea' }, values: { palette: ['#22d3ee', '#3b82f6', '#34d399'], amplitude: 0.8, speed: 0.6, font: 'serif' } },
  ],
  dependencies: ['motion/react', '@motif/runtime'],
  fonts: ['Geist Variable', 'Space Grotesk Variable', 'Instrument Serif'],
  guidance: {
    rules: [
      'The section is always dark: the waves use additive blending, which washes out on a light background.',
      'Use two to five palette colors that sit close on the wheel or share a temperature; three is the sweet spot.',
      'Keep the text block in the upper half and let the waves have the lower half, or put a dark radial scrim behind the headline as the demo does.',
    ],
  },
  perf: { webgl: false, maxDpr: 1.5 },
  a11y: { reducedMotion: 'static' },
  capture: { posterTime: 3, loop: 8 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'uitripled',
      repo: 'moumen-soliman/uitripled',
      sha: '05d18376db775072ed61d0cab8ea184f8f527429',
      paths: ['packages/components/react-shadcn/src/components/sections/glowy-waves-hero.tsx'],
      spdx: 'MIT',
      copyright: ['Copyright (c) 2026 uitripled'],
    },
    modifications: [
      'Kept the layered sine waves and the pointer influence radius; the canvas is now sized to the section with useCanvasSize and animated by the Motif frame loop (time-driven, paused offscreen, one still frame under reduced motion).',
      'Colors come from a palette param instead of theme variables and a MutationObserver; the glow is two extra wide translucent strokes with additive blending instead of shadowBlur.',
      'A virtual pointer sweeps the waves when no real pointer is present; headline, pills, buttons and the stat strip were rewritten, and lucide icons removed.',
    ],
    assets: [],
  },
})
