import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'support-inbox-landing',
  status: 'published',
  title: { 'zh-CN': '共享收件箱产品页', en: 'Shared Inbox Landing' },
  summary: {
    'zh-CN': '浅色、圆润的产品官网：悬浮胶囊导航，首屏流动渐变托着一个三栏收件箱界面，往下是交替图文、评价墙、主色数据带与定价。',
    en: 'A light, rounded product site: a floating pill navbar, a hero where a flowing shader gradient holds a three-pane inbox, then alternating features, a review wall, an accent stats band and pricing.',
  },
  kind: 'template',
  category: 'product',
  tags: ['product', 'saas', 'landing', 'light', 'shader', 'pricing', 'testimonials'],
  runtime: ['react', 'motion', 'css', 'svg', 'webgl'],
  entry: { file: 'support-inbox-landing.tsx', export: 'SupportInboxLanding' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'light' },
  files: [
    { path: 'support-inbox-landing.tsx', role: 'component' },
    { path: 'sections.tsx', role: 'component' },
    { path: 'mockups.tsx', role: 'component' },
    { path: 'parts.tsx', role: 'lib' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    { key: 'brandName', type: 'text', label: { 'zh-CN': '品牌名', en: 'Brand name' }, default: 'Harbor', maxLength: 18, group: 'brand' },
    { key: 'accent', type: 'color', label: { 'zh-CN': '主色', en: 'Accent color' }, default: '#0d9488', group: 'brand' },
    {
      key: 'fontPair',
      type: 'select',
      label: { 'zh-CN': '字体搭配', en: 'Font pairing' },
      default: 'jakarta',
      options: [
        { value: 'jakarta', label: { 'zh-CN': 'Plus Jakarta Sans（友好）', en: 'Plus Jakarta Sans, friendly' } },
        { value: 'manrope', label: { 'zh-CN': 'Manrope（干净）', en: 'Manrope, clean' } },
        { value: 'fraunces', label: { 'zh-CN': 'Fraunces + Manrope（温暖）', en: 'Fraunces + Manrope, warm' } },
        { value: 'outfit', label: { 'zh-CN': 'Outfit + IBM Plex Sans（几何）', en: 'Outfit + IBM Plex Sans, geometric' } },
      ],
      group: 'brand',
    },
    { key: 'radius', type: 'number', label: { 'zh-CN': '圆角', en: 'Corner radius' }, default: 12, min: 4, max: 20, step: 1, unit: 'px', safe: [8, 16], group: 'look' },
    { key: 'dark', type: 'boolean', label: { 'zh-CN': '深色模式', en: 'Dark mode' }, default: false, group: 'look' },
    {
      key: 'headline',
      type: 'text',
      label: { 'zh-CN': '首屏标题', en: 'Hero headline' },
      hint: { 'zh-CN': '最好 60 字符以内', en: 'Best under 60 characters' },
      default: 'Support that feels like one conversation, not forty tickets',
      maxLength: 90,
      group: 'copy',
    },
    {
      key: 'subhead',
      type: 'text',
      label: { 'zh-CN': '首屏副标题', en: 'Hero sub-headline' },
      default: 'Email, chat and web forms land in a single shared inbox. Everyone sees who is replying, and customers never have to repeat themselves.',
      maxLength: 200,
      group: 'copy',
    },
  ],
  presets: [
    { id: 'lagoon', name: { 'zh-CN': '泻湖', en: 'Lagoon' }, values: { accent: '#0d9488', fontPair: 'jakarta', radius: 12, dark: false } },
    {
      id: 'apricot',
      name: { 'zh-CN': '杏子', en: 'Apricot' },
      values: { accent: '#e8590c', fontPair: 'fraunces', radius: 18, dark: false, brandName: 'Marigold' },
    },
    { id: 'indigo', name: { 'zh-CN': '靛青', en: 'Indigo' }, values: { accent: '#4f46e5', fontPair: 'manrope', radius: 8, dark: false, brandName: 'Relay' } },
    { id: 'midnight', name: { 'zh-CN': '午夜', en: 'Midnight' }, values: { accent: '#2dd4bf', fontPair: 'outfit', radius: 14, dark: true, brandName: 'Nightshift' } },
  ],
  dependencies: ['motion/react', '@paper-design/shaders-react', '@motif/runtime'],
  fonts: ['Plus Jakarta Sans Variable', 'Manrope Variable', 'Fraunces Variable', 'Outfit Variable', 'IBM Plex Sans Variable', 'IBM Plex Mono'],
  guidance: {
    use: [
      'A product marketing site for a collaborative, workflow-style SaaS (help desk, CRM, scheduling, docs). Friendly, light and rounded rather than technical.',
      'Works best when you can show the core screen in the hero. Replace the inbox mockup with your own product UI built in JSX or SVG.',
    ],
    rules: [
      'Keep the section order: floating navbar, hero with shader panel and product UI, partners, two alternating feature rows, steps, testimonials, accent stats band, pricing, FAQ, CTA, footer.',
      'The mesh-gradient panel behind the hero mockup is derived from the accent color. Do not hard-code its colors; change the accent instead.',
      'Use the accent color for one solid band (stats), primary buttons and small marks. Keep everything else on tinted neutrals so pages with any accent stay calm.',
      'Rounded pill controls (buttons, nav, toggles) and large radius cards are part of the voice. Keep the radius param between 8 and 16.',
      'Copy is plain and specific: invented but believable customer names, numbers with units, no exclamation marks or superlatives.',
      'No photos or logos of real companies: people are gradient initials, partners are invented SVG wordmarks, screens are JSX.',
    ],
  },
  perf: { webgl: true, maxDpr: 1.5 },
  a11y: { reducedMotion: 'static' },
  capture: { scroll: true, posterTime: 0.5, loop: 8 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'saas-landing-template',
      repo: 'gonzalochale/saas-landing-template',
      sha: '7bc36b2a7ae905314c6b7fc95e0168ce5bf0db49',
      paths: [
        'app/page.tsx',
        'components/hero.tsx',
        'components/partners.tsx',
        'components/testimonials.tsx',
        'components/stats.tsx',
        'components/pricing.tsx',
        'components/faq.tsx',
        'components/footer.tsx',
      ],
      spdx: 'MIT',
      copyright: ['Copyright (c) 2024 Gonzalo Chalé'],
    },
    modifications: [
      'Ported the section list (hero, partners, testimonials, stats, pricing, FAQ, footer) to React 19 and Tailwind v4 without Next.js, shadcn/ui, NumberFlow or framer-motion; motion comes from motion/react and icons are inline SVG.',
      'Partner logos are invented SVG wordmarks; avatar photos are gradient initials; the hero light beam became a Paper Shaders mesh gradient derived from the accent color.',
      'Added a three-pane inbox mockup, an automation rule card and a report chart (all JSX), plus a getting-started section and a floating pill navbar.',
      'Theming (brand, accent, fonts, radius, dark mode) is driven by props through CSS variables; layout uses container queries instead of viewport breakpoints.',
    ],
    assets: [],
  },
})
