import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'fluid-simulation',
  status: 'published',
  title: { 'zh-CN': '流体模拟', en: 'Fluid Simulation' },
  summary: {
    'zh-CN': '真正在 GPU 上求解的流体：彩色染料被不断搅动、卷成漩涡，带泛光。自己会流动，拖动指针还能亲手搅拌。适合做首屏或全屏背景。',
    en: 'A real Navier-Stokes fluid solved on the GPU: colored dye constantly stirred into curls and glowing with bloom. It flows on its own, and dragging the pointer stirs it by hand. Made for hero and full-screen backgrounds.',
  },
  kind: 'effect',
  category: 'background',
  tags: ['fluid', 'simulation', 'webgl', 'ink', 'interactive', 'hero'],
  runtime: ['react', 'webgl2'],
  entry: { file: 'fluid-simulation.tsx', export: 'FluidSimulation' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'fluid-simulation.tsx', role: 'component' },
    { path: 'fluid-engine.ts', role: 'lib' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    {
      key: 'dyeResolution',
      type: 'select',
      label: { 'zh-CN': '画质', en: 'Quality' },
      hint: { 'zh-CN': '染料的分辨率，越高越细腻也越吃 GPU', en: 'Dye resolution: sharper but heavier on the GPU' },
      default: '1024',
      options: [
        { value: '256', label: { 'zh-CN': '低', en: 'Low' } },
        { value: '512', label: { 'zh-CN': '中', en: 'Medium' } },
        { value: '1024', label: { 'zh-CN': '高', en: 'High' } },
      ],
      group: 'quality',
    },
    {
      key: 'simResolution',
      type: 'select',
      label: { 'zh-CN': '模拟精度', en: 'Simulation resolution' },
      hint: { 'zh-CN': '速度场的网格大小，越高涡旋越细', en: 'Velocity grid size: higher gives finer eddies' },
      default: '128',
      options: [
        { value: '64', label: { 'zh-CN': '粗', en: 'Coarse' } },
        { value: '128', label: { 'zh-CN': '标准', en: 'Standard' } },
        { value: '256', label: { 'zh-CN': '细', en: 'Fine' } },
      ],
      group: 'quality',
    },
    {
      key: 'densityDissipation',
      type: 'number',
      label: { 'zh-CN': '染料消散', en: 'Dye dissipation' },
      hint: { 'zh-CN': '越大颜色褪得越快', en: 'Higher values make the color fade faster' },
      default: 1.2,
      min: 0,
      max: 4,
      step: 0.01,
      safe: [0.4, 2.5],
      group: 'physics',
    },
    {
      key: 'velocityDissipation',
      type: 'number',
      label: { 'zh-CN': '流速衰减', en: 'Velocity dissipation' },
      hint: { 'zh-CN': '越大流动停得越快', en: 'Higher values make the flow settle faster' },
      default: 0.2,
      min: 0,
      max: 4,
      step: 0.01,
      safe: [0, 2],
      group: 'physics',
    },
    {
      key: 'pressure',
      type: 'number',
      label: { 'zh-CN': '压力', en: 'Pressure' },
      default: 0.8,
      min: 0,
      max: 1,
      step: 0.01,
      safe: [0.4, 1],
      group: 'physics',
    },
    {
      key: 'curl',
      type: 'number',
      label: { 'zh-CN': '涡度', en: 'Vorticity' },
      hint: { 'zh-CN': '越大漩涡越多越卷', en: 'Higher values roll the flow into more curls' },
      default: 30,
      min: 0,
      max: 50,
      step: 1,
      group: 'physics',
    },
    {
      key: 'splatRadius',
      type: 'number',
      label: { 'zh-CN': '笔触大小', en: 'Splat radius' },
      default: 0.25,
      min: 0.05,
      max: 0.8,
      step: 0.01,
      safe: [0.1, 0.5],
      group: 'input',
    },
    {
      key: 'splatForce',
      type: 'number',
      label: { 'zh-CN': '搅动力度', en: 'Splat force' },
      default: 6000,
      min: 1000,
      max: 12000,
      step: 100,
      group: 'input',
    },
    { key: 'bloom', type: 'boolean', label: { 'zh-CN': '泛光', en: 'Bloom' }, default: true, group: 'look' },
    {
      key: 'bloomIntensity',
      type: 'number',
      label: { 'zh-CN': '泛光强度', en: 'Bloom intensity' },
      default: 0.8,
      min: 0.1,
      max: 2,
      step: 0.01,
      safe: [0.3, 1.4],
      group: 'look',
    },
    {
      key: 'colorful',
      type: 'boolean',
      label: { 'zh-CN': '多彩', en: 'Colorful' },
      hint: { 'zh-CN': '关闭后只用一种色相，由随机种子决定', en: 'When off, a single hue chosen by the seed is used' },
      default: true,
      group: 'look',
    },
    {
      key: 'seed',
      type: 'seed',
      label: { 'zh-CN': '随机种子', en: 'Seed' },
      hint: { 'zh-CN': '决定自动搅动的路径、斑点和单色时的色相', en: 'Decides the autoplay paths, splats and the hue in single-color mode' },
      default: 7,
    },
  ],
  presets: [
    {
      id: 'aurora',
      name: { 'zh-CN': '极光', en: 'Aurora' },
      values: { colorful: true, seed: 7, densityDissipation: 1.2, curl: 30, bloom: true, bloomIntensity: 0.8 },
    },
    {
      id: 'ink',
      name: { 'zh-CN': '墨海', en: 'Deep ink' },
      values: { colorful: false, seed: 1, densityDissipation: 0.6, velocityDissipation: 0.4, curl: 22, splatRadius: 0.35, bloom: true, bloomIntensity: 0.6 },
    },
    {
      id: 'ember',
      name: { 'zh-CN': '余烬', en: 'Ember' },
      values: { colorful: false, seed: 5, densityDissipation: 1.4, velocityDissipation: 0.15, curl: 40, splatRadius: 0.2, bloom: true, bloomIntensity: 1.2 },
    },
    {
      id: 'marbling',
      name: { 'zh-CN': '大理石', en: 'Marbling' },
      values: { colorful: true, seed: 12, densityDissipation: 0.3, velocityDissipation: 0.9, curl: 12, splatRadius: 0.4, bloom: false },
    },
  ],
  dependencies: ['@motif/runtime'],
  perf: { webgl: true, maxDpr: 1.5 },
  a11y: { reducedMotion: 'static' },
  capture: { posterTime: 6, loop: 8 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'webgl-fluid',
      repo: 'PavelDoGreat/WebGL-Fluid-Simulation',
      sha: 'a2d292931f19d9b3b9f564e23e6c32729d2121c3',
      paths: ['script.js'],
      spdx: 'MIT',
      copyright: ['Copyright (c) 2017 Pavel Dobryakov'],
    },
    modifications: [
      'Ported script.js to TypeScript and split the solver into fluid-engine.ts; the render loop now runs on motif-runtime (pauses offscreen and in hidden tabs, renders a settled static frame under reduced motion).',
      'Removed dat.gui, the mobile promo and analytics code, screenshot capture, sunrays, and the logo and dithering images; the bloom dithering noise is now generated in the shader.',
      'Added a seeded autoplay (Lissajous stirrers plus periodic random splats derived from the seed and frame-loop time) so the effect is alive without input and deterministic; pointer drags still inject splats.',
      'Handles context loss and restore, resizes the buffers with the canvas, and releases the context on unmount.',
    ],
    assets: [],
  },
})
