import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'halftone-cmyk',
  status: 'published',
  title: { 'zh-CN': 'CMYK 半调', en: 'Halftone CMYK' },
  summary: {
    'zh-CN': '把画面拆成青、品红、黄、黑四色网点，像凑近了看的印刷海报；画面在网点下缓慢推拉，网点随之闪动。景色可以是海上日出、色团或一行大字，都在 Canvas 上现画；网点、墨色和纸色都能调，也有报纸和复古印刷的预设。',
    en: 'Splits the picture into cyan, magenta, yellow and black dots, like a printed poster seen up close; the picture slowly pushes in and out under the dots so they shimmer. The scene is a sunrise over the sea, colour blooms or a big word, drawn on a canvas at runtime; dots, inks and paper are all tunable, with newspaper and vintage presets.',
  },
  kind: 'effect',
  category: 'shader',
  tags: ['halftone', 'cmyk', 'print', 'risograph', 'retro', 'webgl', 'shader', 'paper'],
  runtime: ['react', 'webgl2', 'canvas2d'],
  entry: { file: 'halftone-cmyk.tsx', export: 'HalftoneCmykPrint' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'light' },
  files: [
    { path: 'halftone-cmyk.tsx', role: 'component' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    {
      key: 'scene',
      type: 'select',
      group: 'content',
      label: { 'zh-CN': '画面', en: 'Scene' },
      default: 'sun',
      options: [
        { value: 'sun', label: { 'zh-CN': '海上日出', en: 'Sunrise' } },
        { value: 'bloom', label: { 'zh-CN': '色团', en: 'Bloom' } },
        { value: 'type', label: { 'zh-CN': '大字', en: 'Type' } },
      ],
    },
    { key: 'text', type: 'text', group: 'content', label: { 'zh-CN': '文字', en: 'Text' }, hint: { 'zh-CN': '画面选「大字」时使用', en: 'Used when the scene is Type' }, default: 'PRINT', maxLength: 8 },
    {
      key: 'type',
      type: 'select',
      group: 'shape',
      label: { 'zh-CN': '网点', en: 'Dots' },
      default: 'ink',
      options: [
        { value: 'ink', label: { 'zh-CN': '油墨', en: 'Ink' } },
        { value: 'dots', label: { 'zh-CN': '圆点', en: 'Dots' } },
        { value: 'sharp', label: { 'zh-CN': '锐利', en: 'Sharp' } },
      ],
    },
    { key: 'size', type: 'number', group: 'shape', label: { 'zh-CN': '网点大小', en: 'Dot size' }, default: 0.6, min: 0, max: 1, step: 0.01, safe: [0.05, 0.9] },
    { key: 'contrast', type: 'number', group: 'shape', label: { 'zh-CN': '对比', en: 'Contrast' }, default: 1, min: 0.4, max: 2, step: 0.01, safe: [0.8, 1.6] },
    { key: 'softness', type: 'number', group: 'shape', label: { 'zh-CN': '柔和', en: 'Softness' }, default: 0.5, min: 0, max: 1, step: 0.01 },
    { key: 'gridNoise', type: 'number', group: 'shape', label: { 'zh-CN': '网格抖动', en: 'Grid noise' }, hint: { 'zh-CN': '网点位置的随机偏移，越大越像手工印刷', en: 'Random offsets of the dots; higher looks more hand-printed' }, default: 0.3, min: 0, max: 1, step: 0.01 },
    { key: 'colorBack', type: 'color', group: 'color', label: { 'zh-CN': '纸色', en: 'Paper' }, default: '#fbfaf5' },
    { key: 'colorC', type: 'color', group: 'color', label: { 'zh-CN': '青', en: 'Cyan' }, default: '#00b4ff' },
    { key: 'colorM', type: 'color', group: 'color', label: { 'zh-CN': '品红', en: 'Magenta' }, default: '#fc519f' },
    { key: 'colorY', type: 'color', group: 'color', label: { 'zh-CN': '黄', en: 'Yellow' }, default: '#ffd800' },
    { key: 'colorK', type: 'color', group: 'color', label: { 'zh-CN': '黑', en: 'Black' }, default: '#231f20' },
    { key: 'grain', type: 'number', group: 'shape', label: { 'zh-CN': '纸纹', en: 'Paper grain' }, default: 0, min: 0, max: 0.5, step: 0.01 },
    { key: 'drift', type: 'number', group: 'motion', label: { 'zh-CN': '推拉幅度', en: 'Drift' }, hint: { 'zh-CN': '画面在网点下推拉的幅度，0 为静止', en: 'How far the picture pushes in and out; 0 keeps it still' }, default: 0.06, min: 0, max: 0.15, step: 0.01, safe: [0.02, 0.1] },
  ],
  presets: [
    { id: 'press', name: { 'zh-CN': '印刷', en: 'Press' }, values: {} },
    { id: 'drops', name: { 'zh-CN': '墨滴', en: 'Drops' }, values: { scene: 'bloom', colorBack: '#eeefd7', colorC: '#00b2ff', colorM: '#fc4f4f', colorY: '#ffd900', size: 0.88, contrast: 1.15, softness: 0, grain: 0.25, gridNoise: 0.5 } },
    { id: 'newspaper', name: { 'zh-CN': '报纸', en: 'Newspaper' }, values: { colorBack: '#f2f1e8', colorC: '#7a7a75', colorM: '#7a7a75', colorY: '#7a7a75', size: 0.01, contrast: 2, softness: 0.2, grain: 0.2, gridNoise: 0.6, type: 'dots' } },
    { id: 'vintage', name: { 'zh-CN': '复古', en: 'Vintage' }, values: { scene: 'type', colorBack: '#fffaf0', colorC: '#59afc5', colorM: '#d8697c', colorY: '#fad85c', colorK: '#2d2824', contrast: 1.25, softness: 0.4, grain: 0.1, gridNoise: 0.45, type: 'sharp' } },
  ],
  dependencies: ['@motif/runtime', '@paper-design/shaders-react'],
  fonts: ['Archivo Black'],
  perf: { webgl: true, maxDpr: 2 },
  a11y: { reducedMotion: 'static' },
  guidance: {
    use: ['Editorial, music, event and retro-print pages: a hero image, a poster section or a full-bleed band.'],
    rules: [
      'Choose pictures with big shapes and smooth tonal ramps; small detail dissolves into dots.',
      'Keep real text outside the halftone; the dots make small type unreadable.',
      'For a real photo, pass it as the image prop of the underlying Paper HalftoneCmyk component.',
    ],
  },
  capture: { posterTime: 3, loop: 12 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'paper-shaders',
      repo: 'paper-design/shaders',
      sha: '43cd68db79fa0b1759f72ffc941b3238e2a3954c',
      paths: ['packages/shaders-react/src/shaders/halftone-cmyk.tsx', 'docs/src/shader-defs/halftone-cmyk-def.ts'],
      spdx: 'Apache-2.0',
      copyright: ['Paper Shaders (https://shaders.paper.design)'],
    },
    modifications: [
      'The picture (a sunrise over the sea, colour blooms or a big word) is drawn on a canvas at runtime, so the item needs no image assets.',
      'The picture slowly pushes in and out under the dots (the upstream shader is static); the image is passed as an element so the per-frame change does not decode it again.',
      'The per-channel flood and gain controls are fixed at the upstream defaults. Parameter ranges adapted from the Paper docs; Drops, Newspaper and Vintage follow the upstream presets apart from those per-channel values; Press uses larger, softer-edged dots than the upstream default so the screen reads at a glance.',
      'Stays still when the user prefers reduced motion.',
    ],
    assets: [],
  },
})
