import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'warp',
  status: 'published',
  title: { "zh-CN": '扭曲漩涡', en: 'Warp' },
  summary: {
    "zh-CN": '方格、条纹或边缘线被层层漩涡卷曲，像流动的墨与丝绸。适合做大面积背景。',
    en: 'Checks, stripes or edges twisted through layered swirls, like drifting ink and silk. Made for large backdrops.',
  },
  kind: 'effect',
  category: 'background',
  tags: ['swirl', 'warp', 'ink', 'shader', 'webgl', 'background'],
  runtime: ['react', 'webgl2'],
  entry: { file: 'warp.tsx', export: 'WarpBackground' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'warp.tsx', role: 'component' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    {
      key: 'colors',
      type: 'palette',
      label: { "zh-CN": '颜色', en: 'Colors' },
      hint: { "zh-CN": '按顺序排成色带', en: 'Colors are laid out as bands in order' },
      default: ['#121212', '#9470ff', '#121212', '#8838ff'],
      minItems: 2,
      maxItems: 10,
    },
    {
      key: 'shape',
      type: 'select',
      label: { "zh-CN": '图案', en: 'Pattern' },
      default: 'checks',
      options: [
        { value: 'checks', label: { "zh-CN": '方格', en: 'Checks' } },
        { value: 'stripes', label: { "zh-CN": '条纹', en: 'Stripes' } },
        { value: 'edge', label: { "zh-CN": '边缘', en: 'Edge' } },
      ],
      group: 'look',
    },
    {
      key: 'shapeScale',
      type: 'number',
      label: { "zh-CN": '图案尺度', en: 'Pattern scale' },
      default: 0.1,
      min: 0,
      max: 1,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'proportion',
      type: 'number',
      label: { "zh-CN": '色带比例', en: 'Proportion' },
      default: 0.45,
      min: 0,
      max: 1,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'softness',
      type: 'number',
      label: { "zh-CN": '柔和度', en: 'Softness' },
      default: 1,
      min: 0,
      max: 1.5,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'distortion',
      type: 'number',
      label: { "zh-CN": '扭曲', en: 'Distortion' },
      default: 0.25,
      min: 0,
      max: 0.6,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'swirl',
      type: 'number',
      label: { "zh-CN": '漩涡', en: 'Swirl' },
      default: 0.8,
      min: 0,
      max: 1,
      step: 0.01,
      group: 'look',
    },
    {
      key: 'speed',
      type: 'number',
      label: { "zh-CN": '速度', en: 'Speed' },
      default: 1,
      min: 0,
      max: 12,
      step: 0.01,
      safe: [0.2, 6],
      unit: 'x',
      group: 'motion',
    },
    {
      key: 'scale',
      type: 'number',
      label: { "zh-CN": '缩放', en: 'Scale' },
      default: 1,
      min: 0.4,
      max: 3,
      step: 0.01,
      safe: [0.6, 2.5],
      unit: 'x',
      group: 'layout',
    },
    {
      key: 'rotation',
      type: 'number',
      label: { "zh-CN": '旋转', en: 'Rotation' },
      default: 0,
      min: 0,
      max: 360,
      step: 1,
      unit: 'deg',
      group: 'layout',
    },
  ],
  presets: [
    {
      id: 'amethyst',
      name: { "zh-CN": '紫晶', en: 'Amethyst' },
      values: {
        colors: ['#121212', '#9470ff', '#121212', '#8838ff'],
        shape: 'checks',
        shapeScale: 0.1,
        proportion: 0.45,
        softness: 1,
        distortion: 0.25,
        swirl: 0.8,
        speed: 1,
        scale: 1,
        rotation: 0,
      },
    },
    {
      id: 'cauldron',
      name: { "zh-CN": '药釜', en: 'Cauldron' },
      values: {
        colors: ['#a7e58b', '#324472', '#0a180d'],
        shape: 'edge',
        shapeScale: 0.6,
        proportion: 0.64,
        softness: 1.5,
        distortion: 0.2,
        swirl: 0.86,
        speed: 6,
        scale: 0.9,
        rotation: 160,
      },
    },
    {
      id: 'nectar',
      name: { "zh-CN": '花蜜', en: 'Nectar' },
      values: {
        colors: ['#151310', '#d3a86b', '#f0edea'],
        shape: 'edge',
        shapeScale: 0.75,
        proportion: 0.24,
        softness: 1,
        distortion: 0.21,
        swirl: 0.57,
        speed: 4.2,
        scale: 2,
        rotation: 0,
      },
    },
    {
      id: 'passion',
      name: { "zh-CN": '热恋', en: 'Passion' },
      values: {
        colors: ['#3b1515', '#954751', '#ffc085'],
        shape: 'checks',
        shapeScale: 0.25,
        proportion: 0.5,
        softness: 1,
        distortion: 0.09,
        swirl: 0.9,
        speed: 3,
        scale: 2.5,
        rotation: 1,
      },
    },
    {
      id: 'ink',
      name: { "zh-CN": '活墨', en: 'Live ink' },
      values: {
        colors: ['#111314', '#9faeab', '#f3fee7', '#f3fee7'],
        shape: 'checks',
        shapeScale: 0.28,
        proportion: 0.05,
        softness: 0,
        distortion: 0.25,
        swirl: 0.8,
        speed: 2.5,
        scale: 1.2,
        rotation: 44,
      },
    },
  ],
  dependencies: ['@paper-design/shaders-react', '@motif/runtime'],
  perf: { webgl: true, maxDpr: 1.5 },
  a11y: { reducedMotion: 'static' },
  capture: { posterTime: 2 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'paper-shaders',
      repo: 'paper-design/shaders',
      sha: '43cd68db79fa0b1759f72ffc941b3238e2a3954c',
      paths: ['packages/shaders-react/src/shaders/warp.tsx', 'docs/src/shader-defs/warp-def.ts'],
      spdx: 'Apache-2.0',
      copyright: ['Paper Shaders (https://shaders.paper.design)'],
    },
    modifications: ['Wrapped the Paper Warp component as a full-bleed background that can hold children.', 'Parameter ranges adapted from the Paper docs; Amethyst (default), Cauldron, Nectar, Passion and Live ink follow the upstream presets (Passion’s offsets and Live ink’s vertical offset dropped; Cauldron’s speed lowered).', 'Renders a static frame when the user prefers reduced motion.'],
    assets: [],
  },
})
