import { defineItem } from '@motif/schema'

export default defineItem({
  schemaVersion: 1,
  slug: 'laser',
  status: 'published',
  title: { 'zh-CN': '激光场', en: 'Laser' },
  summary: {
    'zh-CN': '四种深色背景上的激光场景：穿过薄雾的光刃、消失点的辐射光阵、棱镜光圈和半调中继光束，指针会让光束轻轻偏转。适合做科技、发布会类首屏。',
    en: 'Four laser scenes on a dark field: a blade cutting through haze, a vanishing-point array, a prism aperture and a halftone relay beam, all nudged by the pointer. For tech and launch-event heroes.',
  },
  category: 'shader',
  tags: ['laser', 'beam', 'glow', 'haze', 'prism', 'halftone', 'webgl', 'background', 'interactive', 'variants'],
  runtime: ['react', 'webgl'],
  entry: { file: 'laser.tsx', export: 'Laser' },
  demo: { file: 'demo.tsx', export: 'Demo', theme: 'dark' },
  files: [
    { path: 'laser.tsx', role: 'component' },
    { path: 'shaders.ts', role: 'shader' },
    { path: 'demo.tsx', role: 'demo' },
  ],
  params: [
    {
      key: 'variant',
      type: 'select',
      label: { 'zh-CN': '场景', en: 'Scene' },
      default: 'atmospheric-blade',
      options: [
        { value: 'atmospheric-blade', label: { 'zh-CN': '大气光刃', en: 'Atmospheric blade' } },
        { value: 'vanishing-array', label: { 'zh-CN': '消失点光阵', en: 'Vanishing array' } },
        { value: 'prism-aperture', label: { 'zh-CN': '棱镜光圈', en: 'Prism aperture' } },
        { value: 'halftone-relay', label: { 'zh-CN': '半调中继', en: 'Halftone relay' } },
      ],
    },
    { key: 'speed', type: 'number', label: { 'zh-CN': '速度', en: 'Speed' }, default: 1, min: 0.2, max: 2.5, step: 0.01, unit: 'x', safe: [0.4, 1.8], group: 'motion' },
    {
      key: 'size',
      type: 'number',
      label: { 'zh-CN': '光束粗细', en: 'Beam width' },
      hint: { 'zh-CN': '同时影响光晕的宽度', en: 'Also widens the glow' },
      default: 1,
      min: 0.5,
      max: 2,
      step: 0.01,
      safe: [0.6, 1.6],
      group: 'look',
    },
    { key: 'length', type: 'number', label: { 'zh-CN': '延伸长度', en: 'Reach' }, default: 1, min: 0.5, max: 2, step: 0.01, safe: [0.6, 1.6], group: 'look' },
    {
      key: 'density',
      type: 'number',
      label: { 'zh-CN': '密度', en: 'Density' },
      hint: { 'zh-CN': '雾的浓度、光线数量或网点大小，随场景而定', en: 'Haze thickness, ray count or dot size, depending on the scene' },
      default: 1,
      min: 0.4,
      max: 2,
      step: 0.01,
      safe: [0.5, 1.6],
      group: 'look',
    },
    { key: 'hue', type: 'number', label: { 'zh-CN': '色相', en: 'Hue' }, default: 0, min: -180, max: 180, step: 1, unit: 'deg', group: 'color' },
    { key: 'saturation', type: 'number', label: { 'zh-CN': '饱和度', en: 'Saturation' }, default: 1, min: 0.3, max: 1.6, step: 0.01, group: 'color' },
    { key: 'brightness', type: 'number', label: { 'zh-CN': '亮度', en: 'Brightness' }, default: 1, min: 0.6, max: 1.6, step: 0.01, group: 'color' },
  ],
  presets: [
    { id: 'blade', name: { 'zh-CN': '夜幕光刃', en: 'Night blade' }, values: { variant: 'atmospheric-blade' } },
    { id: 'array', name: { 'zh-CN': '消失点', en: 'Vanishing point' }, values: { variant: 'vanishing-array', brightness: 1.45, density: 1.3 } },
    { id: 'prism', name: { 'zh-CN': '棱镜', en: 'Prism' }, values: { variant: 'prism-aperture' } },
    { id: 'relay', name: { 'zh-CN': '半调', en: 'Halftone' }, values: { variant: 'halftone-relay' } },
    { id: 'red-line', name: { 'zh-CN': '赤线', en: 'Red line' }, values: { variant: 'atmospheric-blade', hue: -130, saturation: 1.2, size: 1.3, density: 1.4 } },
  ],
  dependencies: ['@motif/runtime'],
  perf: { webgl: true, maxDpr: 1.5 },
  a11y: { reducedMotion: 'static' },
  capture: { posterTime: 0.5 },
  provenance: {
    kind: 'upstream',
    upstream: {
      source: 'threeui',
      repo: 'MengTo/threeui',
      sha: '68802d5428071ada5c20db8094b1649e6bb770ed',
      paths: ['src/shaders/laser/LaserVariants.tsx', 'src/shaders/laser/laserShaders.ts', 'src/shaders/laser/LaserCollection.tsx'],
      spdx: 'MIT',
      copyright: ['Copyright (c) 2026 Meng To'],
      origin: 'ThreeUI original variants + preserved Neuform export',
    },
    modifications: [
      'Only the four shader variants of LaserVariants are ported; the preserved Matrix-field junction (a separate Neuform component in upstream) is not included.',
      'The render loop now uses motif-runtime: pauses offscreen and in hidden tabs, renders a static frame under reduced motion, and caps DPR at 1.5.',
      'Handles WebGL context loss and restore, and releases the context on unmount.',
      'The variant is a select parameter and parameter changes redraw immediately; opacity is dropped and every range is tightened.',
      'Defaults moved into the generated defaults region; children can be layered on top.',
    ],
    assets: [],
  },
})
